[package]
name = "bos-internals"
version = "0.1.1"
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Core internal data structures for Bible text representation, indexing, and manipulation"
keywords = ["bible", "usfm", "scripture"]
categories = ["text-processing", "parser-implementations"]

[dependencies]
compact_str.workspace = true
indexmap.workspace = true
pyo3 = { workspace = true, optional = true }
regex.workspace = true
rkyv.workspace = true
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[features]
default = []
python = ["dep:pyo3"]

# While we're still debugging
[profile.release]
debug = true

