[package]
name = "bos-internals"
version = "0.2.4"
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Core internal data structures for Bible text representation, indexing, and manipulation"
keywords = ["bible", "usfm", "scripture"]
categories = ["text-processing", "parser-implementations"]
publish = false

[dependencies]
log.workspace = true
bos_books_codes = { workspace = true }
compact_str = { workspace = true, features = ["rkyv"] }
indexmap = { workspace = true, features = ["rayon"] }
usfm_markers = { workspace = true }
num-format = "0.4.4"
pyo3 = { workspace = true, optional = true }
quick-xml = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
ureq = { workspace = true }

rkyv.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
env_logger = "0.11"

[features]
default = []
python = ["dep:pyo3"]

