#!/usr/bin/env python3
# -\*- coding: utf-8 -\*-
# SPDX-FileCopyrightText: © 2023 Robert Hunt <Freely.Given.org+BOS@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# EuropeanToEnglish.py
#
# Module handling OpenBibleData Language functions
#
# Copyright (C) 2023-2025 Robert Hunt
# Author: Robert Hunt <Freely.Given.org+BOS@gmail.com>
# License: See gpl-3.0.txt
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
Module handling European language (German and Latin) functions.

translateGerman( html:str ) -> str
    Do basic word-for-word translation from Luther's German Bible to English.
translateLatin( html:str ) -> str
    Do basic word-for-word translation from Latin Vulgate Bible to English.
briefDemo() -> None
fullDemo() -> None
main calls fullDemo()


CHANGELOG:
    2025-03-20 Moved into BOS from OBD (OpenBibleData)
"""
import BibleOrgSys.BibleOrgSysGlobals as BibleOrgSysGlobals
from BibleOrgSys.BibleOrgSysGlobals import fnPrint, vPrint, dPrint


LAST_MODIFIED_DATE = '2025-04-15' # by RJH
SHORT_PROGRAM_NAME = "EuropeanToEnglish"
PROGRAM_NAME = "OpenBibleData Language Handling functions"
PROGRAM_VERSION = '0.96'
PROGRAM_NAME_VERSION = f'{SHORT_PROGRAM_NAME} v{PROGRAM_VERSION}'

DEBUGGING_THIS_MODULE = False


GERMAN_WORD_MAP = (
    ('Aber ','But '),(' aber ',' but '),(' aber,',' but,'),(' abermal:',' again:'),
        ('Ach,','Oh,'), ('Achseln ','armpits '), ('achtzehntausend','eighteen_thousand'),
        ('Adler','eagle(s)'),
        (' alle ',' all '),(' alle,',' all,'), (' allein ',' alone '),(' allein.',' alone.'),
                (' allem ',' everything '),(' allem,',' everything,'), (' allen ',' all '),
                ('Aller ','All '),(' aller ',' all '), (' alles ',' all/everything '),(' alles,',' all/everything,'),
            ('allmächtige','almighty'),
            (' alsbald',' soon'), ('Also ','So '), (' als ',' as '),
            ('Altar ','altar '), (' alten ',' old '),(' alt ',' old '),(' alt,',' old,'),
        (' an ',' at '), (' anbeten',' worship'),
            (' andere ',' other '), (' andern ',' change '), (' andermal',' another_time'),
            ('Anfang','beginning'), ('anfingest','started'),
            ('Angesicht','face'),
            (' ansagen',' announce/declare'), ('ansiehest','look_at'),
            ('Antlitz','face'),
                ('Antwortet','Answer'),('Antwort','answer'), ('antworten','answer'), ('antworteten','replied'),('antwortete','replied'),
        ('Am ','At_the '),(' am ',' in/at/on_the '),
        (' arbeitet',' works'), ('Arche ','ark '), ('Arm,','arm,'), ('Arztes ','doctor '),
        ('Asche ','ash '), (' aß ',' ate '),
        (' außen ',' outside '),
            ('Auch ','Also '),(' auch ',' also '),(' auch,',' also,'),(' auch.',' also.'),
            (' auf ',' on/in/to '),(' auf,',' on/in/to,'),(' auf.',' on/in/to.'),(' auf?',' on/in/to?'),(' auf!',' on/in/to!'),(' auf;',' on/in/to;'),(' auf<',' on/in/to<'),(' auf)',' on/in/to)'), ('aufhören','stop/cease'), (' aufs ',' onto '),
            ('Augen ','eyes '),
            ('Aus ','Out_of '),(' aus ',' out_of '),(' aus,',' out,'),(' aus.',' out.'),
                ('ausgerottet','eradicated'),
                ('ausländische','foreign'),
                ('ausreuten','exploit'),
    # With umlaut
    (' äße,',' eat,'),
        ('Ägypten','Egypt'),
        ('Ältesten','elders'), ('Älteste','elder'),
        ('ärgerte','annoyed'),('ärgert','annoys'), ('Armen','poor'),
        ('aufrichtet','erects/straightens'),
    (' bald ',' soon '),
            ('Bär ','bear '), ('Barmherzigkeit','compassion'),
            (' bat,',' asked,'),
            (' bauen',' build'), ('baueten','built'), ('Bäumen','trees'),
        ('bedecken','cover'), ('bedürfen','need'),
            (' befahl',' commanded/ordered'), ('Befehl','command'),
            (' begab ',' gifted '), (' begehren',' desire'),(' begehrete',' desired'), (' begraben ',' buried '),(' begruben ',' buried '),
            (' behalten',' keep'), ('behütet','protected'),
            (' bei ',' at '),
                (' beide ',' both '),(' beide,',' both,'),(' beiden ',' both '),
                (' beißet',' bites'),
            ('bekannt','known'),
                ('bekehretet','converted'),
                ('bekleidet','clothed'),
            ('belagerte','besieged'),
            ('Benjamin','Benyamin'),
            (' beraubt',' robbed'),
                (' bereitete',' prepared'),(' bereite ',' prepare '),
                ('Berge Sinai','Mt. Sinai'), ('Berge ','mountains/hills '),('Berg ','mountain/hill '),
                (' bersten',' burst/crack/break'),
            (' besser ',' better '), ('Besten','best'), ('Bestreiter','contestant/opponent'),
            (' betaget',' old'),
                (' beten',' pray'),(' betet ',' prays '),(' betete ',' prayed '),
            (' bewahret',' preserved/kept/retained'),
                (' bewegen',' move_around'),
        (' bin ',' am '),(' bin,',' am,'), (' binden',' bind'), (' bis ',' until '), (' bist ',' are '),(' bist.',' are.'),
        ('Bleibe ','Stay '),(' bleib ',' stayed '),(' bleibe ',' stay '),(' bleiben ',' remain '),(' bleibest',' stay/remain'),
            ('Blicken','a_look/glance'), (' blieb ',' stayed '), # vowels swapped!
                ('Blitzes','lightning'),
            ('Blöken','bleat'), (' bloß',' just'),
            ('blühen','bloom'), ('Blut','blood'),
        ('Bogen','bow'),
            ('Bösen','evil/evil_people'),('Böse ','evil/evil_person '),(' böse ',' evil '),(' bösen ',' evil '),(' böser ',' more_evil '),('Böses ','evil '),
            ('Boten ','messenger '),
        (' brachten',' brought'),(' brachte',' brought'),
            (' bringen',' bring'),(' bringet',' bring'),
            ('Brots','bread'),('Brot ','bread '),
            ('Brüder','brothers'),('Bruder','brother'),
                ('brüllen','roar'),
        ('Buchs','book'),('Buch','book'), ('Burg','castle'), ('Buße ','repentance '),
        ('Bürgern','citizens'),
    ('Chor,','choir,'),
        ('Christus','Christ'),
    ('Da ','So '),(' da ',' there '),(' da,',' there,'),
            ('Daher ','Therefore '), (' dahergehen',' go_along'), (' dahin',' gone'),
            (' damit ',' with_it/so_that '),
            ('Danach ','Thereafter/Then '),(' danach ',' after/thereafter/then '), (' danken',' thank'),('Danket','Thank'),(' danket',' thanks'),
            (' darauf ',' on_it '), (' darin ',' in_it '), ('Darum','Therefore'), (' darum ',' therefore '), #('>darum ','>therefore '),
            ('Das ','The '),(' das ',' the '), ('daselbst','there'),
            ('Daß ','That '),(' daß ',' that '),(' daß,',' that,'),
            ('Davids','David\'s'), (' davon',' of_that'),
            ('Dazu ','In_addition '),(' dazu ',' in_addition '),
        ('Dein ','Your '),(' dein ',' your '),(' dein;',' your;'), ('Deine ','Your '),(' deine ',' your '),(' deinem',' your'),(' deinen',' yours'),(' deiner',' yours'),(' deines',' yours'),
            (' dem ',' to_him '),(' dem,',' to_him,'),
            ('Den ','The '),(' den ',' the '), ('Denen','Those'),(' denen',' those'), ('Denn ','Because '),(' denn ',' because '), ('Dennoch','Nonetheless'),('dennoch','nonetheless'), (' denselben ',' the_same '),
            ('Der ','The '),(' der ',' the/of_the '), (' derer',' those/of_those'), ('Derhalben','Therefore'),
            (' des ',' the '),
            ('Deutung','interpretation'),
        (' dich ',' you/yourself '),(' dich,',' you/yourself,'),(' dich.',' you/yourself.'),(' dich?',' you/yourself?'),(' dich;',' you/yourself;'),
            ('Die ','The '),(' die ',' the '),(' die,',' that,'),
                (' dieneten',' served'), ('Dienst','service'),
                ('Dies ','This/These '),(' dies ',' this/these '),
                    ('Diese ','This/These '),(' diese ',' this/these '),(' diese:',' this/these:'), (' diesem ',' this_one '), (' dieselbe ',' the_same '), (' diesen ',' this '),
                    ('dieselbigen','the_same'),
            ('Dinge ','things '),
            (' dir ',' you/to_you '),(' dir,',' to_you,'),(' dir.',' to_you.'),(' dir;',' to_you;'),(' dir!',' to_you!'), ('Dirne ','prostitute '),
        (' doch ',' though/but '),
        ('Drachen','dragons'),('Drache','dragon'),
                (' dräuet',' threatens'), (' draußen',' outside'), (' drauf',' on_it'),
            ('dreißig','thirty'),(' dreien',' three'),(' drei',' three'),
            (' drinnen ',' inside '),
                (' dritte ',' third '),
        ('Du ','You(sg) '),(' du ',' you(sg) '),(' du,',' you(sg),'),(' du.',' you(sg).'),
            ('Dunkel ','darkness '),
            (' durch ',' through '),
    ('Ecken ','corners '),
        ('ewiglich','forever'),
        (' ehe ',' before '), (' ehernen ',' brazen '), ('Ehre ','honour '),('Ehren','honour'),
        (' eifere',' zealous'), (' eifriger',' more_eager'),
            (' eilend ',' rushing '),(' eilete ',' rushed '),(' eileten ',' rushed '),
            ('Ein ','A '),(' ein ',' a '),(' eine ',' one '),(' einem ',' one '),(' einem,',' one,'),(' einem:',' one:'),(' einen ',' a '),(' einen,',' a,'),(' einer ',' one '),(' einer,',' one,'),(' eines ',' one '),
                ('einnahmen','have_as_income'), ('eingeborenen','native_born'),
                (' eins ',' like '),
        ('Elend ','misery/poverty/distress '),('Elenden','wretched'),
        (' empfahen',' received'),
        ('Ende ','end '),('Ende,','end,'),('Ende.','end.'),('Ende?','end?'),('Ende!','end!'),('Ende;','end;'), ('Engel','angel'), ('entfallen','omitted'),
        ('Er ','He '),(' er ',' he '),(' er,',' he,'),(' er!',' he!'),(' er:',' he:'),
            ('Erbe ','heritage '), ('Erbteil ','inheritance '),
            ('Erden','earth'),('Erde','earth'), ('erdichten','to_invent'),
            ('Ergreife','Seize'), (' ergrimmete ',' enraged '),
            (' erhält',' receives'),
                ('Erhebet','Raise'),
                (' erhöhen',' increase/enhance'), (' erhöre',' hear'),
                (' erhub ',' rise '),
            (' erkannte',' recognised'), (' erkennest',' recognise/see/realise'),
            (' erlöset',' redeemed'),
            (' erlösete',' redeemed'),
            ('Errette ','Save/Rescue '),(' errette ',' save/rescue '),(' errettete',' saved/rescued'),
            (' erschien',' appeared'), (' erschrak',' frightened'), (' ersterben',' die'), ('Erstlinge','first-fruits'),
            (' erste ',' first '),(' ersten ',' first '),
            (' erwählet',' chosen'), (' erwürget',' strangled'),
            (' erzählten',' told'),
        ('Es ','It '),(' es ',' it '),('(es ','(it '),(' es,',' it,'),(' es.',' it.'),(' es:',' it:'),(' es;',' it;'),(' es!',' it!'),
            ('Esel ','donkey '),
                (' essen',' eat'),(' essest',' eat'),(' esse',' eat'),
        (' etliche ',' several '),
            (' etwa ',' approximately '),
        (' euch',' you'),
            (' euer ',' your '),
            (' euren ',' yours '),(' eurer ',' yours '),(' eure ',' your '),
        ('Evangeliums','gospel'),
        (' ewig ',' forever '),(' ewige ',' eternal '),(' ewiges',' eternal'),
    (' fahen ',' drive '),(' fahre ',' drive '),(' fahren',' drive/ride/run'),
            (' fallen ',' fall/drop '),('fällen','fell'),('Fällt','Falls'), (' falsche ',' false '),
            (' fanden ',' found '),(' fand ',' found '),
            (' fassen ',' grasp/take/touch '), (' fast ',' nearly '),(' faste ',' fast '),
        (' fehlet ',' mistake '),
            ('Feigen','figs'), ('Feinde ','enemies '),('Feinden ','enemies '),
            ('Felde ','field '),('Felde,','field,'),
            (' ferne ',' distant '),(' ferne.',' distant.'),(' ferne;',' distant;'),
            ('Feste ','festivals '),
            ('Feuer','fire'),
        (' fiel ',' fell '),(' fielen ',' fell '),
            (' findet ',' finds '), (' fing ',' caught '), ('Finger ','finger '), ('Finsternis','darkness'),(' finster ',' dark '),
            ('Fische','fish'),
        ('Fleisch','flesh'), (' flohen ',' fled '),
        ('Folget ','Follow/obey '),(' folgen ',' follow/obey '),(' folgeten ',' followed '),(' folgt ',' follows '),(' folgte ',' followed '),
            (' fordern',' demand'),
        (' fragte ',' asked '),
            ('Fremdling','stranger'),
                ('Freude','joy/pleasure/delight'), (' freue ',' am_happy '),(' freuet',' is_happy'), ('Freunde','friends'), ('freundlich','friendly'), ('Frevels','wickedness'),
            (' fröhlich',' cheerful'), ('Frommen','pious'),
            ('Früchte','fruit'), (' freuen',' be_happy'),('Freuet','Pleased'), (' frühe ',' early '),
        (' fuhren',' lead'),(' führen',' lead'),(' führest',' lead'),(' führeten',' led'),
            (' fünf ',' five '),
            (' für ',' for '),(' für.',' for.'), ('Fürchte ','Fear '),(' fürchte ',' fear '),('fürchten','fear'), ('führete','led'), ('Fürsten ','prince(s) '),
            ('Fuß','foot'), ('Füßen','feet'),('Füße ','feet '),
    (' gab ',' gave '),(' gab,',' gave,'),(' gaben ',' gave '),(' gäbe',' give'),
            ('Gajus','Gaius'),
            (' ganz ',' all '),(' ganze ',' whole/all '),(' ganzen ',' entire '),
            (' gar ',' even '),
            ('Gassen','alleys/lanes'),
        ('Gebeine','bones'), (' geben ',' give '),(' geben,',' give,'),(' geben.',' give.'),(' geben?',' give?'),(' gebe ',' give '), (' gebeten',' requested'), ('Gebet','prayer'),
                ('Gebirge ','mountains '), ('Gebiß ','denture '),
                ('Gebote ','commandments '), (' geboten ',' offered '),
                (' gebracht ',' brought '),
            (' gedachte',' thought'),
                ('Gedenke','Remember'),('gedenken','commemorate'),('gedenkt','remembered'),
                (' gedienet',' served'),
            ('gefangen','caught'),
                (' gefiel',' liked'),
                (' geführet',' guided'),
            (' gegeben',' given'), ('gegründet','founded'),
            (' gehe ',' go '),(' gehen',' go'),(' gehest',' go'), ('Gehet ','Go '),(' gehet ',' goes '),
                ('gehorchte','obeyed'),('gehorsam','obedient/submissive'),
            ('Geist','spirit'),
            ('gekehret','swept'),
            ('gelangen','reach'),
                ('Geld ','money '),
                ('Geleit','escort'),
                ('geliebet','loved'),
            ('Gemächern','chambers'), (' gemacht',' made'),
                ('Gemeinden','communities'),
            (' gen ',' to/toward '), # Archaic -- now 'richtung'
                (' geneiget',' inclined'),
                (' genommen',' taken'),
                (' genugsam',' enough'),(' genug',' enough'),
            (' geopfert',' sacrificed'),
            (' geraubt',' stolen'),
                ('Gerechten ','righteous_ones '), ('Gerechtigkeit','justice'), (' geredet',' talked'),
                (' gering ',' small/little '),
                (' gerne ',' gladly '),
            (' gesagt',' said'), (' gesandt',' sent'),
                ('geschah','happened'),
                    ('geschehen','happen'),
                    ('Geschichten','stories'), ('geschrieben','written'),
                    (' geschlagen',' beaten'), # Leading space is vital
                    ('geschweiget','let_alone'),
                        ('geschwinde','quickly'),
                        ('geschworen','sworn'),
                ('Gesegnet','Blessed'), (' gesehen ',' seen '), ('Gesellen','fellows'), ('Gesetz','law'),(' gesetz',' set'),
                ('gestellet','provided'),
                ('Gesicht ','vision/face '),
                (' gesund ',' healed '),
            (' getan ',' did '),(' getan,',' did,'),
                ('Getreide ','grain '),
                    ('getroffen','met'), ('getrost,','confidently,'), ('getröstet','comforted'),
            (' gewann ',' won '), (' gewesen ',' been '),
        ('Gib ','Give '),(' gib ',' give '), (' gibst',' give'),
            (' ging ',' went '),(' gingen ',' went '),
        ('Glänzen','shine'), ('Glauben','faith'), ('glauben','believe'),
            ('gleich','even'),
            ('Glied','member/element'),
        ('Gnade ','grace '),('gnädig','gracious'),
        (' goß ',' poured/cast '),
            ('GOttlosen','godless'), ('Gottes','God’s'),('Göttern','gods'),('Götter','gods'),('GOtt','God'),
        ('Grabe ','grave '),
            ('Grenzen ','boundaries '),
            (' groß ',' large '), (' große ',' large '),(' großen',' large'),(' großer',' large'),(' großes',' large'), ('größer','bigger'),
        (' gut ',' good '),(' gute ',' good '),(' guter ',' good '),('Gutes','goodness/good_(person)'), ('Güte ','goodness '),('Güte,','goodness,'),('Güte!','goodness!'), ('Güter ','goods '),('Gütern ','goods '),
    (' hab ',' have '), ('Habe ','goods '), (' habe ',' have '),(' habe,',' have,'),(' habe.',' have.'),(' habe;',' have;'), ('haben','have'), ('Habt','Have'),(' habt',' have'),
            (' hadere ',' quarrel '), ('Haderern','quarrelers'),
            (' half ',' helped '), (' halben ',' half '),
                ('Halleluya','Halleluyah'),
                ('halsstarrig','stubborn'),
                (' halten',' hold'),(' halte ',' hold '), (' hält ',' holds '),(' hältst',' hold'),
            ('Hand ','hand '),('Hand,','hand,'), ('Händen','hands'),('Hände','hands'), (' hangen ',' hang/stuck '),
            ('Häupter ','heads '),
            (' harre ',' wait '),(' harret',' wait'), ('Harfe ','harp '),('Harfen','harps'),
            (' hasse ',' hate '),(' hasse,',' hate,'), (' hassen',' hate'), (' hast ',' have '),(' hast,',' have,'),
            (' hat ',' has '),(' hat,',' has,'),(' hat.',' has.'),(' hat?',' has?'),(' hat:',' has:'), (' hatte ',' had '),(' hatte,',' had,'),(' hatte.',' had.'),(' hatte;',' had;'), (' hätte ',' would_have '), (' hatten',' had'),
            (' häufig ',' frequently '),
                ('Haupt','head'),
                ('Hauses','houses'),('Hause','house'),('Haus','house'), ('Häuser','houses'),
                ('Haut ','skin '),
        (' hebräisch ',' hebrew '),
            ('Heere ','armies '),('Heer ','army '),
            ('Heiden','heathens'),
                ('Heiligen','saints'), ('Heiligkeit','holiness'), ('heiligte','sanctified'), ('Heiligtum','sanctuary'),  (' heiligen',' holy'),(' heilig',' holy'), ('Heils','salvation'),('Heil ','salvation '),
                (' heimlich',' secretly'),
                (' heißt',' is_called'),
            ('heller ','brighter '),
            (' herab ',' down '), (' heraus',' out_of_here'),
                ('herkommen','come_here'),
                (' helfen',' help'),
                # ('HErrn','LORD'), # This will already have \\nd around HErr so would do nothing here
                ('Herrschaft','rule/reign'), ('HErr','LORD'),('Herrn','Lord'),('Herr','Lord'),
                (' hervor',' out'),
                ('herunterreißen','tear_down'),
                ('Herzen','hearts'),('Herzlich','Heartfelt'),('Herz','heart'),
            ('Heulen','cry'),(' heule,',' cry,'),
        ('Hie ','Here '),(' hie ',' here '), (' hieß ',' was_called '),(' hieß.',' was_called.'), (' hießet ',' is_called '),
            (' hilf ',' help/assist '),('Hilfe ','help '),(' hilfst',' help'),(' hilft',' help'),
            ('Himmel','heaven'),
            (' hin ',' there '),(' hin,',' there,'),
                (' hinab ',' down '), (' hinauf ',' up '),(' hinauf,',' up,'),(' hinauf.',' up.'), (' hinaufzog',' pulled_up'), (' hinausführen',' lead_out'),
                (' hinnen ',' inside '),
                (' hinkte ',' limped '),
                (' hinter ',' behind '),
                (' hinüber ',' over '),
                (' hinzog',' dragged_on'),
            ('Hirten','shepherds'),
        (' hoch ',' high '),
            (' hoffe ',' hope '),(' hoffen',' hope'),
            (' holdselig',' lovely'), (' holen',' fetch'), ('Hölle','hell'), ('Holz','wood'),
            (' hören',' hear/listen'), (' höreten',' heard'),(' hörete',' heard'), ('Höret','Hear'),(' höret',' hear'), ('Höre','Listen'),(' höre',' listen'),
                ('Hörnern','horns'),
                ('Hort ','refuge/stronghold '),
        (' hülfe ',' help '), ('Hügel ','hill '), (' hundert ',' hundred '), ('Hütte ','hut/cabin '),
    ('Ich ','I '),('Ich,','I,'),(' ich ',' I '),(' ich,',' I,'),(' ich.',' I.'),
        (' ihm ',' him '),(' ihm,',' him,'),(' ihm.',' him.'),(' ihm:',' him:'),(' ihm!',' him!'),
            (' ihn ',' him/it '),(' ihn,',' him/it,'),(' ihn.',' him/it.'),(' ihn?',' him/it?'),(' ihn!',' him/it!'),(' ihn:',' him/it:'),(' ihn;',' him/it;'),(' ihn<',' him/it<'), (' ihnen ',' to_them '),(' ihnen,',' to_them,'),(' ihnen.',' to_them.'),(' ihnen:',' to_them:'),
            ('Ihr ','You '),(' ihr ',' you/their/her '), (' ihre ',' their/her '), (' ihrem ',' their '), (' ihren ',' your '), (' ihrer ',' of_their/her '),
        ('Im ','In_the '),(' im ',' in_the '), (' immer ',' always '), (' immerdar',' forever'),
        (' innen ',' inside '), (' ins ',' into_the '),
        ('Irrgeist ','crazy '),
        ('Ist ','Is '),(' ist ',' is '),(' ist,',' is,'),(' ist.',' is.'),(' ist:',' is:'),(' ist;',' is;'),
    ('Jahr ','year '), ('Jahre','years'),
            ('jämmerlich','miserable/pitiful'),
            ('Jawohl','Yes_indeed'),
        (' je ',' each/ever '),
            (' jedermann ',' anyone '),
            (' jeglichen',' anyone '),
            (' jemand ',' someone '), (' jemen ',' that '),
            (' jenem ',' that_one '), (' jenseit ',' beyond '),
            ('JEsus','Yesus'),
        ('Jüngern','disciples'),('Jünger','disciple'), ('Jünglinge','young_men'),
    ('Kälte','coldness'),
        (' kam ',' came '),(' kam,',' came,'), (' kamen ',' came '),
            (' kann ',' can '),('Kannst','Can'),(' kannst',' can'),
            (' kaufen ',' buy '),
        (' kehrete ',' returned '),
            (' kein ',' no/not '),(' keine ',' no '), (' keinen ',' none '),(' keines ',' none '),
            (' kennet ',' knows '),
            ('Ketten','chains'),
        ('Kinder ','children '),('Kinder,','children,'),('Kinder.','children.'), ('Kindeskind','child\'s_child'),
        ('Kleid ','garment '),('Kleider ','clothes '), (' kleinen',' small'),
            ('Kluge ','wise/clever_(person) '),
        ('Knabe ','boy/lad '),
            ('Knechten','servants'),('Knechte','servant(s)'),('Knecht','servant/farmhand'),
        ('Komm ','Come '),(' komme ',' come '),(' kommen ',' coming '),(' kommen,',' coming,'),(' kommen.',' come.'), (' kommest ',' come '),(' kommt ',' comes '),
            (' könnest ',' can '),(' konnten ',' could '),
            ('Kost ','cost '),
        ('Könige','kings/king'),('Königin','queen'),('Königs','kings'),('König','king'), (' königliche ',' royal '),
        ('Kraft ','strength/power '),('Kräften ','strength/power '), (' krank',' sick'),('Kranken ','sick_ones '), ('Krone ','crown '),
        ('kundtätest','announce'),
    ('Lade ','box/chest '),
            (' lag.',' lay.'), ('Lager ','camp '), (' lagert ',' stores/camps '),(' lagerten',' stored'),
            ('Länder','countries/lands'),('Lande','land'), (' lang ',' long '),(' lang,',' long,'),(' lange ',' long '),(' länger ',' longer '),
            (' lasse ',' let '),(' lassen',' let'), (' lässest',' let'), (' lasset ',' let '),
            ('Laß ','Let '),(' laß ',' let '),(' läßt ',' lets '),
            ('Lauterkeit','purity/integrity'),
        ('lebendige','living/lively'),('Lebens','life'),('Leben ','life '),(' leben',' life'), (' lebet',' lives'),(' lebte',' lived'),
            ('leer,','empty,'),
            (' legen ',' place '),(' legen,',' place,'), (' legte ',' laid '), (' legt,',' lays,'),
            ('Lehre','Teaching'),(' lehret ',' teaches '),
            ('Leib ','body '),('Leibe ','body '), ('Leid ','sorrow '),
            (' lesen ',' read '),
            ('leuchten','shine/glow'), ('Leute ','people '),('Leuten','people'),
        ('Licht','light'),('licht','light'),
            (' lieb ',' kind/sweet/dear '), ('Lieben ','loved_(one) '),(' lieben',' love'),(' lieber ',' dear '), ('Liebe ','love '), (' liebhabe ',' love '), (' lieblich ',' lovely/delightful '),
                ('Lied','song'),
                (' ließ ',' left/let '),(' ließen ',' leave/let '), (' liegen',' lie/lay'), (' lieten',' lead'),
                (' lief ',' ran '),
            ('Lippen ','lips '),
            ('List ','cunning '),
        ('Lobe ','Praise '),(' loben',' praise'),#(' loben,',' praise,'),(' loben.',' praise.'),
                ('lobsinget','sing_praises'), ('Lobet ','Praise '),(' lobet',' praises'),
            (' löse',' resolve'),
            ('Löwen','lions'),
        (' lud ',' invited '),
        ('Lügen ','lie(s) '),
    (' mache ',' make '),(' machen ',' make '),(' machen,',' make,'),(' machen.',' make.'), (' machet ',' makes '), (' machten',' make'),(' machte ',' made '),(' machte,',' made,'), ('Macht','Power'),(' macht ',' power '),(' macht,',' power,'),(' macht.',' power.'),(' macht;',' power;'),
            (' mag ',' like '),
            ('Man ','They '), ('Mangel','shortage'), ('Männer','men'), ('Manne ','man '), ('Mann ','man '),('Mann.','man.'),
            ('Märkte ','marketplaces '),
            ('Maul ','mouth '),('Maul.','mouth.'),('Mäuler','mouths'), ('Mauern','walls'),('Mauer','wall'),
        (' mecum ',' with_me '),
            ('Meeres','sea'),('Meer ','sea '),('Meer,','sea,'),('Meer.','sea.'),('Meer?','sea?'),
            (' mehr ',' more '),
            (' meiner',' mine'),('Meine ','My '),(' meinem ',' my '),(' meinen ',' my '),(' meiner ',' my '),(' meines ',' my '),(' meine ',' my '),('Mein ','My '),(' mein ',' my '),(' mein,',' my,'),
            ('Mensch ','person '),('Menschen','people'),
            ('mercator','merchant'), (' merkte',' noticed'),
        ('Mich ','Me/Myself '),(' mich ',' me '),(' mich,',' me,'),(' mich.',' me.'),(' mich?',' me?'),(' mich!',' me!'),(' mich:',' me:'),(' mich;',' me;'),
            (' mir ',' to_me '),(' mir,',' to_me,'),(' mir.',' to_me.'),(' mir:',' to_me:'),(' mir;',' to_me;'),
            ('Missetat ','misdeed/iniquity '),
            ('Mit ','With '),(' mit ',' with '), ('miteinander','together'),
        ('Mond ','moon '),('Monden','moons'),
            ('. Morgan','. Morning'),('Morgan','morning'), ('Morgens','morning'),
        ('Mögen','May'),(' mögest',' may'), ('mörderischen','murderous'),
        ('Mühe,','effort/trouble,'),
            ('Munde ','mouth '),('Mund ','mouth '),
            (' müssen ',' must '),(' müsse ',' must '),
            (' muß ',' must '), ('müßige','idle'),
            ('Mutter ','mother '),
    (' nachdem ',' after '),('Nach ','After '),(' nach ',' after '),(' nach,',' after,'),(' nach.',' after.'),(' nach!',' after!'), ('Nacht ','night '), 
                ('Nächsten','neighbour'),
            ('Naemi ','Naomi '),
            (' nahmen ',' took '),(' nahm ',' took '),
            ('Namen','name(s)'), (' nämlich ',' namely '), # ('Namen,','name(s),'),('Namen!','name(s)!'),
            (' nannte',' called'),
            ('Nase ','nose '),('Nase.','nose.'),
        (' neben ',' next_to '),
            (' nehmen',' take'),
            ('Nest ','nest '),
            ('Netze ','net '),('Netz,','net,'),
            (' neun ',' nine '),
        (' nichts',' nothing'),(' nicht ',' not '),(' nicht,',' not,'),(' nicht.',' not.'),(' nicht!',' not!'),(' nicht;',' not;'),
            ('niedergeschlagen','dejected/depressed'), (' niemand',' no_one'),
            (' nimmermehr',' nevermore'),
        ('Noch ','Still '),(' noch ',' still '),
        ('Nöten','needs'), (' nötigte ',' forced '),
        ('Nun ','Now '),('Nun,','Now,'),(' nun ',' now '),(' nun,',' now,'),
            (' nur ',' only '),
    (' ob ',' if/whether '), (' oben ',' above '), ('Oberste ','top '),
        ('Ochsen ','oxen '),
        (' oder ',' or '),
        ('offenbaren','reveal'), (' offene ',' open '),
        (' ohne ',' without '), (' ohngefähr ',' about '), ('Ohren ','ears '),
        (' opferten',' sacrificed'),(' opfert',' sacrifices'),
        ('Ort ','place '),('Ort,','place,'),('Ort.','place.'), ('Orten','places'),
    (' öde ',' dull '), ('Oder ','Or '),
        ('Öl ','oil '),
    ('Palästen','palaces'),
        ('Pfeile','arrows'), ('Pferd','horse'), ('Pfosten','post(s)'), ('pflügen','plough'),
        ('Philister','Philistines'),
        (' plagen ',' plague '),
            ('plündern','plunder'),
        (' predigen ',' preaching '), (' predigte ',' preached '),
            (' preisen',' praise'),(' preiset',' praises'),(' preise',' praise'), ('Priester','priest(s)'),
    ('Quelle','source/spring'),
    ('Ränke','schemes'),
            ('Rat ','advice '),('Rat.','advice.'),('Rats ','council '),
            ('Raub','plunder'),(' rauben',' rob'), ('Raum ','space '),
        (' rechne ',' reckon '), ('Rechten','law/right'),('Rechte','law/right'),('Recht','law/right'),(' rechten',' right'),(' rechte',' right'), (' recht',' right'),
            ('Rede ','speech '),(' reden ',' talk '), (' redeten',' talked'),(' redete ',' talked '), (' redet ',' talks '),
            ('regierete','ruled'),
            ('Reich ','kingdom '), ('reinigte','cleaned'), (' reisen ',' travel '),(' reisete ',' travelled '),
        (' richtet',' directed'), (' richtig',' correct'),
            (' rief ',' shouted '),(' riefen ',' shouted '),
            ('Rindern ','cattle '),('Rinder ','bovine '),
            ('Ritze ','crack/crevice '),
        (' roter ',' red '),
        (' ruchbar',' noticeable'),
            (' rufe ',' call/cry/shout '),(' rufen',' call/cry/shout'),
            ('Ruhe ','rest '), (' rühmen',' boast/praise'),(' rühme ',' boast/praise '),
            (' rüsten ',' equip '),
    ('Saal ','room '),
            ('Sache ','matter '),
            ('Sage ','Say_to '),(' sagen',' say'),(' sagte',' said'),(' sagt',' says'),(' sage ',' said '),
            (' sah ',' saw '),(' sah,',' saw,'),(' sahen',' saw'),
            ('Saiten','strings'),
            ('Salz','salt'),
            ('Samen ','seed/seeds '),('Samen.','seed/seeds.'), (' sammelten ',' collected '),(' sammeln',' collect'),
            ('Sand','sand'), (' sandten',' sent'),(' sandte ',' sent '),
            (' saß ',' sat '),
        ('Schafe ','sheep '),('Schafe,','sheep,'), ('schaffe','create/make'), ('schaffte','managed'), ('Schalkheit','mischievousness'), ('schämte','ashamed'), ('Schande ','shame '),
                    ('Schmach','disgrace'),('schmähen','revile'),
                (' schied ',' separated '), ('Schild ','shield/sign '), ('Schiff','ship'),
                ('schlachten','slaughter'), ('Schlachtopfer','sacrifice'), (' schlafen',' sleep'), (' schlag ',' hit/beat '),(' schlage ',' hit/beat '), (' schlugen ',' hit/beat '),(' schlug ',' hit/beat '),
                    ('Schloß ','castle '), ('Schlüssel ','key '),
                (' schon ',' already '), (' schön ',' beautiful '),(' schöne ',' beautiful '),(' schönen ',' beautiful '),
                (' schrie ',' shouted/screamed '),(' schrieen ',' shouted/screamed '), ('Schriftgelehrten','scribes'), ('Schrift','writing'),
                (' schuf ',' created '), ('Schultern','shoulder'), ('schüttelt','shakes'),
                ('schwebete ','floated '), ('schweigen','keep_quiet'),('schweige','keep_quiet'), ('schwelgen','revel/delight'), ('Schwert ','sword '),
        ('sechshundert','six-hundred'), ('sechzehn','sixteen'),
            ('SeeLE','soul'), # What's with the CAPS???
            ('Segen','blessing'), (' segnet',' blesses'),
            (' sehe ',' see '), (' sehen',' see'), (' sehr ',' very '),
            ('Sei ','Be '),(' sei ',' be '), ('Seid ','Are '),(' seid ',' are '),(' seid.',' are.'),(' seid;',' are;'), (' seien ',' be '),(' seiest ',' be '),  (' seihe',' see'),
                ('Sein ','His '),(' sein ',' his '),(' sein,',' be,'),(' sein.',' be.'),(' sein;',' be;'), (' seine ',' his '),(' seinem ',' his '),(' seinen ',' his '),(' seiner ',' his '),(' seines ',' his '), (' seit ',' since '), ('Seite ','side '),
            (' selbst',' himself/itself'), (' selig ',' blessed '),
            (' sende ',' send '),(' senden ',' send '),(' sendet ',' send '),
            (' setzen',' set/put/place'),(' setzet ',' sets '),(' setzten ',' put/set/sat '), (' setzte ',' sat '),
        (' sich ',' itself/yourself/themselves '),(' sich,',' itself/yourself/themselves,'),(' sich.',' itself/yourself/themselves.'),(' sich;',' itself/yourself/themselves;'),(' sich<',' itself/yourself/themselves<'), (' sicher ',' secure '),
            ('Sie ','They/She '),(' sie ',' they/she/them '),(' sie,',' they/she/them,'),(' sie.',' they/she/them.'),(' sie?',' they/she/them?'),(' sie!',' they/she/them!'),(' sie:',' they/she/them:'),(' sie;',' they/she/them;'), ('Sieben ','Seven '),(' sieben ',' seven '), ('Siehe,','See,'),(' siehe,',' look,'),(' siehest',' see'),(' siehet',' see'), (' sienem ',' his '),
            ('Sind ','Are '),(' sind ',' are '),(' sind,',' are,'),(' sind.',' are.'),(' sind?',' are?'),(' sind!',' are!'),(' sind:',' are:'),(' sind;',' are;'),
            ('Sitte ','custom '),(' sitzen',' sit'),(' sitzet',' sits'),(' sitzt',' sits'),
        ('Sohn','son'),('Söhne','sons'),
            (' solch ',' such '),(' solche ',' such '),(' solches ',' such '),
                (' soll ',' should '), ('Sollen ','Should '),(' sollen ',' should '), (' sollst ',' should '),(' sollt ',' should '),(' sollte ',' should '),
            ('sondern','rather'), ('Sonne','sun'), ('Sonst ','Otherwise '),
        (' spannen',' tension/stretch'),(' spannete ',' tense '),
            ('Speere ','spear(s) '), ('Speise ','food '), ('Speisopfer','grain-offering'),
            (' spiritern ',' spirits '),
            (' spottet ',' scoffs '),
            (' sprachen',' said'),(' sprach ',' spoke '),(' sprach:',' spoke:'),
                ('sprechet','speaker'),
                (' sprich:',' say:'),(' spricht ',' says '),
        ('Städte ','cities '),('Städten ','cities '), ('Stadt ','city '),('Stadt,','city,'),('Stadt.','city.'),('Stadt!','city!'),
                ('Stamms ','tribe '),('Stamm ','tribe '),
                (' starb ',' died '),(' starb.',' died.'),
                    ('Stärke','strength'),('Starken ','strong_ones '),(' stärker ',' stronger '),('stärkete','strengthened'),
                ('Statt','instead_of'),
                ('Staube ','dust '),('Staub ','dust '),
            (' stehen',' stand'),(' stehet',' stands'),
                (' steigen',' climb'), ('Steinen','stones'),
                (' sterben',' die'),(' sterbe',' die'),
                (' stets ',' always '),
            (' stille ',' silence '), ('Stimme ','voice '),
            ('stolzen','proud'),
            ('Straßen','roads'),('Straße','road'), ('Straußen','ostriches'),
                ('Streit','battle'),('streite ','argue/battle '),('streiten','argue/battle'), ('stritten','argued/fought'),('stritt ','argued/fought '),
            ('Stücke','pieces'),('Stück ','piece '), (' stund ',' stood '), (' stürze ',' falls '),
        (' suchen ',' search_for '), (' suchten ',' were_looking_for '),
            ('Sünde ','sin '),('Sünde,','sin,'), ('Sünden','sins'), ('Sünder ','sinners '),('Sündern','sinners'), (' sündigen ',' sin '), (' sühnen ',' atone '),
    ('Tag ','day '),('Tag.','day.'),('Tagen','days'),('Tage','days'), (' täglich',' daily'),
            (' tat ',' did '),(' tat,',' did,'),(' taten ',' did '),
        ('Teil ','part/portion '),('Teile','parts'),(' teile ',' share '),
            ('Tempel','temple'),
        ('Tiefe','depth'), ('Tier ','animal '),('Tiere ','animals '), (' timor ',' fear '), ('Tisch ','table '),('Tisch;','table;'),
        (' toben',' rage'),
            ('Tochter','daughter'),
            ('Tode ','deaths '),
            ('Tore ','gates/goals '),('Tor ','goal/doorway '),('Tor.','goal/doorway.'),
            (' tot ',' dead '),(' toter ',' dead '),
            (' töte ',' kill '),(' töte?',' kill?'), (' töten,',' kill,'),(' töten.',' kill.'),(' tötest ',' kill '),
        (' tragen',' bear/carry'),(' trägst',' bear/carry'),
                (' trank',' drank'),
                (' trat ',' stepped '),
                (' traue ',' trust '),(' traue,',' trust,'),
            (' treuer ',' loyal '),
            (' trieb ',' drove '), (' trinken',' drink'),
            (' trocken',' dry'), (' tröstet ',' comforts '),
            (' trug ',' wore '), (' trunken',' drink'),
        ('Tu ','Do/Act '),(' tu ',' do/act '),(' tu.',' do/act.'), (' tue ',' do/act '),
            (' tun ',' do/put '),(' tun,',' do/put,'),
            ('Tür ','door '),('Türen','doors'),
            (' tut ',' does '),(' tut,',' does,'),(' tut.',' does.'),(' tut?',' does?'),(' tut!',' does!'),(' tut:',' does:'),(' tut;',' does;'),
    ('Übel','evil'),(' übel ',' bad/evil '),(' übel?',' bad/evil?'),
                (' über ',' above '),
                    ('überantwortest','hand_over'),
                    ('überbleiben','remain'),('überblieben','left-over'),
                    (' übergeben',' hand-over/transfer'),
                    (' überlasse',' leave'),
            (' übrig ',' left-over '),(' übrigen',' remaining'),
        ('Ufer','riverbank'),
        (' um ',' around/by/for '), (' umgehen',' evade/avoid'), (' umher ',' around/about '),
        ('Und ','And '),(' und ',' and '), # ('>und ','>and '),
            ('Ungewitter','storm'), ('ungläubige','unbelieving'), ('Unglück','accident/misfortune/disaster'),
            (' unrechte',' wrong'),(' unrecht',' wrong'), (' unrein',' unclean'),
            (' uns ',' us/to_us/ourselves '),(' uns,',' us/to_us/ourselves,'),(' uns.',' us/to_us/ourselves.'),(' uns?',' us/to_us/ourselves?'),(' uns!',' us/to_us/ourselves!'),(' uns:',' us/to_us/ourselves:'),(' uns;',' us/to_us/ourselves;'),
                ('unschuldig','innocent'),
                ('Unsere ','Our '),('Unser ','Our '),(' unser ',' our '),(' unsere ',' our '), (' unsern',' ours'), (' unsers',' ours'),
            (' unten',' below'),
                (' unter ',' under '),
                    ('untereinander','each_other'),
                    ('untergehen','go_under/sink'),
                    ('untertänig','submissive/subservient'),
            ('unversehens','unexpectedly'),
        ('Ursache','cause'),
    ('Vaterland','fatherland/homeland'), ('Vater ','father '),('Vaters','father'),('Väter ','fathers '),
        ('verbanne','banish'), ('verbrannt','burnt'), ('Verborgene','hidden_things/ones'),
                ('verdienet','deserves'),
                    ('verdorren','wither'),
                    ('verdrießt','annoyed'),
                ('verfolgen','pursue/follow'), ('verführen','seduce'),
                ('vergeben','forgive'), ('vergessen','forget'),
                    ('vergilt','repaid'),
                    ('vergoß','shed/spill'),
                    ('vergreifen','violate'),
                ('verkehret','wrong'),
                    ('Verkündiget','Announce'),('verkündigten','announced'),('verkündigte','announced'),('verkündigen','announce'),('verkündiget','announced'),
                ('verlassen','leave'),('verlässest','leave'),('verläßt','leaves'),
                    ('verließen','left'), ('verloren','lost'),
                ('versammelt','gathered'),
                    ('verschlagen','devious'), ('verschlungen','devoured'), ('verschmähet','spurned/despised'),
                    ('versöhnen','reconcile'),
                    ('verständiges','sensible/understanding'),('verständig','sensible/understanding'),('verstehen','understand'),('verstehe','understand'), ('Verstummen','Be_silent'), ('verstund','understood'),
                    ('versuchte','tried'),
                ('vertilgen','destroy/eradicate'),
                ('verwesen','decay/rot'),
                ('verzeichnet','recorded'),
            ('Vetter','cousin'),
        (' viel ',' many '),(' viele ',' many '),(' vieler',' many'),
            (' vier ',' four '), (' viereckig',' square'), (' vierte ',' fourth '), (' vierzig ',' forty '),
        ('Volk','people'),('Völkern','peoples'),('Völker','peoples'), (' voll ',' full/whole '),
            (' vom ',' from_the '),
            ('Von ','From '),(' von ',' from '),
            (' vor ',' before/in_front_of '),
                (' vorhin ',' earlier '),
                (' vorigen ',' previous '),
                ('vorsetzen','offer/serve_up'), ('vorsichtig','cautious'),
                ('vorüberging','passed_by'),
                ('vorzusingen','to_sing_to'),
    ('Waage','scale'),
            ('Wachs','wax'),
            ('Waffen','weapons'),
            (' währet ',' lasts '), ('Wahrheit','truth'), ('wahrhaftig','truthfully'),
            (' walten ',' prevail '),
            ('Wand ','wall '),('Wände','walls'), (' wandele',' walk'), (' wandeln',' walk'), (' wandelte',' walked'), (' wandte ',' turned '),
            (' war ',' was '),(' war,',' was,'),(' war.',' was.'),
                (' ward ',' was '), # Is 'ward' a mispelling?
                (' wäre ',' were '),(' waren',' were'),(' wären ',' would_be '),
                (' warf ',' threw '),
                (' warten',' wait'),
                ('Warum ','Why '),(' warum ',' why '),
            ('Was ','What '),(' was ',' what/which '), ('Wässerlein','little_water'),('Wasser','water'),
        ('Weg ','path '),
                ('Wege ','ways '),('Wege,','ways,'),('Wege.','ways.'),('Wege?','ways?'),('Wege;','ways;'),
                    ('Wegen','ways'), # NOTE: Can also mean 'Because_of' at sentence start
                (' wegführen',' lead_away'),
            ('Wehe ','Woe '),
            ('Weibern','women'),('Weiber','women'),('Weib ','woman '),('Weib,','woman,'),('Weib.','woman.'),
                (' weil ',' because '),
                ('Wein ','wine '), (' weinet?',' cries?'),(' weinete ',' cried '),
                (' weises',' wise'), ('Weisheit','wise_(people)'),
                (' weiß ',' know '),(' weiße ',' white '),(' weißt ',' know '),
                (' weit ',' far '), (' weiter ',' further '),
                ('Weizen','wheat'),
            ('Welche ','Which '),('welche ','which '),('welcher ','which '),(' welches ',' which '),(' welchem ',' which_one '), ('Welt','world'),
            ('Wende ','Turn '), ('Wendige ','few '), ('Wenn ','When '),(' wenn ',' when '),
            ('Wer ','Who '),(' wer ',' who '),
                (' werden',' become'),(' werde',' become'),
                (' werfen',' throw'),
                ('Werken','works'),('Werke','work'),('Werk','work'),
                (' wert ',' value/worth '),
            ('Wesen','beings'),
        (' wider ',' against '),
            ('Wie ','How '),(' wie ',' as/like '), (' wiedergeben',' restore/give_back'),(' wiederkam',' came_back'),(' wiederum',' again/in_turn'),(' wieder',' again'), # ('>wie ','>as '),
            (' willen',' will'),
            ('Wind ','wind '), ('Winkel ','corner '),
            (' wird ',' becomes '),(' wird,',' becomes,'),(' wird.',' becomes.'),
                (' wirst ',' will '), ('Wir ','We '),(' wir ',' we/us '),(' wir.',' we/us.'),
            (' wissen ',' realize '),('Wisset ','Know '),(' wisset ',' know '),
        ('Wo ','Where '),(' wo ',' where '),
            ('Woche ','week '),
            ('Wohl ','Probably '),(' wohl ',' probably '), (' wohltun',' do_good'), (' wohnen',' reside'),(' wohnete',' lived'),(' wohnet',' lives'),
            (' wollen',' want'),(' wollest',' want'),
                ('Wolken ','clouds '),
                ('Wollt ','Want '),(' wollten',' wanted'),(' wollte',' wanted'),
            (' womit',' with_what'),
            (' worden',' been'), ('Worten','words'),('Worte ','words '),('Worts ','word '),('Wort ','word '),
        (' wund.',' sore.'), ('Wunder','miracle/wonder'),
            (' wurden ',' became '), ('Wurzel ','root '),
            ('Wüste','desert'), (' wüst ',' wild '),(' wüste ',' wasteland/desert '),
            (' wußte ',' knew '),(' wußten',' knew'),
    ('zählete ','counted '), ('zähme ','tame '), ('Zähne ','teeth '), ('Zaun ','fence '),
        ('Zebaoth','Tsevaot_(of_armies)'),
        (' zehn ',' ten '),('Zehnten','tithe/tenth'),
            ('Zeichen ','sign '), ('Zeit ','time '),('Zeit,','time,'),('Zeit.','time.'),('Zeit!','time!'),('Zeit:','time:'),('Zeit;','time;'),
            ('zerbrechen','break'),
            (' zeugen',' witness/testify'),(' zeuget',' witness/testify'), ('Zeugnisse','testimonials'), ('Zeugnis','transcript'),
        (' zog ',' pulled '),(' zogen ',' pulled '), ('Zorn','anger'),('zornig','angry'),
        (' zu ',' to '),(' zu,',' to,'),
            ('zufrieden','satisfied'),
            ('Zuletzt ','Finally '),
            (' zum ',' for_the '),
            ('Zunge','tongue'),
            (' zur ',' to '),
            ('zusammen','together'), ('zuschanden','to_shame'),
        ('Zwanzig','Twenty'),(' zwanzig',' twenty'),
            (' zween ',' two '),(' zwei ',' two '),(' zweimal',' twice'),
            (' zwiefach ',' doubly '), (' zwischen ',' between '),
            (' zwölften ',' twelfth '),
    )
GermanWords, EnglishWords = [], []
for wordMapEntry in GERMAN_WORD_MAP:
    assert len(wordMapEntry) == 2, f"{wordMapEntry}"
    GermanWord,EnglishWord = wordMapEntry
    assert isinstance( GermanWord, str ) and (len(GermanWord)>=2 or GermanWord in ('J','j')), f"{GermanWord=}"
    assert GermanWord != EnglishWord, f"Attempting to replace identical German word: {GermanWord=}"
    assert GermanWord not in GermanWords, f"duplicate GermanWord: {GermanWord=} ({EnglishWord=})"
    if GermanWord.startswith(' ') or EnglishWord.startswith(' '): assert GermanWord.startswith(' '), f"Mismatched leading space: {GermanWord=} {EnglishWord=}"
    if GermanWord.endswith(' ') or EnglishWord.endswith(' '): assert GermanWord.endswith(' '), f"Mismatched trailing space: {GermanWord=} {EnglishWord=}"
    assert GermanWord not in EnglishWord, f"Recursive substitution of '{GermanWord}' into '{EnglishWord}'"
    assert '  ' not in GermanWord
    GermanWords.append( GermanWord)
    if GermanWord.startswith(' '): assert EnglishWord.startswith(' '), f"Mismatched leading space:  {GermanWord=} {EnglishWord=}"
    if GermanWord.endswith(' '): assert EnglishWord.endswith(' '), f"Mismatched trailing space: {GermanWord=} {EnglishWord=}"
    if EnglishWord[-1] in ' ,.:;':
        assert GermanWord[-1] == EnglishWord[-1], f"Mismatched trailing character: {GermanWord=} {EnglishWord=}"
    if GermanWord[-1] in ' ,.:;':
        assert EnglishWord[-1] == GermanWord[-1], f"Mismatched trailing character: {GermanWord=} {EnglishWord=}"
    assert '  ' not in EnglishWord
    if ' ' not in GermanWord.strip():
        assert ' ' not in EnglishWord.strip(), f"Space in middle of {EnglishWord=}" # No space in middle
    EnglishWords.append( EnglishWord )
del GermanWords, EnglishWords

def translateGerman( htmlStr:str ) -> str:
    """
    Do basic word-for-word translation from Luther's German Bible to English.

    Text in htmlStr parameter can be inside a span,
        e.g., '<span class="Wycl_verseTextChunk">ech man in his seruice, and in the offring,</span>'
    """
    fnPrint( DEBUGGING_THIS_MODULE, f"translateGerman( ({len(htmlStr)}) )" )

    # if html.startswith( 'und '): # Handle common exception that can't be expressed in the word table
    #     html = f'and {html[4:]}'
    htmlStr = htmlStr.replace( '»', '‘' ).replace( '«', '’' )
    for GermanWord,EnglishWord in GERMAN_WORD_MAP:
        htmlStr = htmlStr.replace( GermanWord, EnglishWord )
        if GermanWord[0] == ' ':
            if htmlStr.startswith( GermanWord[1:] ):
                htmlStr = htmlStr.replace( GermanWord[1:], EnglishWord[1:], 1 )
            htmlStr = htmlStr.replace( f'>{GermanWord[1:]}', f'>{EnglishWord[1:]}' )

    return ( htmlStr.replace('j','y').replace('J','Y') # Try to write it like it might have sounded
                # But then need to fix up some regular English words
                .replace('deyect','deject').replace('yoy','joy').replace('yust','just')
            )
# end of EuropeanToEnglish.translateGerman


LATIN_WORD_MAP = (
    # Two words
    ('et ait','and he_said'),
    # Single Latin words
    (' a ',' from '),
        ('Ab ','From '),(' ab ',' away '), (' abierunt',' they_are_gone'), ('Abiit ','He_went_away '),(' abiit ',' he_is_gone '), (' arbores ',' trees '),
        (' absque ',' without '),
        (' ac ',' and '), ('Accedens','Approaching'),
        ('Ad ','To '),(' ad ',' to '), (' adverso ',' on_the_contrary '),(' adversum',' against'),(' adversus',' against'),
        ('Afferte','Bring_it'),
        (' agmina ',' trains '),
        ('Ait ','He_said '),(' ait ',' he_said '),(' ait:',' he_said:'),
        (' alia ',' other '), (' aliæ ',' in_another '), (' aliud',' something_else'), (' alius',' another'),
            (' alleviabit',' will_relieve'),
            (' altera',' the_other'),(' alterum',' the_other'), ('altitudinem','height'),
        ('amaræ','bitter'),
            ('ambæ','both'), ('ambulabant','they_were_walking'),
            (' amico',' friend'),
            ('Amovit','Removed'),(' amovit',' removed'),
        ('ancillam','maidservant'),
            (' angelum',' a_messenger/angel'),
            (' anima ',' the_soul '),(' animæ',' soul'),(' animam',' the_soul'),
            ('Anno ','In_the_year '),(' anno ',' in_the_year '),(' annos ',' years '),
                (' annum ',' a_year '), ('annuntiata','announced'),('annuntiatio','announcement'),('annuntiate','announce'),
            (' ante ',' before '),(' antequam ',' before '),
        (' appellavit ',' he_called '),
        (' aqua',' water'),
        (' arca ',' box '),(' arcam ',' the_box '),(' arcem ',' the_castle '),(' argento ',' with_silver '),
        ('ascendit','went_up'),
            ('aspiciam','I_will_look'), ('aspiciet','will_look'), ('asportaverunt','they_took_away'),
        ('At ','But '),
            (' atque',' and_yet'),
        (' audiet',' will_hear'), ('Audita ','Hearing '),('Audi,','Listen,'),(' audi ',' listen '),(' audio',' I_hear'), (' audientes ',' hearing '), (' audivi',' I_heard'),
            (' aurem ',' ear '),(' aures ',' ears '),(' auribus ',' in_the_ears '),(' auris ',' ear '), (' auro',' with_gold'),
            (' aut ',' or '),(' aut,',' or,'), (' autem',' however'),
        ('avertas','turned_away'),
    (' ædificare',' to_build'),
        (' æreus',' brazen/golden'),
        (' æternam',' eternal'), (' æternum',' eternal'),
    ('Beatus','Blessed'),
            ('benedicentes','blessing'), ('Benedictus ','Blessed '),
            (' bestia',' beast/animal'),
        (' bibere ',' to_drink '), (' bibes ',' you_will_drink '),
            (' bis ',' twice '),
        (' bona ',' good '), (' bonum',' good'), (' boves ',' cattle '), # ('>bona ','>good '),
    ('cæli','heavens'),('cælo','the_sky'),('Cælum','The_sky'),('cælum','the_sky'), (' calida ',' hot '),
            ('Canticum','A_song'),
            (' capta ',' captured '),
            (' castro',' the_castle'),
            (' causam',' cause'),
        ('ceciderunt','they_fell'),(' cecidit',' fell'),(' cecidi',' I_fell'),
            ('Centum ','Hundred '),(' centum ',' hundred '),
            ('Cepit ','He_took '),
            ('Cerno ','I_see '), (' cervicis ',' of_the_neck '),
        ('Chananæum','Canaanites'),
        (' circuitu',' around'), ('Circumdederunt','They_circled'), ('circumferentur','are_carried_around'),
            (' civitas ',' city '),(' civitate ',' city '),('civitatem','the_city'),('civitatis','of_the_city'),
        ('clamabo','I_will_cry'), ('clamantis','crying'), ('clamavi','I_cried'),
                ('claudus','lame'), ('claustra','barriers'),
            ('clypeus','shield'),
        ('cœpit','he_began'),
        ('cognovit','he_knew'),
            ('Collisi ','I_collided '), ('collocavit','placed'),
            (' comedat',' to_eat'), ('commotionem','excitement'),
            ('confidere','to_trust'), ('confitebitur','will_confess'), ('confregit','he_broke'),
                ('congregabit','will_gather'), ('conspectu','in_sight'),
                ('consurgam','I_will_get_up'),('consurgit','he_gets_up'),
                ('continetur','is_contained'), (' contra ',' on_the_contrary '), ('contradictione','contradiction'),
            (' coram ',' before '),
                (' cor ',' heart '),(' corde',' heart'),(' cordis',' of_the_heart'),
                (' corpus',' body'), (' corrigit ',' corrects '), ('corroboravit','he_strengthened'),
        ('creavit ','created '), ('credere ','to_believe '), ('credite','believe_me'),('credit','he_believes'),
            ('Christi','of_Christ'),
        (' cubitos',' elbows'),
            (' cui ',' to_whom '),
            ('Cum ','Since '),(' cum ',' when/with '), ('Cumque ','And_when '),
            ('curaretur','would_be_taken_care_of'),
            (' custodis',' you_keep'),(' custodi',' keep'),
    ('Da ','Give '),
            (' daret ',' would_give '),(' daretur',' would_be_given'),
        ('dæmonia','demons'),
        (' de ',' about '),
            (' decem ',' ten '),(' decem,',' ten,'),
            (' dedit',' he_gave'), ('Deditque','And_he_gave'),
            (' deferens ',' bearing '),
            ('Dei','of_God'),
            ('Deo','to_God'),
            (' derelinquam',' I_will_leave'),
            (' deserto ',' desert '),(' desertum',' desert'), (' destruxit',' destroyed'),
            ('Deum','God'),('Deus','God'),
            (' dextera',' right_hand'),(' dextris',' on_the_right'),
        (' dic ',' say '),('dicat','let_him_say'),
                (' dicebat',' he_said'), (' dicebant',' they_said'), (' dicemus',' we_will_say'), (' dicens',' saying'), ('dicentes','saying'), (' dices:',' you_say:'),
                ('Dicit:','He_says:'),(' dicit ',' he_says '),(' dicit:',' he_says:'), ('dicitur','it_is_said'),
                (' dico ',' I_mean/say '),(' dico,',' I_mean/say,'),(' dico?',' I_mean/say?'),(' dico:',' I_mean/say:'),(' dico)',' I_mean/say)'),
                ('dicunt','they_say'),
            (' diebus ',' days '), (' diei ',' of_the_day '), ('Dies ','The_day '),(' dies',' days'),(' die ',' day '),
            ('dilexit','he_loved'),
            ('dimittere','to_release'),('dimittuntur','they_are_released'),
            ('Dirige ','Direct '),
            ('discedas','leave'), ('discipulis','students'),('discipuli','students'),
            ('divisit','divided'),
            ('dixerunt','they_said'),
                (' dixi ',' I_said '),(' dixi,',' I_said,'), ('Dixitque','And_he_said'), (' dixit',' he_said'),
        (' docebo ',' I_will_teach '), (' docet',' teaches'),
        (' dolor ',' pain '), (' dolus',' trick/hoax/guile'),
        ('domestici','domestic'),
            ('Domine ','Master '),('Domine,','Master,'),('Domine.','Master.'),('Domine?','Master?'),('Domine:','Master:'),('Domine;','Master;'), ('Domini ','Master '),('Domini,','Master,'),('Domini.','Master.'),('domini ','master '),('Domino','Master'),('Dominum','the_Master'),('Dominus','Master'),
            (' domo ',' at_home '), (' domos',' houses'), (' domum',' home'), (' domus',' home'),
        ('donec ','until '),
        ('dormit','he_sleeps'),
        (' ducam ',' I_will_lead '), (' duce ',' as_a_leader '),
                ('Ducenta','Two_hundred'),(' ducenta',' two_hundred'), (' ducentes',' leading'),
                    (' ducere ',' to_lead '),
                (' ductus ',' leadership '),
            (' dum ',' while '),
            (' duo ',' two '),(' duodecim ',' twelve '),(' duodecimo ',' the_twelfth '),
            (' duræ ',' hard '),
    (' ea ',' them '),(' eam ',' her '),(' eam.',' her.'),
            (' earum',' of_them'),
        ('Ecce ','Behold '),(' ecce ',' behold '), ('ecclesiis','assemblies/churches'),
        ('Educet','He_will_bring'),
        ('Effunde','Pour_it_out'),(' effusi',' poured_out'),
        ('Ego ','I '),(' ego ',' I '),(' ego.',' I.'),
        (' ei ',' to_him '),(' ei,',' to_him,'),(' ei.',' to_him.'),(' ei:',' to_him:'),(' ei;',' to_him;'),(' ei?',' to_him?'),(' eis ',' to_them '),(' eis,',' to_them,'),(' eis.',' to_them.'),(' eis?',' to_them?'),(' eis:',' to_them:'),(' eis;',' to_them;'),(' eis)',' to_them)'),
        (' ejus',' his'),
        (' enim',' because'),
        (' eo ',' by_him '),(' eo,',' by_him,'),(' eo.',' by_him.'),(' eo?',' by_him?'),(' eo:',' by_him:'),(' eo;',' by_him;'), (' eorum',' their'), (' eos',' them'),
        (' epulis ',' food '),
        (' eradicatæ',' eradicated'), (' eram ',' I_was '), (' erant ',' they_were '),(' erant.',' they_were.'), (' erat',' was'),
            (' ergo ',' therefore '),(' ergo,',' therefore,'),
            (' erit ',' will_be '),(' erit.',' will_be.'),
            (' ero.',' I_will_be.'), (' errore ',' by_mistake '),
            (' eruit ',' out '),
        (' es ',' you_are '),(' es,',' you_are,'),(' es.',' you_are.'),(' es?',' you_are?'),(' es:',' you_are:'),(' es;',' you_are;'), (' essem ',' I_would_be '), (' essent ',' they_would_be '), (' esset ',' was '), (' est ',' it_is '),(' est,',' it_is,'),(' est.',' it_is.'),(' est:',' it_is:'),
        ('Et ','And '),(' et ',' and '), (' etiam ',' also '), # ('>et ','>and '),
        (' eum ',' him '),(' eum,',' him,'),(' eum.',' him.'),(' eum?',' him?'),(' eum:',' him:'),
        ('Evangelii','of_the_Gospels'),('Evangelium','the_Gospel'),
        ('Ex ','From '),(' ex ',' from '),
            ('Exaudi','Hear_me'),('exaudi','listen'),
            (' exercitus',' army'),
            (' exordio ',' beginning '),
            (' expecto',' I_wait'), ('exspectabo','I_will_wait'),
    (' fac ',' do '),
            (' facere ',' to_do '),
            (' faciam ',' I_will_do '),(' faciat ',' let_him_do '),
            (' facie ',' face '), (' faciebat ',' he_was_doing '), (' faciem ',' face '), (' faciens',' making'), (' facies',' faces'), (' facite ',' do_it '),(' facit ',' he_does '),
            (' facta ',' facts '), ('Factum ','Done '),(' factum ',' done '),(' factus ',' became '), ('facultatibus','resources'),
        (' fecerit',' he_did'),('Fecitque ','And_he_did '),(' fecit ',' he_did '),
            ('Fenestras','The_windows'),(' fenestras',' the_windows'),
            (' feri ',' wild '),
            ('Festinaverunt','They_hurried'),(' festinanter',' hurriedly'),
        ('Fiat ','Let_it_happen '),
            (' fidei',' of_faith'),(' fidelis ',' faithful '),(' fidem ',' faith '),
            (' fieri ',' to_be_done '), (' fiet ',' will_be_done '),
            (' filia',' daughter'),('Filiæ','Daughters'),(' filiæ',' daughters'), (' filiis',' to_the_children'), ('Filii','Children'),(' filii',' children'), ('filiorum','of_children'),('Filium','Son'),(' filium ',' son '),('Filius','Son'),(' filius',' son'),('Fili,','Son,'),(' fili ',' son '),
            (' finem',' the_end'),(' finibus ',' borders '),
            ('firmamentum','a_support'),
        ('flammæ','flames'),
            ('fluctus ','wave '), ('fluminis','of_the_river'),
        (' fortes',' strong'),
        ('fratrem','brother'),('fratres','brothers'),('fratrum','brothers'),
            (' frigus',' cold'),
            ('frumentum','corn'),
        (' fuerint',' they_have_been'),(' fuerit',' has_been'),
            (' fugabunt ',' they_will_flee '), (' fugiet ',' he_will_flee '), (' fugissent ',' they_would_have_fled '), (' fugit ',' he_fled '),
            ('Fuit ','It_was '),(' fuit ',' it_was '),(' fuit;',' it_was;'),
            (' funiculi ',' rope '),
            (' fur ',' a_thief '), (' fürchten',' fear'),
    (' gelu.',' frost.'),
            ('generationem','generation'), (' genere',' in_general'),(' gentes',' people/nations'), (' gentibus ',' nations '),
        (' gloria ',' glory '),(' gloriam',' glory'),
        ('graduum','steps'),
            ('greges','flocks'),('gregum','flock'),
        (' gustata ',' tasted '),
    (' habeant ',' let_them_have '), (' habeat ',' have '),(' habebat ',' had '),(' habes,',' you_have,'), ('habitabat','he_lived'),('habitabo','I_will_live'),('habitare','to_live'),('habitat','he_lives'),
        ('Hæc ','This '),(' hæc ',' these_things '),(' hæc,',' these_things,'), ('hæreditabunt','they_will_inherit'),('hæreditatem','inheritance'),
        ('hebraice','hebrew'), ('Hethæum','Hittites'),  ('Hevæum','Hivites'),
        ('Hi ','They '), (' hic ',' this '),(' hic.',' this.'),
        ('Hoc ','This '),(' hoc ',' this '),
            (' hominis',' of_man'),(' hominum',' of_men'), (' homo ',' human '),
            (' hordeaceos',' barley'), (' horum',' of_these'),
        (' hujuscemodi ',' of_this_kind '), (' humeros ',' shoulders '), (' hunc ',' this_one '),
    ('Ibi ','There '),(' ibi ',' there '),
        ('Id ','That '),
        ('Ierunt ','They_went '),
        ('Igitur ','Therefore '), (' ignem ',' fire '),(' ignis ',' fire '), ('ignorantiis','ignorance'),
        (' illa ',' that '),(' illa:',' that:'),
                (' ille ',' he '),
                (' illi ',' them '),(' illi,',' them,'),(' illi.',' them.'),(' illi?',' them?'),(' illi:',' them:'),(' illi;',' them;'),
                    (' illic ',' there '),
                    (' illis ',' to_them '),(' illis,',' to_them,'),(' illis.',' to_them.'),(' illis?',' to_them?'),(' illis:',' to_them:'),(' illis;',' to_them;'),
                (' illos ',' those '),
                (' illuc ',' there/to_that_place '), (' illud ',' it/this/that '), (' illum ',' him '),(' illum,',' him,'),
        ('imperium','government'), ('imputavit','imputed/transferred_over'),
        (' inclina ',' incline '),
            (' inde ',' hence '), (' inducam',' I_will_introduce'),
            (' infirmum',' weak'), (' inferno',' hell'),
            ('ingredieris','you_will_enter'),
            ('inimica','hostile'),('inimici','enemies'),('inimicorum','of_enemies'),('inimicos','enemies'),
                ('iniquitatem','iniquity'),
                ('Initium ','The_beginning '),(' initium ',' the_beginning '),
            (' inquit',' he_said'),
            ('Insidiatus','Intrigued'), ('Insuper','In_addition'),
            ('intellexi','I_understood'), (' inter ',' between '), ('interfecti','killed'), ('intermissum','a_break'),
                ('intrabat','he_was_entering'),('intravit','he_entered'), ('introëas','enter'),
            ('invenies','you_will_find'), ('inveniens','finding'), ('invocabant','they_invoked'),('invocant','they_invoke'),
        (' ipsa ',' herself '),('Ipse ','Exactly_that '),(' ipse ',' exactly_that/himself '),('(ipse ','(exactly_that/himself '),('Ipsi ','Himself '),(' ipsi ',' themselves '),(' ipsos ',' themselves '),
        (' ira ',' anger/rage '), ('iracundiam','anger'),
            (' irrue ',' rushed '),
        ('Israël','Israel'),
            (' istam,',' that_one,'),(' iste ',' this '),(' istum',' that'),
        (' ita ',' so/thus '),(' itaque',' therefore'), (' iterum',' again'),
    ('Jordanem','Yordan'),
        (' judicet',' he_will_judge'), (' judicis',' judgements'), (' judicium',' judgement'),
            (' jugiter',' regularly'),
            ('Juravit ','He_swore/promised '),(' juravit',' he_swore/promised'),
            (' justæ ',' just '),(' justa.',' just.'),('Justi ','Just '),(' justi.',' just.'), (' justis,',' just,'), ('justitia ','justice '),('justitiam','justice'),
            (' juxta ',' next_to '),
    (' lacum',' lake'), ('læteris','of_leather'),
            (' laganum',' pancake'),
            (' lapide ',' stone '),
            ('latitudinis','width'),
            ('laudantes','praising'),
        (' legem ',' the_law '),(' legum ',' laws '),
            (' lehrete ',' taught '),
            (' lex ',' the_law '),(' lex.',' the_law.'),
        (' liberis ',' freedom '), ('Licet ','It’s_possible '),
        (' loco ',' instead '), (' locum ',' place '), (' locutique',' and_spoke'),(' locutus ',' spoke '),
            (' longe ',' far_away '), (' longious ',' farther '), (' longitudinis',' length'),
        (' luco ',' in_the_forest '), (' lucem',' the_light'),
            (' lux ',' light '),(' lux,',' light,'), (' luxi',' shine'),
    (' maculæ',' spots'),
            (' magnus',' big'),
            (' mala ',' evil '),(' malum ',' evil '),(' malum,',' evil,'),
            ('Mane ','Stay '), ('manibus','hands'), (' manu ',' by_hand '),(' manum ',' hand '), (' manus ',' hands '),
            (' mare ',' the_sea '),(' mari ',' of_the_sea '),(' maris',' of_the_sea'),
            (' matrem',' mother'),
        (' mea ',' my '),(' mea,',' my,'),(' mea.',' my.'),(' mea?',' my?'),(' mea:',' my:'),(' mea;',' my;'), (' meæ ',' my '),(' meæ,',' my,'),(' meæ.',' my.'),(' meæ:',' my:'),(' meæ;',' my;'),(' meæ?',' my?'), (' meam ',' mine '),(' meam,',' mine,'),(' meam.',' mine.'),(' meam?',' mine?'),(' meam:',' mine:'),(' meam;',' mine;'), (' meas ',' mine '),(' meas,',' mine,'),(' meas.',' mine.'),(' meas?',' mine?'),
            (' mecum ',' with_me '),(' mecum:',' with_me:'),
            (' medio ',' in_the_middle '),
            (' mei ',' my/mine '),(' mei,',' my/mine,'),(' mei.',' my/mine.'),(' meis ',' mine '),(' meis,',' mine,'),
            (' membra ',' members '), (' memor ',' memory '),
            (' Men ',' members '), (' mensa ',' the_table '), (' mense ',' a_month '),(' mense,',' a_month,'), (' mensis,',' month,'),(' mensis.',' month.'),
            (' meo ',' mine '),(' meo,',' mine,'),(' meo:',' mine:'),(' meos',' mine'),
            (' mercede ',' reward '),
            (' meum ',' mine '),(' meum,',' mine,'),(' meum.',' mine.'),(' meum:',' mine:'), (' meus ',' mine '),(' meus,',' mine,'),(' meus.',' mine.'),
        (' mihi ',' to_me '),(' mihi,',' to_me,'),(' mihi.',' to_me.'),(' mihi?',' to_me?'),(' mihi:',' to_me:'),(' mihi;',' to_me;'),
            (' militum',' soldiers'), (' mille ',' a_thousand '),(' millia ',' thousands '),('millibus','thousands'),
            ('ministrabant','served'),
            ('mirabilia','wonderful_things'),
            ('misericordiam','mercy'),('misericordia','mercy'), (' misi ',' I_sent '),(' misit ',' he_sent '),
            (' mitto ',' I_send '),
        (' monte ',' mountain '),(' montes',' mountains'),
            ('moreretur','would_die'),
                ('morientur','they_will_die'),
                (' morte ',' death '),(' mortuæ',' dead'),(' mortuus',' dead'),
            ('Moysi','of_Moses'),
        (' multæ ',' many '), (' multas',' fines'),(' multa ',' fine '),
            (' mundum',' the_world'), (' munera',' gifts'),
            (' muros',' the_walls'),
    ('Nati ','born '), (' navi:',' by_ship:'),
        ('Ne ','Don\'t '),(' ne ',' not '), (' nec ',' but_not '), ('Neque ','Neither '),(' neque ',' nor '),
        (' nimis',' too_much'),
            (' nisi ',' except '),
        (' nobis ',' us '),(' nobis,',' us,'),(' nobis.',' us.'),(' nobis?',' us?'),(' nobis:',' us:'),(' nobis;',' us;'),
            (' nocte',' at_night'),(' noctis',' of_the_night'),
            ('Nolite ','Don\'t '),(' nolite ',' don\'t '),
            (' nomen ',' name '),(' nomine ',' by_name '),(' nomini ',' to_the_name '),
            ('Non ','Not/No '),(' non ',' not/no '), ('Nonne ','Isn\'t_it '), (' nonne ',' isn\'t_it '),
            (' nos ',' we '),(' nos,',' we,'), (' noster ',' our '), (' nostri ',' our '), ('nostrorum','of_ours'), (' nostros',' ours'),
            (' novam',' new'),(' novum ',' new '),
        (' nubes ',' clouds '),
            (' nudus',' naked'),
            (' numero ',' number '), ('Numquid ','Is_it '),(' numquid ',' is_it '),
            (' nunc ',' now '),
            (' nurus ',' daughter-in-law '),
    ('oblatrent','they_should_offer'), ('obliquas','sideways'),
            ('observantes','observing'),('obsidebant','they_invested'), ('Obsecro','Please'), ('obsederunt','besieged'),
        (' occidas ',' kill '),
            (' ocreas ',' boots '),
            (' octavus',' the_eighth'),
            ('Oculi','The_eyes'),(' oculi',' eyes'), (' oculos',' the_eyes'),('Oculus','The_eye'),
        ('Odisti ','You_hate_it '),
        (' oleum ',' oil '),
        ('Omnes ','All_of_them '),(' omnes ',' everyone '), (' omni ',' all '), ('Omnia ','Everything '),(' omnia ',' everything '),(' omnia,',' everything,'), (' omnibus',' to_all'), ('Omnis ','Everyone '),(' omnis ',' everyone '), (' omnipotens',' omnipotent'),
        (' opus ',' work/need '),
        ('Oratio ','Speech/Prayer '),(' oratio ',' speech '), ('orationem','speech'), (' oravit ',' he_prayed '),
            (' orbatus',' bereaved'),
            (' oris ',' mouth '),
        (' ostiis ',' the_doors '),
    (' palatio',' palace'), (' pallium ',' cloak '),
            (' panes ',' bread '),(' panis ',' bread '),
            (' parte ',' in_part/partly '),
            (' pater ',' father '), (' patris ',' of_the_father '),(' patri ',' to_his_father '),
            (' paululum ',' a_little '),
        (' peccata ',' sins '),(' peccatis ',' sins '), ('peccatores','sinners'),('peccatorum','sinners'), ('peccatum','sin'), ('peccavi','I_have_sinned'), (' pecus',' cattle'),
            (' pede.',' on_foot.'),(' pedes',' feet'),(' pedibus',' feet'),
            (' peperit ',' gave_birth '),
            (' per ',' through '),
                (' pera ',' bag '),
                (' percussit ',' he_struck '),
                ('perductus ','conducted '),
                (' pereat ',' perish '),
                (' perierat',' had_perished'),
                (' perflata',' blown_away'),
                (' perierunt',' they_perished'),
                ('persequuntur','pursue'),
                (' pertinet',' belongs'),
                ('pervenit','arrived'),
            (' petivi ',' I_asked '),
        ('Philisthiim','Philistines'),
        ('pingues','fat'), ('pinguium','fat'),
            ('piscatores','fishermen'), (' pisces',' fish'),
        ('placabilem','appeasable'), (' planctum ',' crying '), ('Planxit ','He_cried '),
            ('plebis','of_the_people'),
        ('Pones ','Put '), (' ponit',' puts'),
            (' populi',' of_the_people'),(' populo',' to_the_people'),(' populum',' the_people'),
            ('Porro ','Further '),
                (' portabo',' I_will_carry'), (' portam ',' the_gate '),
            ('possederunt','they_possesed'), ('possessionem','possession'), ('Post ','After '),(' post ',' after '), (' posuerunt ',' they_put '),(' posuit ',' put '),
            (' potens ',' powerful '),
                (' poterant ',' they_could '), (' poteris',' you_will_be_able_to'),
                ('Potes ','You_can '), (' potestas ',' power '),
                (' potius ',' rather '),
        ('præceperat','had_ordered'),('præcepit','ordered'), ('prælium','battle'),
            ('prima ','the_first '),('prima,','the_first,'), ('primum ','first '),
                ('princeps ','prince '),('principe ','prince '), ('principio ','at_the_beginning '), ('principum','of_the_princes'),
                (' prius',' first/before'),
            (' pro ',' for '),
                ('procedens','proceeding'), ('procella ','storm '),
                ('projecta ','projected '),
                ('propheta ','a_prophet '),('prophetæ','the_prophets'),('prophetidem','the_same_prophet'),
                    ('proprie ','properly '),
                    ('Propterea ',"That's_why "),('Propter ','Because '),(' propter ',' because '),
                ('Provocaverunt','They_provoked'),
                (' proximo ',' the_next '),
        ('Psalmus','Psalm'),
        (' pueris ',' children '),
            (' pugna ',' fight '),
            (' putabunt ',' they_will_think '), (' puteum ',' a_well '),
    (' qua ',' which '),('Quæ ','Which '),('quæ ','which '),('quæque','each'),('quærere','to_seek/search_for'), (' quambis ',' with_which '),
            (' qualis ',' such_as '),
            (' quam ',' how '),
            ('Quando ','When '),(' quando ',' when '),
            (' quæres ',' you_will_seek '),(' quæret ',' he_would_seek '),
            (' quarta ',' the_fourth '),
            (' quas ',' which '),(' quasi ',' as_if '), ('quæsierit','he_asked'),
            (' quatuor',' four'),
        (' quem ',' which '),
        ('Qui ','Who '),(' qui ',' who '), # ('>qui ','>who '),
            ('Quia ','Because '),('quia ','because '),
            ('Quibus ','To_whom '),('quibus ','to_whom '),
            ('Quid ','What '),(' quid ',' what '), (' quidam ',' some '), (' quidem ',' indeed '), (' quidquam ',' anything '),
            ('quietus','quiet'),
            ('quinque','five'),
            ('Quis ','Who '),('quis ','who/any '),
        ('Quod ','That '),('quod ','that '),
            ('quomodo ','how '),
            ('Quoniam','Since'),(' quoniam',' since/because'),
            ('quoque ','too '),
            ('quos ','which '),
    (' radix ',' root '),
        ('recesserunt','they_withdrew'), (' rectas ',' correct '),
            (' regem',' the_king'), (' regis',' king'), (' regna ',' kingdoms '), (' regnavit',' reigned'),(' regni ',' of_the_kingdom '),(' regnum',' kingdom'),(' regum',' of_kings'),
            (' reliqui ',' I_left '),
            ('remittat','let_him_go'), ('remittentur','they_will_be_released'),
            ('respondens','responding'), ('respondit','answered'),
            (' retia ',' net '),
            (' reus ',' guilty '),
            (' reversus ',' returned '),
            (' rex ',' king '),(' rex.',' king.'),
        (' ripa ',' bank '),
        ('robustus','robust'),
        (' ruinæ ',' fall/ruins '), (' rursum',' again'),
    ('sacerdos','priest'),('sacerdotes','priests'),('sacerdotibus','to_the_priests'),('sacerdotis','of_the_priest'), (' sacris ',' sacred '),
            ('sæculi','of_the_world'),
            ('Salus','Health/Safety'),(' salus',' health/safety'), ('salutare','to_greet'),
                (' salva ',' save '), ('salvabit','will_save'), ('salvatorem','saviour'), ('salvavit','he_saved'), (' salvum',' safe'),
            (' sancto',' holy'),('Sanctos ','Saints '),(' sanctum',' holy'), (' sanguinis',' blood'), ('sanctificavit','sanctified'),
            (' sapientiam',' wisdom'),
        ('sæculum','forever'),
        ('sceleribus','crimes'),
        (' se ',' himself '),(' se,',' himself,'),(' se.',' himself.'),(' se?',' himself?'),(' se:',' himself:'),(' se;',' himself;'),
            (' secundo ',' secondly '),('Secundum ','After/Second '),(' secundum ',' after/second '), (' secuti ',' followed '),
            ('Sed ','But '),(' sed ',' but '),
                (' sedens ',' sitting '),(' sedero',' I_will_sit_down'),(' sedi,',' I_sat_down,'),
            (' semen ',' seed '), (' semitas ',' path '), ('sermonem','conversation'), (' semper ',' always '),
            ('senioribus','seniors'),
            (' sepelierunt',' they_buried'), (' septem ',' seven '), (' septimus ',' the_seventh '),
            (' sequens',' following'),(' sequitur',' follows'),
            (' servata ',' saved '), ('servavitque','and_kept'), (' servierunt ',' they_served '),
        ('Si ','When/But_if '),(' si ',' when/but_if '),
            ('Sic ','So '),(' sic ',' so '),(' sic,',' so,'), (' sicut ',' like '),
            (' sidera ',' stars '),
            (' sileas',' be_silent'),(' sileat',' be_silent'),
            ('similiter','likewise'),(' simul ',' at_the_same_time '),
            (' sine ',' without '),
                (' singulis ',' each '),
                (' sinu ',' pocket '),
            (' siquidem',' indeed'),
            (' sit ',' let_it_be '),(' sit,',' let_it_be,'),(' sit:',' let_it_be:'), (' situ ',' situation '),
            (' sive ',' if/or '),
        (' socrum',' mother-in-law'),
            (' solii ',' the_throne '), (' sollten',' should'),
            (' somnium',' a_dream/sleep'),
            (' sortem',' lot'),
        ('spatioso','spacious'),
            ('speravi','I_hoped'),
            ('spiritu ','in_spirit '),('spiritus','spirit'),
            ('spoliasti','you_robbed'),
        (' stabam ',' I_was_standing '), ('Stan ','Standing '), (' stare',' to_stand'), (' statim ',' immediately '),
            (' stella ',' star '), ('steterant','they_had_stood'),
            (' studia ',' studies '),
        (' sua ',' his_own '),(' sua,',' his_own,'),(' sua.',' his_own.'),(' sua?',' his_own?'),(' sua:',' his_own:'),(' sua;',' his_own;'),
                (' suæ,',' his_own,'),
                (' suam ',' his_own '),(' suam,',' his_own,'),(' suam:',' his_own:'), (' suas ',' their_own '),
            ('Sub ','Under '),(' sub ',' under '), (' subegerat ',' he_had_taken '),
            (' sui ',' self '),(' suis',' to_his_own'),
            (' sum ',' I_am '),(' sum,',' I_am,'),(' sum.',' I_am.'),
            (' sunt ',' are '),(' sunt,',' are,'),(' sunt.',' are.'),(' sunt:',' are:'),
            (' suo ',' his_own '),(' suo,',' his_own,'),(' suo.',' his_own.'),(' suo?',' his_own?'),(' suo:',' his_own:'),(' suo;',' his_own;'), (' suos',' his_own'),
            (' super ',' over '), ('supervacue','needlessly'),
            (' surdos ',' the_deaf '), ('Surrexerunt ','They_rose_up '),(' surrexit ',' got_up '),
            (' suscitet ',' raise '),
            (' suum ',' his_own '),(' suum,',' his_own,'),(' suum.',' his_own.'),
    (' tace,',' be_silent,'),
            ('tamquam','as_if'),
            ('tanquam','as_if'),(' tantum ',' only '),
            (' tauri ',' bull '),
        (' te ',' you(sg) '),(' te,',' you(sg),'),(' te.',' you(sg).'),
            ('Tectum ','The_roof '),(' tectum ',' roof '),
            (' tegebat ',' covered '),
            (' templo',' temple'),
            (' tenebris',' darkness'), (' tenet',' holds'),
            (' terga ',' back '),
                (' terra ',' earth/land '),(' terra.',' earth/land.'),(' terra:',' earth/land:'),(' terra?',' earth/land?'),(' terra;',' earth/land;'),
                    (' terræ',' of_the_earth/of_the_land'),
                    (' terram',' the_earth/the_land'),(' terra,',' earth/land,'),
            (' testimonium',' testimony'),
        (' tibi ',' to_you '),(' tibi,',' to_you,'),(' tibi.',' to_you.'),(' tibi?',' to_you?'),(' tibi:',' to_you:'),(' tibi;',' to_you;'),
            (' timeas',' fear'), ('timentes','afraid'),
        ('Tollens ','Taking_off '),(' tollens ',' removing '),
            (' tota ',' the_whole '),
        (' tradam ',' I_will_deliver '), (' tradas ',' hand_over '), (' tradidit ',' he_delivered '),
            (' trans ',' across '), ('Transierunt ','They_passed '),(' transierunt ',' they_passed '), ('Translata ','Transferred '),
            (' tribus ',' three '),
        ('Tu ','You(sg) '),('Tu,','You(sg),'),(' tu ',' you(sg) '),(' tu,',' you(sg),'),(' tu.',' you(sg).'),(' tu?',' you(sg)?'),(' tu:',' you(sg):'),(' tu;',' you(sg);'),
                (' tua ',' your '),(' tua,',' your,'),(' tua.',' your.'), (' tuam ',' your(sg) '),(' tuam,',' your(sg),'),(' tuam.',' your(sg).'),(' tuam:',' your(sg):'),(' tuam;',' your(sg);'),(' tuam?',' your(sg)?'),(' tuam!',' your(sg)!'), (' tuarum',' of_yours(pl)'), (' tuas',' yours'),
                (' tuæ ',' yours '),(' tuæ,',' yours,'),(' tuæ.',' yours.'),(' tuæ?',' yours?'),(' tuæ:',' yours:'),(' tuæ;',' yours;'),
            (' tui ',' yours(sg) '),(' tui;',' yours(sg);'), (' tuis',' yours'),
            ('tulerunt','they_took'), ('tulit ','took '),
            ('Tunc ','Then '),
            (' tuo ',' your '),(' tuo,',' your,'),(' tuo.',' your.'),(' tuo?',' your?'),(' tuo:',' your:'),(' tuo;',' your;'), (' tuorum',' yours'), (' tuos ',' yours '),
            (' turba ',' crowd '),(' turbæ',' to_the_crowd'),
            (' tuum ',' your '),(' tuum,',' your,'),(' tuum.',' your.'),(' tuum?',' your?'),(' tuum:',' your:'),(' tuum;',' your;'), (' tuus',' your'),
    ('Ubi ','Where '),(' ubi ',' where '),
        (' una,',' together,'), (' unctionis',' anointing'), (' unctus ',' anointed '),
            ('Unde:','Whence:'),(' unde ',' whence '),
            ('unigenitum','only_born'),
                (' unius',' of_one'),
                (' universam',' the_whole'),(' universus',' the_whole'),
            (' unum ',' one '),(' unum.',' one.'),(' unum,',' one,'),(' unus ',' one '),
        (' urbe ',' city '), (' urbem',' city'), (' urbs ',' city '),
        (' usque ',' until '), (' usus ',' use '),
        (' ut ',' as '), (' utroque ',' both '),
            (' uxorem',' wife'),(' uxores',' wives'),(' uxor ',' wife '),
    ('Væ ','Alas '),
        ('vanitates','vanities'),
        (' vel ',' or '),
            ('Veneruntque','And_they_came'),('venerunt','they_came'),
                (' veniat ',' let_him_come '),(' veniebat',' he_was_coming'),(' veniet ',' will_come '),(' veniret ',' would_come '), (' venisset ',' had_come '), ('Venite','Come'), ('Venit','He_came'),(' venit',' he_came'),
                (' ventis ',' the_winds '),
            (' verba ',' words '),(' verbis ',' with_words '),(' verbum ',' the_word '),
                ('veritas','the_truth'),('veritate ','with_truth '),('veritatem','the_truth'),
                ('vero ','indeed/however '),('vero,','indeed/yet,'),
            ('vescebatur','was_fed'),
                ('Vespere','In_the_evening'),
                ('vestimenta','clothes'),('vestium','clothing'),
                    (' vestra,',' your,'),('vestras','your'), ('vestrorum','of_yours'), ('vestrum','of_you'),
        (' via ',' road '),(' viam ',' road '),
            (' videbo',' I_will_see'),(' vidi ',' I_saw '),(' vidisset ',' had_seen '),(' vidit ',' he_saw '),
            (' vigesima',' the_twentieth'), (' viginti',' twenty'),
            ('Vir ','Man '),(' vir ',' man '),
                (' viri ',' men '),
                (' virga',' rod/staff'), ('Virgo ','girl/damsel '),
                (' viro ',' to_the_man '), (' virorum',' of_men'), (' viros ',' men '),(' viros:',' men:'),
                (' virum,',' husband,'), ('virtutis','of_virtue'),
            (' vis ',' you_want '), ('Visio ','Vision '),(' visionem ',' vision '),(' visione ',' vision '),
                (' visum ',' sight '),
            (' vitæ ',' of_life '), (' vitam ',' life '),(' vitam,',' life,'),
                (' vituli',' calf'),
            (' vivat',' he_lives'),
        (' vobis ',' to_you '),(' vobis,',' to_you,'),(' vobis?',' to_you?'), ('vobiscum','with_you'),
            ('vocans ','calling '),('Vocansque','And_calling'), ('vocatur ','is_called '), ('vocavit','he_called'),
                (' voce ',' voice '),(' vocem',' voice'),(' voces',' voices'),
            ('volatilia','flights'), ('Voluitque','And_he_wanted_to'),
            (' vos ',' you '),
            (' vota ',' wishes '),
            ('Vox ','The_voice '),(' vox ',' voice '),
        (' vulva ',' womb '), ('vulneravit','wounded'),
    )
LatinWords, EnglishWords = [], []
for wordMapEntry in LATIN_WORD_MAP:
    assert len(wordMapEntry) == 2, f"{wordMapEntry}"
    LatinWord,EnglishWord = wordMapEntry
    assert isinstance( LatinWord, str ) and len(LatinWord)>=2, f"{LatinWord=}"
    assert LatinWord != EnglishWord, f"Attempting to replace identical Latin word: {LatinWord=}"
    assert LatinWord not in LatinWords, f"duplicate LatinWord: {LatinWord=} ({EnglishWord=})"
    if LatinWord.startswith(' ') or EnglishWord.startswith(' '): assert LatinWord.startswith(' '), f"Mismatched leading space: {LatinWord=} {EnglishWord=}"
    if LatinWord.endswith(' ') or EnglishWord.endswith(' '): assert LatinWord.endswith(' '), f"Mismatched trailing space: {LatinWord=} {EnglishWord=}"
    assert LatinWord not in EnglishWord, f"Recursive substitution of '{LatinWord}' into '{EnglishWord}'"
    assert '  ' not in LatinWord
    LatinWords.append( LatinWord)
    if LatinWord.startswith(' '): assert EnglishWord.startswith(' '), f"Mismatched leading space:  {LatinWord=} {EnglishWord=}"
    if LatinWord.endswith(' '): assert EnglishWord.endswith(' '), f"Mismatched trailing space: {LatinWord=} {EnglishWord=}"
    if EnglishWord[-1] in ' ,.:;':
        assert LatinWord[-1] == EnglishWord[-1], f"Mismatched trailing character: {LatinWord=} {EnglishWord=}"
    if LatinWord[-1] in ' ,.:;':
        assert EnglishWord[-1] == LatinWord[-1], f"Mismatched trailing character: {LatinWord=} {EnglishWord=}"
    assert '  ' not in EnglishWord
    if ' ' not in LatinWord.strip():
        assert ' ' not in EnglishWord.strip(), f"Space in middle of {EnglishWord=}" # No space in middle
    EnglishWords.append( EnglishWord )
del LatinWords, EnglishWords

def translateLatin( htmlStr:str ) -> str:
    """
    Do basic word-for-word translation from Latin Vulgate Bible to English.

    Text in htmlStr parameter can be inside a span,
        e.g., '<span class="Wycl_verseTextChunk">ech man in his seruice, and in the offring,</span>'
    """
    fnPrint( DEBUGGING_THIS_MODULE, f"translateLatin( ({len(htmlStr)}) )" )

    # NOTE: Didn't work because it's already html, so added back to table above with '>'
    # if html.startswith( 'et '): # Handle common exception that can't be expressed in the word table
    #     html = f'and {html[3:]}'
    # elif html.startswith( 'qui '):
    #     html = f'who {html[4:]}'
    for LatinWord,EnglishWord in LATIN_WORD_MAP:
        htmlStr = htmlStr.replace( LatinWord, EnglishWord )
        if LatinWord[0] == ' ':
            htmlStr = htmlStr.replace( f'>{LatinWord[1:]}', f'>{EnglishWord[1:]}' )


    return ( htmlStr.replace('j','y').replace('J','Y') # Try to write it like it might have sounded
                # But then need to fix up some regular English words
                .replace('yudge','judge')
                .replace('Yust ','Just ').replace('yust','just')
                .replace('Yhes','Jhes') # Change these ones back again -- 'Jhesus' -- was maybe more like French J ???
            ) 
# end of EuropeanToEnglish.translateLatin



def briefDemo() -> None:
    """
    Main program to handle command line parameters and then run what they want.
    """
    BibleOrgSysGlobals.introduceProgram( __name__, PROGRAM_NAME_VERSION, LAST_MODIFIED_DATE )

    # Demo the html object
    pass
# end of EuropeanToEnglish.briefDemo

def fullDemo() -> None:
    """
    Full demo to check class is working
    """
    BibleOrgSysGlobals.introduceProgram( __name__, PROGRAM_NAME_VERSION, LAST_MODIFIED_DATE )

    # Demo the html object
    pass
# end of EuropeanToEnglish.fullDemo

if __name__ == '__main__':
    from multiprocessing import freeze_support
    freeze_support() # Multiprocessing support for frozen Windows executables

    # Configure basic Bible Organisational System (BOS) set-up
    parser = BibleOrgSysGlobals.setup( SHORT_PROGRAM_NAME, PROGRAM_VERSION, LAST_MODIFIED_DATE )
    BibleOrgSysGlobals.addStandardOptionsAndProcess( parser )

    fullDemo()

    BibleOrgSysGlobals.closedown( PROGRAM_NAME, PROGRAM_VERSION )
# end of EuropeanToEnglish.py
