[workspace]
resolver = "3"
members = [
    "Rust/bible_organisational_system",
    "Rust/bos-internals",
    "Rust/bos_books_codes",
    "Rust/bos_books_codes_py",
    "Rust/usfm_markers",
    "Rust/usfm_markers_py",
]

[workspace.package]
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["Robert Hunt <Freely.Given.org+BOS@gmail.com>"]

[workspace.dependencies]
# local dependencies
bos-internals = { path = "Rust/bos-internals" }
bos_books_codes = { path = "Rust/bos_books_codes" }
usfm_markers = { path = "Rust/usfm_markers" }

compact_str = { version = "0.9.0", features = ["rkyv"] }
indexmap = "2.14"
pretty_assertions = "1.4"
log = "0.4"
pyo3-log = "0.13"
pyo3 = { version = "0.29.0", features = ["extension-module", "abi3-py312", "generate-import-lib"] }
quick-xml = "0.37"
regex = "1.12"
rayon = "1.10"
ureq = { version = "3.0", features = ["rustls"] }
rkyv = { version = "0.8", features = ["indexmap-2"] }
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# While we're still debugging
[profile.release]
debug = true
