[workspace]
resolver = "3"
members = [
    "Rust/bible_organisational_system",
    "Rust/bos-internals",
]

[workspace.package]
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["Robert Hunt <Freely.Given.org+BOS@gmail.com>"]

[workspace.dependencies]
compact_str = { version = "0.9.0", features = ["rkyv"] }
indexmap = "2.13"
pretty_assertions = "1.4"
pyo3 = { version = "0.28.3", features = ["extension-module", "abi3-py38", "generate-import-lib"] }
regex = "1.12"
rkyv = { version = "0.8", features = ["indexmap-2"] }
thiserror = "2.0"

# While we're still debugging
[profile.release]
debug = true
