# Auto-generated by rylai. Do not edit manually.

import typing as t

__all__ = [
    "exportToText",
    "exportToHtml5",
    "getSmallLeadingInt",
    "getPositiveLeadingInt",
    "set_rust_verbosity",
    "set_rust_debug",
    "set_rust_strict_checking",
    "processLines",
    "processBible",
    "parseOsis",
    "saveBookFast",
    "loadBookFast",
    "discoverBible",
    "discoverFilenames",
    "detectBibles",
    "parseWordAttributes",
    "validateMarkers",
    "validateBibleMarkers",
    "getVersification",
    "getBibleVersification",
    "getAddedUnits",
    "getBibleAddedUnits",
    "checkBook",
    "checkBible",
    "buildBibleCVIndexes",
    "buildBibleSectionIndexes",
    "splitUSFMMarkerFromText",
    "readUSFMFile",
    "readESFMFile",
    "readSFMLines",
    "readSFMRecords",
    "escapeCharacters",
    "validateWellFormedness",
    "validateWithLint",
    "DiscoveryFlags",
    "CheckOptions",
    "InternalBibleExtra",
    "InternalBibleExtraList",
    "PyInternalBibleExtraListIter",
    "BookDiscoveryResults",
    "AggregateDiscoveryResults",
    "BibleDiscoveryResults",
    "DiscoveryOptions",
    "DiscoveryResults",
    "DetectedBible",
    "ChapterVerse",
    "InternalBibleEntry",
    "InternalBibleEntryList",
    "PyInternalBibleEntryListIter",
    "CVIndexEntry",
    "InternalBibleBookCVIndex",
    "PyCVIndexIter",
    "InternalBibleBookSectionIndexEntry",
    "InternalBibleBookSectionIndex",
    "PySectionIndexIter",
    "ObjectType",
    "ProcessLinesOptions",
    "MlWriter",
    "MlOutputType",
    "HumanReadable",
    "SectionName",
]

# Module: bible_organisational_system
def exportToText(books_dict: dict, output_path_str: str, column_width: int) -> set:
    """
    Python-accessible wrapper for `export_to_text`.

    Iterates over Python book objects in self.books, extracts their underlying
    Rust `InternalBibleEntryList` from `_processedLines`, and runs the parallel export engine.
    """

def exportToHtml5(books_dict: dict, output_path_str: str, column_width: int) -> set:
    """Python-accessible wrapper for `export_to_html5`."""

def getSmallLeadingInt(s: str) -> int:
    """Extract leading integer from a string (e.g., "17a" -> 17)."""

def getPositiveLeadingInt(s: str) -> int:
    """Extract leading integer from a string (e.g., "17a" -> 17)."""

def set_rust_verbosity(level: int) -> None: ...
def set_rust_debug(value: bool) -> None: ...
def set_rust_strict_checking(value: bool) -> None: ...
def processLines(
    raw_lines: list[tuple[str, str]],
    book_code: str,
    work_name: str,
    options: ProcessLinesOptions,
) -> InternalBibleEntryList: ...
def processBible(
    books_dict: dict, work_name: str, options: ProcessLinesOptions
) -> dict: ...
def parseOsis(path: str) -> dict: ...
def saveBookFast(
    path: str,
    work_name: str,
    book_code: str,
    entries: InternalBibleEntryList,
    cv_index: InternalBibleBookCVIndex | None,
    section_index: InternalBibleBookSectionIndex | None,
) -> None: ...
def loadBookFast(path: str) -> dict: ...
def discoverBible(books_dict: dict) -> BibleDiscoveryResults: ...
def discoverBible(books_dict: dict) -> BibleDiscoveryResults: ...
def discoverFilenames(
    folder: str, is_usx: bool, options: DiscoveryOptions | None
) -> DiscoveryResults: ...
def detectBibles(root: str, strict: bool) -> list[DetectedBible]: ...
def parseWordAttributes(*args, **_kwargs) -> dict:
    """
    Parse word attributes from a USFM3 `\w` field.
    Returns a dict for backward compatibility with the old Python implementation.
    """

def validateMarkers(
    entries: InternalBibleEntryList,
    book_code: str,
    work_name: str,
    strict_checking: bool,
) -> dict: ...
def validateBibleMarkers(
    books_dict: dict, work_name: str, strict_checking: bool
) -> dict: ...
def getVersification(
    entries: InternalBibleEntryList, book_code: str, work_name: str
) -> dict: ...
def getBibleVersification(books_dict: dict, work_name: str) -> dict: ...
def getAddedUnits(entries: InternalBibleEntryList, book_code: str) -> dict: ...
def getBibleAddedUnits(books_dict: dict) -> dict: ...
def checkBook(
    entries: InternalBibleEntryList,
    book_code: str,
    work_name: str,
    options: CheckOptions,
    discovery: DiscoveryFlags,
) -> dict: ...
def checkBible(
    books_dict: dict,
    work_name: str,
    options: CheckOptions,
    discovery_results: BibleDiscoveryResults,
) -> dict: ...
def buildBibleCVIndexes(books_dict: dict, work_name: str) -> dict:
    """Build CV indexes for all books in parallel."""

def buildBibleSectionIndexes(books_dict: dict, work_name: str) -> dict:
    """Build section indexes for all books in parallel."""

def splitUSFMMarkerFromText(line: str) -> t.Any:
    """Python binding for split_usfm_marker_from_text."""

def readUSFMFile(path: str, ignore_sfms: list[str]) -> t.Any:
    """Python binding for USFMFile.read"""

def readESFMFile(path: str, ignore_sfms: list[str]) -> t.Any:
    """Python binding for ESFMFile.read"""

def readSFMLines(path: str, ignore_sfms: list[str]) -> t.Any:
    """Python binding for SFMLines.read"""

def readSFMRecords(
    path: str,
    key: str | None,
    ignore_sfms: list[str],
    ignore_entries: list[str],
    change_pairs: list[tuple[str, str]],
) -> t.Any:
    """Python binding for SFMRecords.read"""

def escapeCharacters(s: str) -> str: ...
def validateWellFormedness(path: str) -> bool:
    """Check if XML is well-formed."""

def validateWithLint(xml_path: str, schema_path: str | None) -> tuple:
    """Validate XML with xmllint."""

@t.final
class DiscoveryFlags:
    def __init__(
        self,
        partly_done: bool = False,
        percentage_progress: float = 0.0,
        seems_finished: bool = False,
        have_main_headings: bool = False,
        have_introductory_text: bool = False,
    ) -> None: ...
    @property
    def partly_done(self) -> bool: ...
    @partly_done.setter
    def partly_done(self, value: bool) -> None: ...
    @property
    def partlyDone(self) -> bool: ...
    @partlyDone.setter
    def partlyDone(self, value: bool) -> None: ...
    @property
    def percentage_progress(self) -> float: ...
    @percentage_progress.setter
    def percentage_progress(self, value: float) -> None: ...
    @property
    def percentageProgress(self) -> float: ...
    @percentageProgress.setter
    def percentageProgress(self, value: float) -> None: ...
    @property
    def seems_finished(self) -> bool: ...
    @seems_finished.setter
    def seems_finished(self, value: bool) -> None: ...
    @property
    def seemsFinished(self) -> bool: ...
    @seemsFinished.setter
    def seemsFinished(self, value: bool) -> None: ...
    @property
    def have_main_headings(self) -> bool: ...
    @have_main_headings.setter
    def have_main_headings(self, value: bool) -> None: ...
    @property
    def haveMainHeadings(self) -> bool: ...
    @haveMainHeadings.setter
    def haveMainHeadings(self, value: bool) -> None: ...
    @property
    def have_introductory_text(self) -> bool: ...
    @have_introductory_text.setter
    def have_introductory_text(self, value: bool) -> None: ...
    @property
    def haveIntroductoryText(self) -> bool: ...
    @haveIntroductoryText.setter
    def haveIntroductoryText(self, value: bool) -> None: ...

@t.final
class CheckOptions:
    def __init__(self) -> None: ...
    @property
    def check_sfms(self) -> bool: ...
    @check_sfms.setter
    def check_sfms(self, value: bool) -> None: ...
    @property
    def checkSFMs(self) -> bool: ...
    @checkSFMs.setter
    def checkSFMs(self, value: bool) -> None: ...
    @property
    def check_words(self) -> bool: ...
    @check_words.setter
    def check_words(self, value: bool) -> None: ...
    @property
    def checkWords(self) -> bool: ...
    @checkWords.setter
    def checkWords(self, value: bool) -> None: ...
    @property
    def check_headings(self) -> bool: ...
    @check_headings.setter
    def check_headings(self, value: bool) -> None: ...
    @property
    def checkHeadings(self) -> bool: ...
    @checkHeadings.setter
    def checkHeadings(self, value: bool) -> None: ...
    @property
    def check_introduction(self) -> bool: ...
    @check_introduction.setter
    def check_introduction(self, value: bool) -> None: ...
    @property
    def checkIntroduction(self) -> bool: ...
    @checkIntroduction.setter
    def checkIntroduction(self, value: bool) -> None: ...
    @property
    def check_notes(self) -> bool: ...
    @check_notes.setter
    def check_notes(self, value: bool) -> None: ...
    @property
    def checkNotes(self) -> bool: ...
    @checkNotes.setter
    def checkNotes(self, value: bool) -> None: ...
    @property
    def check_speech_marks(self) -> bool: ...
    @check_speech_marks.setter
    def check_speech_marks(self, value: bool) -> None: ...
    @property
    def checkSpeechMarks(self) -> bool: ...
    @checkSpeechMarks.setter
    def checkSpeechMarks(self, value: bool) -> None: ...
    @property
    def check_added_units(self) -> bool: ...
    @check_added_units.setter
    def check_added_units(self, value: bool) -> None: ...
    @property
    def checkAddedUnits(self) -> bool: ...
    @checkAddedUnits.setter
    def checkAddedUnits(self, value: bool) -> None: ...
    @property
    def opening_chars(self) -> str: ...
    @opening_chars.setter
    def opening_chars(self, value: str) -> None: ...
    @property
    def openingChars(self) -> str: ...
    @openingChars.setter
    def openingChars(self, value: str) -> None: ...
    @property
    def closing_chars(self) -> str: ...
    @closing_chars.setter
    def closing_chars(self, value: str) -> None: ...
    @property
    def closingChars(self) -> str: ...
    @closingChars.setter
    def closingChars(self, value: str) -> None: ...
    @property
    def leading_punct(self) -> str: ...
    @leading_punct.setter
    def leading_punct(self, value: str) -> None: ...
    @property
    def leadingPunct(self) -> str: ...
    @leadingPunct.setter
    def leadingPunct(self, value: str) -> None: ...
    @property
    def trailing_punct(self) -> str: ...
    @trailing_punct.setter
    def trailing_punct(self, value: str) -> None: ...
    @property
    def trailingPunct(self) -> str: ...
    @trailingPunct.setter
    def trailingPunct(self, value: str) -> None: ...

@t.final
class InternalBibleExtra:
    """
    An "extra" element extracted from Bible text (footnote, cross-ref, etc.).

    Each extra contains:
    - myType: The type string ('fn', 'en', 'xr', 'fig', 'str', 'sem', 'ww', 'vp')
    - index: Position in the adjusted text where this was extracted
    - noteText: Full text with USFM markers
    - cleanNoteText: Plain text without markers
    """
    def __init__(
        self,
        my_type: str,
        index_to_adj_text: int,
        note_text: str,
        clean_note_text: str,
        location: str | None = None,
    ) -> None:
        """
        Create a new InternalBibleExtra.

        Args:
        myType: Type string ('fn', 'en', 'xr', 'fig', 'str', 'sem', 'ww', 'vp')
        indexToAdjText: Position in adjusted text
        noteText: Full note text with USFM markers
        cleanNoteText: Clean note text without markers
        location: Location string for error messages (not stored)
        """

    def __getnewargs__(self) -> tuple[str, int, str, str]: ...
    @property
    def myType(self) -> str:
        """Get the type string."""

    @property
    def index(self) -> int:
        """Get the index into adjusted text."""

    @property
    def noteText(self) -> str:
        """Get the full note text."""

    @property
    def cleanNoteText(self) -> str:
        """Get the clean note text."""

    def getType(self) -> str:
        """Get the type string (Python compat)."""

    def getIndex(self) -> int:
        """Get the index (Python compat)."""

    def getText(self) -> str:
        """Get the note text (Python compat)."""

    def getCleanText(self) -> str:
        """Get the clean note text (Python compat)."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> t.Any: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: InternalBibleExtra) -> bool: ...
    def __ne__(self, other: InternalBibleExtra) -> bool: ...

@t.final
class InternalBibleExtraList:
    """A list of InternalBibleExtra objects."""
    def __init__(self, initial_data: t.Any | None = None) -> None:
        """Create a new InternalBibleExtraList, optionally from existing data."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> InternalBibleExtra: ...
    def __iter__(self) -> PyInternalBibleExtraListIter: ...
    def __bool__(self) -> bool: ...
    def append(self, new_extra: InternalBibleExtra) -> None:
        """Add an extra to the list."""

    def pop(self) -> InternalBibleExtra | None:
        """Remove and return the last extra."""

    def extend(self, other: InternalBibleExtraList) -> None:
        """Extend with another list."""

    def checkForIndex(self, string_index: int) -> t.Any:
        """
        Check for extras at a specific string index.

        Returns None if no extras found, a single extra if one found,
        or a list if multiple found.
        """

    def summary(self) -> str:
        """Get a short summary string."""

    def fullSummary(self) -> str:
        """Get a full summary string with note text."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: InternalBibleExtraList) -> bool: ...

@t.final
class PyInternalBibleExtraListIter:
    """Iterator for PyInternalBibleExtraList."""
    def __iter__(self) -> t.Self: ...
    def __next__(self) -> InternalBibleExtra | None: ...

@t.final
class BookDiscoveryResults:
    @property
    def chapter_count(self) -> int | None: ...
    @property
    def verse_count(self) -> int | None: ...
    @property
    def completed_verse_count(self) -> int: ...
    @property
    def percentage_progress(self) -> int | None: ...
    @property
    def word_count(self) -> int: ...
    def __getitem__(self, key: str) -> t.Any: ...
    def to_dict(self) -> dict: ...

@t.final
class AggregateDiscoveryResults:
    def to_dict(self) -> dict: ...

@t.final
class BibleDiscoveryResults:
    @property
    def all(self) -> AggregateDiscoveryResults: ...
    @property
    def books(self) -> dict: ...
    @property
    def books_as_objects(self) -> dict: ...
    def get_book_results(self, bbb: str) -> BookDiscoveryResults | None: ...

@t.final
class DiscoveryOptions:
    @property
    def strict_check(self) -> bool: ...
    @strict_check.setter
    def strict_check(self, value: bool) -> None: ...
    def __init__(self, strict_check: bool | None) -> None: ...

@t.final
class DiscoveryResults:
    @property
    def folder(self) -> str: ...
    @property
    def pattern(self) -> str: ...
    @property
    def fileExtension(self) -> str: ...
    @property
    def matchedFiles(self) -> list[tuple[str, str]]: ...
    @property
    def unusedFilenames(self) -> list[str]: ...
    def to_dict(self) -> dict: ...

@t.final
class DetectedBible:
    @property
    def format(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def confidence(self) -> int: ...
    def __repr__(self) -> str: ...

@t.final
class ChapterVerse:
    """
    A chapter:verse reference in a Bible book.

    Both chapter and verse are stored as strings to handle special cases:
    - Chapter `-1` for introductions
    - Verse suffixes like `17a`
    - Verse ranges like `17-25`
    - Verse lists like `5,6,7`
    """
    def __init__(self, chapter: str, verse: str) -> None:
        """
        Create a new ChapterVerse reference.

        Args:
        chapter: The chapter string (e.g., "3", "-1" for intro)
        verse: The verse string (e.g., "16", "17a", "17-25")
        """

    def __getnewargs__(self) -> tuple[str, str]: ...
    @staticmethod
    def intro(verse_line: int) -> t.Self:
        """Create an introduction reference (chapter -1)."""

    @staticmethod
    def chapter_intro(chapter: str) -> t.Self:
        """Create a chapter introduction reference (verse 0)."""

    @property
    def chapter(self) -> str:
        """Get the chapter string."""

    @property
    def verse(self) -> str:
        """Get the verse string."""

    def chapter_int(self) -> int:
        """Get the leading integer from the chapter."""

    def verse_int(self) -> int:
        """Get the leading integer from the verse."""

    def is_intro(self) -> bool:
        """Check if this is an introduction reference (chapter -1)."""

    def is_chapter_intro(self) -> bool:
        """Check if this is a chapter introduction (verse 0)."""

    def is_verse_range(self) -> bool:
        """Check if the verse contains a range (e.g., "17-25")."""

    def is_verse_list(self) -> bool:
        """Check if the verse contains a list (e.g., "5,6,7")."""

    def has_verse_suffix(self) -> bool:
        """Check if the verse has a suffix (e.g., "17a")."""

    def parse_verse_range(self) -> tuple[int, int] | None:
        """Parse a verse range into (start, end) integers."""

    def contains_verse(self, verse_num: int) -> bool:
        """Check if this reference contains the given verse number."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: ChapterVerse) -> bool: ...
    def __hash__(self) -> int: ...

@t.final
class InternalBibleEntry:
    """
    A single line/entry in the internal Bible format.

    Backward-compatible with the Python InternalBibleEntry class.

    Constructor accepts either:
    - Full 6-arg form: (marker, originalMarker, adjustedText, cleanText, extras, original_text)
    - Simple 2-arg form: (marker, cleanText) — creates entry with all text fields set to cleanText

    Supports both snake_case properties and camelCase getter methods.
    """
    def __init__(
        self,
        marker: str,
        original_marker: str | None,
        adjusted_text: str | None = None,
        clean_text: str | None = None,
        extras: InternalBibleExtraList | None = None,
        original_text: str | None = None,
    ) -> None:
        """
        Create a new InternalBibleEntry.

        Matches the Python constructor signature:
        InternalBibleEntry(marker, originalMarker, adjustedText, cleanText, extras, original_text)

        For end markers / added nesting markers, originalMarker through original_text should be None.
        """

    def __getnewargs__(
        self,
    ) -> tuple[
        str,
        str | None,
        str | None,
        str | None,
        InternalBibleExtraList | None,
        str | None,
    ]: ...
    @property
    def marker(self) -> str:
        """Get the (adjusted) marker."""

    @property
    def originalMarker(self) -> str | None:
        """Get the original marker before adjustment."""

    @property
    def adjustedText(self) -> str | None:
        """Get the adjusted text (notes removed, formatting retained)."""

    @property
    def cleanText(self) -> str:
        """Get the clean text (notes and formatting removed)."""

    @property
    def extras(self) -> InternalBibleExtraList | None:
        """Get the extras (footnotes, cross-refs, etc.)."""

    @property
    def original_text(self) -> str | None:
        """Get the original text (full USFM)."""

    def getMarker(self) -> str:
        """Get the marker (Python compat)."""

    def getOriginalMarker(self) -> str | None:
        """Get the original marker (Python compat)."""

    def getAdjustedText(self) -> str | None:
        """Get the adjusted text (Python compat)."""

    def getText(self) -> str | None:
        """Get the adjusted text — alias (Python compat)."""

    def getCleanText(self, remove_esfm_underlines: bool = False) -> str:
        """Get the clean text, optionally removing ESFM underlines (Python compat)."""

    def getExtras(self) -> InternalBibleExtraList | None:
        """Get the extras (Python compat)."""

    def getOriginalText(self) -> str | None:
        """Get the original text (Python compat)."""

    def getFullText(self) -> str | None:
        """Get the full text — returns original_text (Python compat)."""

    def setCleanText(self, new_value: str) -> None:
        """
        Set the clean text (also sets adjusted and original text).
        Only works when extras is None.
        """

    def is_end_marker(self) -> bool:
        """Check if this is an end marker."""

    def has_extras(self) -> bool:
        """Check if this entry has extras (footnotes, cross-refs)."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> t.Any: ...
    def __eq__(self, other: InternalBibleEntry) -> bool: ...
    def __ne__(self, other: InternalBibleEntry) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

@t.final
class InternalBibleEntryList:
    """
    A list of Bible entries.

    This represents the processed lines of a Bible book or a slice of entries.
    Backward-compatible with the Python InternalBibleEntryList class.
    """
    def __init__(self, initial_data: t.Any | None = None) -> None:
        """Create a new entry list, optionally from existing data."""

    def __len__(self) -> int:
        """Get the number of entries."""

    def is_empty(self) -> bool:
        """Check if the list is empty."""

    def __getitem__(self, index: t.Any) -> t.Any:
        """Get an entry by index. Supports negative indexing and slicing."""

    def __iter__(self) -> PyInternalBibleEntryListIter:
        """Iterate over entries."""

    def __bool__(self) -> bool: ...
    def append(self, entry: InternalBibleEntry) -> None:
        """Add an entry to the list."""

    def pop(self) -> InternalBibleEntry | None:
        """Remove and return the last entry."""

    def extend(self, other: InternalBibleEntryList) -> None:
        """Extend with another entry list."""

    def __add__(self, other: InternalBibleEntryList) -> t.Self:
        """Support the + operator to combine lists (Python compat)."""

    def contains(self, search_marker: str, max_lines: int | None = None) -> int | None:
        """Search for the first entry with the given marker (Python compat: `contains`)."""

    def find_marker(self, marker: str, max_lines: int | None = None) -> int | None:
        """Find the first entry with the given marker (alias)."""

    def slice(self, start: int, end: int) -> t.Self:
        """Get a slice of entries."""

    def to_list(self) -> list[tuple[str, str]]:
        """Get all entries as a list of tuples (marker, clean_text)."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getstate__(self) -> t.Any: ...
    def __setstate__(self, state: t.Any) -> None: ...

@t.final
class PyInternalBibleEntryListIter:
    """Iterator for PyInternalBibleEntryList."""
    def __iter__(self) -> t.Self: ...
    def __next__(self) -> InternalBibleEntry | None: ...

@t.final
class CVIndexEntry:
    """
    An entry in the CV index, representing a single Chapter:Verse reference.

    Each entry stores:
    - entryIndex: The index into the entry list where this CV starts
    - entryCount: The count of entries for this CV
    - context: The context markers that were open at this point

    Supports both snake_case properties and camelCase getter methods.
    """
    def __init__(
        self, entry_index: int, entry_count: int, context: list[str] | None = None
    ) -> None:
        """
        Create a new CV index entry.

        Args:
        entry_index: The starting index into the entry list
        entry_count: Number of entries for this C:V
        context: Optional list of context markers
        """

    def __getnewargs__(self) -> tuple[int, int, list[str] | None]: ...
    @property
    def entryIndex(self) -> int:
        """Get the starting entry index."""

    @property
    def entryCount(self) -> int:
        """Get the entry count for this C:V."""

    def next_entry_index(self) -> int:
        """Get the index one past the last entry for this C:V."""

    @property
    def context(self) -> list[str]:
        """Get the context markers."""

    def getEntryIndex(self) -> int:
        """Get the entry index (Python compat)."""

    def getNextEntryIndex(self) -> int:
        """Get the next entry index (Python compat)."""

    def getEntryCount(self) -> int:
        """Get the entry count (Python compat)."""

    def getContextList(self) -> list[str]:
        """Get the context list (Python compat)."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> t.Any: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

@t.final
class InternalBibleBookCVIndex:
    """
    Index for fast Chapter:Verse lookup in a Bible book.

    The index maps (Chapter, Verse) references to entry ranges.
    Accepts both (str, str) tuples and ChapterVerse objects for keys.

    Special cases:
    - Chapter `-1`: Book introduction
    - Verse `0`: Chapter introduction / section headings before first verse
    - Verse ranges: e.g., `17-25` for bridged verses
    - Verse lists: e.g., `5,6,7` for multiple verses in one entry
    - Verse suffixes: e.g., `17a`, `17b`
    """
    def __init__(self, work_name: str, bos_book_code: str) -> None:
        """
        Create a new empty CV index.

        Args:
        work_name: Name of the work/Bible (e.g., "ESV", "KJV")
        bos_book_code: Three-letter book code (e.g., "GEN", "MAT")
        """

    def __getnewargs__(self) -> tuple[str, str]: ...
    @property
    def work_name(self) -> str:
        """Get the work name."""

    @property
    def bos_book_code(self) -> str:
        """Get the book code."""

    @property
    def is_indexed(self) -> bool:
        """Check if the index has been built."""

    @property
    def entries(self) -> InternalBibleEntryList:
        """Get direct access to the underlying entries."""

    @property
    def workName(self) -> str:
        """Get the work name (Python compat)."""

    @property
    def BBB(self) -> str:
        """Get the book code (Python compat: BBB)."""

    @property
    def _indexedFlag(self) -> bool:
        """Check if indexed (Python compat: _indexedFlag)."""

    @property
    def givenBibleEntries(self) -> InternalBibleEntryList:
        """Get the entries list (Python compat: givenBibleEntries)."""

    def __len__(self) -> int:
        """Get the number of CV entries in the index."""

    def is_empty(self) -> bool:
        """Check if the index is empty."""

    def __contains__(self, key: t.Any) -> bool:
        """Check if a (C,V) tuple or ChapterVerse exists in the index."""

    def __getitem__(self, key: tuple[str, str]) -> CVIndexEntry:
        """Get a CVIndexEntry for a (C,V) tuple key."""

    def __iter__(self) -> PyCVIndexIter:
        """Iterate over (C,V) tuples."""

    def items(self) -> list:
        """Iterate over ((C,V), CVIndexEntry) pairs."""

    def chapters(self) -> list[str]:
        """Get all chapters in the index."""

    def contains(self, key: t.Any) -> bool:
        """Check if a CV exists in the index (accepts tuple or ChapterVerse)."""

    def get_verse_entries(
        self, cv: ChapterVerse, strict: bool = True
    ) -> InternalBibleEntryList:
        """Get verse entries using a ChapterVerse object."""

    def get_verse_entries_with_context(
        self, cv: ChapterVerse, strict: bool = True, complete: bool = False
    ) -> tuple[InternalBibleEntryList, list[str]]:
        """Get verse entries with context using a ChapterVerse object."""

    def get_chapter_entries(self, chapter: str) -> InternalBibleEntryList:
        """Get all entries for a chapter (snake_case)."""

    def build(self, entries: InternalBibleEntryList) -> None:
        """Build the CV index from processed entries (snake_case)."""

    def validate(self) -> list[str]:
        """Validate the index structure."""

    def makeBookCVIndex(self, entries: InternalBibleEntryList) -> None:
        """Build the CV index from processed entries (Python compat)."""

    def discover(self) -> BookDiscoveryResults:
        """Perform discovery on this book (Python compat)."""

    def getVerseEntries(
        self, cv_key: tuple[str, str], strict: bool = True
    ) -> InternalBibleEntryList:
        """Get verse entries for a (C,V) tuple key."""

    def getVerseEntriesWithContext(
        self, cv_key: tuple[str, str], strict: bool = False, complete: bool = False
    ) -> tuple[InternalBibleEntryList, list[str]]:
        """Get verse entries with context for a (C,V) tuple key."""

    def getChapterEntries(self, chapter: str) -> InternalBibleEntryList:
        """Get all entries for a chapter (Python compat)."""

    def getChapterEntriesWithContext(
        self, chapter: str
    ) -> tuple[InternalBibleEntryList, list[str]]:
        """Get chapter entries with context markers (Python compat)."""

    def getEntries(self) -> InternalBibleEntryList:
        """Get all entries (Python compat alias for entries property)."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getstate__(self) -> t.Any: ...
    def __setstate__(self, state: t.Any) -> None: ...

@t.final
class PyCVIndexIter:
    """Iterator for PyInternalBibleBookCVIndex, yields (C, V) string tuples."""
    def __iter__(self) -> t.Self: ...
    def __next__(self) -> tuple[str, str] | None: ...

@t.final
class InternalBibleBookSectionIndexEntry:
    """
    A section index entry for a Bible book.

    Each entry represents a section boundary and contains:
    - endC, endV: End chapter and verse (inclusive)
    - startIx, endIx: Start and end entry indices
    - reasonMarker: The marker that started this section (e.g., "s1", "c")
    - sectionName: The section heading text
    - contextList: Context markers active at this point
    """
    def __init__(
        self,
        end_c: str,
        end_v: str,
        start_ix: int,
        end_ix: int,
        reason_marker: str,
        section_name: str,
        context_list: list[str] | None = None,
    ) -> None:
        """
        Create a new section index entry.

        Args:
        endC: End chapter number string
        endV: End verse number string
        startIx: Start entry index
        endIx: End entry index (inclusive)
        reasonMarker: Marker that started this section
        sectionName: Section heading text
        contextList: Optional list of context markers
        """

    def __getnewargs__(
        self,
    ) -> tuple[str, str, int, int, str, str, list[str] | None]: ...
    @property
    def endC(self) -> str: ...
    @property
    def endV(self) -> str: ...
    @property
    def startIx(self) -> int: ...
    @property
    def endIx(self) -> int: ...
    @property
    def reasonMarker(self) -> str: ...
    @property
    def sectionName(self) -> str: ...
    @property
    def contextList(self) -> list[str]: ...
    def getEndCV(self) -> tuple[str, str]:
        """Get end chapter and verse as (str, str) tuple."""

    def getStartIndex(self) -> int:
        """Get start entry index."""

    def getEndIndex(self) -> int:
        """Get end entry index (inclusive)."""

    def getEntryCount(self) -> int:
        """Get entry count (endIx + 1 - startIx)."""

    def getContextList(self) -> list[str]:
        """Get context markers list."""

    def getSectionNameReason(self) -> tuple[str, str]:
        """Get section name and reason marker as (str, str) tuple."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> t.Any: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

@t.final
class InternalBibleBookSectionIndex:
    """
    Section index for a Bible book.

    Maps section starting points (C:V) to section entries.
    Accepts (str, str) tuples for keys.
    """
    def __init__(self, work_name: str, bos_book_code: str) -> None:
        """Create a new empty section index."""

    def __getnewargs__(self) -> tuple[str, str]: ...
    @property
    def workName(self) -> str: ...
    @property
    def BBB(self) -> str: ...
    @property
    def _indexedFlag(self) -> bool: ...
    @property
    def givenBibleEntries(self) -> InternalBibleEntryList: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: tuple[str, str]) -> bool: ...
    def __getitem__(
        self, key: tuple[str, str]
    ) -> InternalBibleBookSectionIndexEntry: ...
    def __iter__(self) -> PySectionIndexIter: ...
    def items(
        self,
    ) -> list[tuple[tuple[str, str], InternalBibleBookSectionIndexEntry]]: ...
    def makeBookSectionIndex(self, entries: InternalBibleEntryList) -> None:
        """Build the section index from processed entries."""

    def getSectionEntries(self, key: tuple[str, str]) -> InternalBibleEntryList:
        """Get entries for a section by (C,V) key."""

    def getSectionEntriesWithContext(
        self, key: tuple[str, str]
    ) -> tuple[InternalBibleEntryList, list[str]]:
        """Get section entries with context markers."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getstate__(self) -> t.Any: ...
    def __setstate__(self, state: t.Any) -> None: ...

@t.final
class PySectionIndexIter:
    """Iterator for PyInternalBibleBookSectionIndex, yields (C, V) string tuples."""
    def __iter__(self) -> t.Self: ...
    def __next__(self) -> tuple[str, str] | None: ...

@t.final
class ObjectType: ...

@t.final
class ProcessLinesOptions:
    @property
    def replace_angle_brackets(self) -> bool: ...
    @replace_angle_brackets.setter
    def replace_angle_brackets(self, value: bool) -> None: ...
    @property
    def replace_straight_double_quotes(self) -> bool: ...
    @replace_straight_double_quotes.setter
    def replace_straight_double_quotes(self, value: bool) -> None: ...
    @property
    def strict_checking(self) -> bool: ...
    @strict_checking.setter
    def strict_checking(self, value: bool) -> None: ...
    @property
    def object_type(self) -> ObjectType: ...
    @object_type.setter
    def object_type(self, value: ObjectType) -> None: ...
    def __init__(
        self,
        replace_angle_brackets: bool = True,
        replace_straight_double_quotes: bool = False,
        strict_checking: bool = False,
        object_type: ObjectType | None = None,
    ) -> None: ...

@t.final
class MlWriter:
    def __init__(self, path: str, output_type: MlOutputType) -> None: ...
    @space_before_selfclose_tag.setter
    def space_before_selfclose_tag(self, value: bool) -> None: ...
    @halt_on_errors.setter
    def halt_on_errors(self, value: bool) -> None: ...
    @property
    def lines_written(self) -> int: ...
    def set_human_readable(self, value: HumanReadable, indent_size: int) -> None: ...
    def set_section_name(self, name: SectionName) -> None: ...
    def start(self, line_endings: str, no_auto_xml: bool, write_bom: bool) -> None: ...
    def write_line_text(self, text: str, no_nl: bool | None) -> int: ...
    def write_line_open(
        self, tag: str, attrib_info: list[tuple[str, str]] | None, no_nl: bool | None
    ) -> None: ...
    def write_line_close(self, tag: str) -> None: ...
    def write_line_open_close(
        self, tag: str, text: str, attrib_info: list[tuple[str, str]] | None
    ) -> int: ...
    def write_line_open_selfclose(
        self, tag: str, attrib_info: list[tuple[str, str]] | None
    ) -> int: ...
    def close(self, write_final_nl: bool) -> None: ...
    def get_file_position(self) -> int: ...

@t.final
class MlOutputType: ...

@t.final
class HumanReadable: ...

@t.final
class SectionName: ...
