# Auto-generated by rylai. Do not edit manually.

import typing as t

__all__ = [
    "getSmallLeadingInt",
    "getPositiveLeadingInt",
    "set_rust_verbosity",
    "set_rust_debug",
    "set_rust_strict_checking",
    "processLines",
    "InternalBibleExtra",
    "InternalBibleExtraList",
    "PyInternalBibleExtraListIter",
    "ChapterVerse",
    "InternalBibleEntry",
    "InternalBibleEntryList",
    "PyInternalBibleEntryListIter",
    "CVIndexEntry",
    "InternalBibleBookCVIndex",
    "PyCVIndexIter",
    "InternalBibleBookSectionIndexEntry",
    "InternalBibleBookSectionIndex",
    "PySectionIndexIter",
    "ObjectType",
    "ProcessLinesOptions",
]

# Module: bible_organisational_system
def getSmallLeadingInt(s: str) -> int:
    """Extract leading integer from a string (e.g., "17a" -> 17)."""

def getPositiveLeadingInt(s: str) -> int:
    """Extract leading integer from a string (e.g., "17a" -> 17)."""

def set_rust_verbosity(level: int) -> None: ...
def set_rust_debug(value: bool) -> None: ...
def set_rust_strict_checking(value: bool) -> None: ...
def processLines(
    raw_lines: list[tuple[str, str]],
    book_code: str,
    work_name: str,
    options: ProcessLinesOptions,
) -> InternalBibleEntryList: ...

@t.final
class InternalBibleExtra:
    """
    An "extra" element extracted from Bible text (footnote, cross-ref, etc.).

    Each extra contains:
    - myType: The type string ('fn', 'en', 'xr', 'fig', 'str', 'sem', 'ww', 'vp')
    - index: Position in the adjusted text where this was extracted
    - noteText: Full text with USFM markers
    - cleanNoteText: Plain text without markers
    """
    def __init__(
        self,
        my_type: str,
        index_to_adj_text: int,
        note_text: str,
        clean_note_text: str,
        location: str | None = None,
    ) -> None:
        """
        Create a new InternalBibleExtra.

        Args:
        myType: Type string ('fn', 'en', 'xr', 'fig', 'str', 'sem', 'ww', 'vp')
        indexToAdjText: Position in adjusted text
        noteText: Full note text with USFM markers
        cleanNoteText: Clean note text without markers
        location: Location string for error messages (not stored)
        """

    def __getnewargs__(self) -> tuple[str, int, str, str]: ...
    @property
    def myType(self) -> str:
        """Get the type string."""

    @property
    def index(self) -> int:
        """Get the index into adjusted text."""

    @property
    def noteText(self) -> str:
        """Get the full note text."""

    @property
    def cleanNoteText(self) -> str:
        """Get the clean note text."""

    def getType(self) -> str:
        """Get the type string (Python compat)."""

    def getIndex(self) -> int:
        """Get the index (Python compat)."""

    def getText(self) -> str:
        """Get the note text (Python compat)."""

    def getCleanText(self) -> str:
        """Get the clean note text (Python compat)."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> t.Any: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: InternalBibleExtra) -> bool: ...
    def __ne__(self, other: InternalBibleExtra) -> bool: ...

@t.final
class InternalBibleExtraList:
    """A list of InternalBibleExtra objects."""
    def __init__(self, initial_data: t.Any | None = None) -> None:
        """Create a new InternalBibleExtraList, optionally from existing data."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> InternalBibleExtra: ...
    def __iter__(self) -> PyInternalBibleExtraListIter: ...
    def __bool__(self) -> bool: ...
    def append(self, new_extra: InternalBibleExtra) -> None:
        """Add an extra to the list."""

    def pop(self) -> InternalBibleExtra | None:
        """Remove and return the last extra."""

    def extend(self, other: InternalBibleExtraList) -> None:
        """Extend with another list."""

    def checkForIndex(self, string_index: int) -> t.Any:
        """
        Check for extras at a specific string index.

        Returns None if no extras found, a single extra if one found,
        or a list if multiple found.
        """

    def summary(self) -> str:
        """Get a short summary string."""

    def fullSummary(self) -> str:
        """Get a full summary string with note text."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: InternalBibleExtraList) -> bool: ...

@t.final
class PyInternalBibleExtraListIter:
    """Iterator for PyInternalBibleExtraList."""
    def __iter__(self) -> t.Self: ...
    def __next__(self) -> InternalBibleExtra | None: ...

@t.final
class ChapterVerse:
    """
    A chapter:verse reference in a Bible book.

    Both chapter and verse are stored as strings to handle special cases:
    - Chapter `-1` for introductions
    - Verse suffixes like `17a`
    - Verse ranges like `17-25`
    - Verse lists like `5,6,7`
    """
    def __init__(self, chapter: str, verse: str) -> None:
        """
        Create a new ChapterVerse reference.

        Args:
        chapter: The chapter string (e.g., "3", "-1" for intro)
        verse: The verse string (e.g., "16", "17a", "17-25")
        """

    def __getnewargs__(self) -> tuple[str, str]: ...
    @staticmethod
    def intro(verse_line: int) -> t.Self:
        """Create an introduction reference (chapter -1)."""

    @staticmethod
    def chapter_intro(chapter: str) -> t.Self:
        """Create a chapter introduction reference (verse 0)."""

    @property
    def chapter(self) -> str:
        """Get the chapter string."""

    @property
    def verse(self) -> str:
        """Get the verse string."""

    def chapter_int(self) -> int:
        """Get the leading integer from the chapter."""

    def verse_int(self) -> int:
        """Get the leading integer from the verse."""

    def is_intro(self) -> bool:
        """Check if this is an introduction reference (chapter -1)."""

    def is_chapter_intro(self) -> bool:
        """Check if this is a chapter introduction (verse 0)."""

    def is_verse_range(self) -> bool:
        """Check if the verse contains a range (e.g., "17-25")."""

    def is_verse_list(self) -> bool:
        """Check if the verse contains a list (e.g., "5,6,7")."""

    def has_verse_suffix(self) -> bool:
        """Check if the verse has a suffix (e.g., "17a")."""

    def parse_verse_range(self) -> tuple[int, int] | None:
        """Parse a verse range into (start, end) integers."""

    def contains_verse(self, verse_num: int) -> bool:
        """Check if this reference contains the given verse number."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: ChapterVerse) -> bool: ...
    def __hash__(self) -> int: ...

@t.final
class InternalBibleEntry:
    """
    A single line/entry in the internal Bible format.

    Backward-compatible with the Python InternalBibleEntry class.

    Constructor accepts either:
    - Full 6-arg form: (marker, originalMarker, adjustedText, cleanText, extras, originalText)
    - Simple 2-arg form: (marker, cleanText) — creates entry with all text fields set to cleanText

    Supports both snake_case properties and camelCase getter methods.
    """
    def __init__(
        self,
        marker: str,
        original_marker: str | None,
        adjusted_text: str | None = None,
        clean_text: str | None = None,
        extras: InternalBibleExtraList | None = None,
        original_text: str | None = None,
    ) -> None:
        """
        Create a new InternalBibleEntry.

        Matches the Python constructor signature:
        InternalBibleEntry(marker, originalMarker, adjustedText, cleanText, extras, originalText)

        For end markers / added nesting markers, originalMarker through originalText should be None.
        """

    def __getnewargs__(
        self,
    ) -> tuple[
        str,
        str | None,
        str | None,
        str | None,
        InternalBibleExtraList | None,
        str | None,
    ]: ...
    @property
    def marker(self) -> str:
        """Get the (adjusted) marker."""

    @property
    def originalMarker(self) -> str | None:
        """Get the original marker before adjustment."""

    @property
    def adjustedText(self) -> str | None:
        """Get the adjusted text (notes removed, formatting retained)."""

    @property
    def cleanText(self) -> str:
        """Get the clean text (notes and formatting removed)."""

    @property
    def extras(self) -> InternalBibleExtraList | None:
        """Get the extras (footnotes, cross-refs, etc.)."""

    @property
    def originalText(self) -> str | None:
        """Get the original text (full USFM)."""

    def getMarker(self) -> str:
        """Get the marker (Python compat)."""

    def getOriginalMarker(self) -> str | None:
        """Get the original marker (Python compat)."""

    def getAdjustedText(self) -> str | None:
        """Get the adjusted text (Python compat)."""

    def getText(self) -> str | None:
        """Get the adjusted text — alias (Python compat)."""

    def getCleanText(self, remove_esfm_underlines: bool = False) -> str:
        """Get the clean text, optionally removing ESFM underlines (Python compat)."""

    def getExtras(self) -> InternalBibleExtraList | None:
        """Get the extras (Python compat)."""

    def getOriginalText(self) -> str | None:
        """Get the original text (Python compat)."""

    def getFullText(self) -> str | None:
        """Get the full text — returns originalText (Python compat)."""

    def setCleanText(self, new_value: str) -> None:
        """
        Set the clean text (also sets adjusted and original text).
        Only works when extras is None.
        """

    def is_end_marker(self) -> bool:
        """Check if this is an end marker."""

    def has_extras(self) -> bool:
        """Check if this entry has extras (footnotes, cross-refs)."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> t.Any: ...
    def __eq__(self, other: InternalBibleEntry) -> bool: ...
    def __ne__(self, other: InternalBibleEntry) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

@t.final
class InternalBibleEntryList:
    """
    A list of Bible entries.

    This represents the processed lines of a Bible book or a slice of entries.
    Backward-compatible with the Python InternalBibleEntryList class.
    """
    def __init__(self, initial_data: t.Any | None = None) -> None:
        """Create a new entry list, optionally from existing data."""

    def __len__(self) -> int:
        """Get the number of entries."""

    def is_empty(self) -> bool:
        """Check if the list is empty."""

    def __getitem__(self, index: t.Any) -> t.Any:
        """Get an entry by index. Supports negative indexing and slicing."""

    def __iter__(self) -> PyInternalBibleEntryListIter:
        """Iterate over entries."""

    def __bool__(self) -> bool: ...
    def append(self, entry: InternalBibleEntry) -> None:
        """Add an entry to the list."""

    def pop(self) -> InternalBibleEntry | None:
        """Remove and return the last entry."""

    def extend(self, other: InternalBibleEntryList) -> None:
        """Extend with another entry list."""

    def __add__(self, other: InternalBibleEntryList) -> t.Self:
        """Support the + operator to combine lists (Python compat)."""

    def contains(self, search_marker: str, max_lines: int | None = None) -> int | None:
        """Search for the first entry with the given marker (Python compat: `contains`)."""

    def find_marker(self, marker: str, max_lines: int | None = None) -> int | None:
        """Find the first entry with the given marker (alias)."""

    def slice(self, start: int, end: int) -> t.Self:
        """Get a slice of entries."""

    def to_list(self) -> list[tuple[str, str]]:
        """Get all entries as a list of tuples (marker, clean_text)."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getstate__(self) -> t.Any: ...
    def __setstate__(self, state: t.Any) -> None: ...

@t.final
class PyInternalBibleEntryListIter:
    """Iterator for PyInternalBibleEntryList."""
    def __iter__(self) -> t.Self: ...
    def __next__(self) -> InternalBibleEntry | None: ...

@t.final
class CVIndexEntry:
    """
    An entry in the CV index, representing a single Chapter:Verse reference.

    Each entry stores:
    - entryIndex: The index into the entry list where this CV starts
    - entryCount: The count of entries for this CV
    - context: The context markers that were open at this point

    Supports both snake_case properties and camelCase getter methods.
    """
    def __init__(
        self, entry_index: int, entry_count: int, context: list[str] | None = None
    ) -> None:
        """
        Create a new CV index entry.

        Args:
        entry_index: The starting index into the entry list
        entry_count: Number of entries for this C:V
        context: Optional list of context markers
        """

    def __getnewargs__(self) -> tuple[int, int, list[str] | None]: ...
    @property
    def entryIndex(self) -> int:
        """Get the starting entry index."""

    @property
    def entryCount(self) -> int:
        """Get the entry count for this C:V."""

    def next_entry_index(self) -> int:
        """Get the index one past the last entry for this C:V."""

    @property
    def context(self) -> list[str]:
        """Get the context markers."""

    def getEntryIndex(self) -> int:
        """Get the entry index (Python compat)."""

    def getNextEntryIndex(self) -> int:
        """Get the next entry index (Python compat)."""

    def getEntryCount(self) -> int:
        """Get the entry count (Python compat)."""

    def getContextList(self) -> list[str]:
        """Get the context list (Python compat)."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> t.Any: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

@t.final
class InternalBibleBookCVIndex:
    """
    Index for fast Chapter:Verse lookup in a Bible book.

    The index maps (Chapter, Verse) references to entry ranges.
    Accepts both (str, str) tuples and ChapterVerse objects for keys.

    Special cases:
    - Chapter `-1`: Book introduction
    - Verse `0`: Chapter introduction / section headings before first verse
    - Verse ranges: e.g., `17-25` for bridged verses
    - Verse lists: e.g., `5,6,7` for multiple verses in one entry
    - Verse suffixes: e.g., `17a`, `17b`
    """
    def __init__(self, work_name: str, bos_book_code: str) -> None:
        """
        Create a new empty CV index.

        Args:
        work_name: Name of the work/Bible (e.g., "ESV", "KJV")
        bos_book_code: Three-letter book code (e.g., "GEN", "MAT")
        """

    def __getnewargs__(self) -> tuple[str, str]: ...
    @property
    def work_name(self) -> str:
        """Get the work name."""

    @property
    def bos_book_code(self) -> str:
        """Get the book code."""

    @property
    def is_indexed(self) -> bool:
        """Check if the index has been built."""

    @property
    def entries(self) -> InternalBibleEntryList:
        """Get direct access to the underlying entries."""

    @property
    def workName(self) -> str:
        """Get the work name (Python compat)."""

    @property
    def BBB(self) -> str:
        """Get the book code (Python compat: BBB)."""

    @property
    def _indexedFlag(self) -> bool:
        """Check if indexed (Python compat: _indexedFlag)."""

    @property
    def givenBibleEntries(self) -> InternalBibleEntryList:
        """Get the entries list (Python compat: givenBibleEntries)."""

    def __len__(self) -> int:
        """Get the number of CV entries in the index."""

    def is_empty(self) -> bool:
        """Check if the index is empty."""

    def __contains__(self, key: t.Any) -> bool:
        """Check if a (C,V) tuple or ChapterVerse exists in the index."""

    def __getitem__(self, key: tuple[str, str]) -> CVIndexEntry:
        """Get a CVIndexEntry for a (C,V) tuple key."""

    def __iter__(self) -> PyCVIndexIter:
        """Iterate over (C,V) tuples."""

    def items(self) -> list[tuple[tuple[str, str], CVIndexEntry]]:
        """Iterate over ((C,V), CVIndexEntry) pairs."""

    def chapters(self) -> list[str]:
        """Get all chapters in the index."""

    def contains(self, key: t.Any) -> bool:
        """Check if a CV exists in the index (accepts tuple or ChapterVerse)."""

    def get_verse_entries(
        self, cv: ChapterVerse, strict: bool = True
    ) -> InternalBibleEntryList:
        """Get verse entries using a ChapterVerse object."""

    def get_verse_entries_with_context(
        self, cv: ChapterVerse, strict: bool = True, complete: bool = False
    ) -> tuple[InternalBibleEntryList, list[str]]:
        """Get verse entries with context using a ChapterVerse object."""

    def get_chapter_entries(self, chapter: str) -> InternalBibleEntryList:
        """Get all entries for a chapter (snake_case)."""

    def get_index_entry(self, cv: ChapterVerse) -> CVIndexEntry | None:
        """Get the CV index entry for a specific ChapterVerse reference."""

    def build(self, entries: InternalBibleEntryList) -> None:
        """Build the CV index from processed entries (snake_case)."""

    def validate(self) -> list[str]:
        """Validate the index structure."""

    def makeBookCVIndex(self, entries: InternalBibleEntryList) -> None:
        """Build the CV index from processed entries (Python compat)."""

    def getVerseEntries(
        self, cv_key: tuple[str, str], strict: bool = True
    ) -> InternalBibleEntryList:
        """Get verse entries for a (C,V) tuple key."""

    def getVerseEntriesWithContext(
        self, cv_key: tuple[str, str], strict: bool = False, complete: bool = False
    ) -> tuple[InternalBibleEntryList, list[str]]:
        """Get verse entries with context for a (C,V) tuple key."""

    def getChapterEntries(self, chapter: str) -> InternalBibleEntryList:
        """Get all entries for a chapter (Python compat)."""

    def getChapterEntriesWithContext(
        self, chapter: str
    ) -> tuple[InternalBibleEntryList, list[str]]:
        """Get chapter entries with context markers (Python compat)."""

    def getEntries(self) -> InternalBibleEntryList:
        """Get all entries (Python compat alias for entries property)."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getstate__(self) -> t.Any: ...
    def __setstate__(self, state: t.Any) -> None: ...

@t.final
class PyCVIndexIter:
    """Iterator for PyInternalBibleBookCVIndex, yields (C, V) string tuples."""
    def __iter__(self) -> t.Self: ...
    def __next__(self) -> tuple[str, str] | None: ...

@t.final
class InternalBibleBookSectionIndexEntry:
    """
    A section index entry for a Bible book.

    Each entry represents a section boundary and contains:
    - endC, endV: End chapter and verse (inclusive)
    - startIx, endIx: Start and end entry indices
    - reasonMarker: The marker that started this section (e.g., "s1", "c")
    - sectionName: The section heading text
    - contextList: Context markers active at this point
    """
    def __init__(
        self,
        end_c: str,
        end_v: str,
        start_ix: int,
        end_ix: int,
        reason_marker: str,
        section_name: str,
        context_list: list[str] | None = None,
    ) -> None:
        """
        Create a new section index entry.

        Args:
        endC: End chapter number string
        endV: End verse number string
        startIx: Start entry index
        endIx: End entry index (inclusive)
        reasonMarker: Marker that started this section
        sectionName: Section heading text
        contextList: Optional list of context markers
        """

    def __getnewargs__(
        self,
    ) -> tuple[str, str, int, int, str, str, list[str] | None]: ...
    @property
    def endC(self) -> str: ...
    @property
    def endV(self) -> str: ...
    @property
    def startIx(self) -> int: ...
    @property
    def endIx(self) -> int: ...
    @property
    def reasonMarker(self) -> str: ...
    @property
    def sectionName(self) -> str: ...
    @property
    def contextList(self) -> list[str]: ...
    def getEndCV(self) -> tuple[str, str]:
        """Get end chapter and verse as (str, str) tuple."""

    def getStartIndex(self) -> int:
        """Get start entry index."""

    def getEndIndex(self) -> int:
        """Get end entry index (inclusive)."""

    def getEntryCount(self) -> int:
        """Get entry count (endIx + 1 - startIx)."""

    def getContextList(self) -> list[str]:
        """Get context markers list."""

    def getSectionNameReason(self) -> tuple[str, str]:
        """Get section name and reason marker as (str, str) tuple."""

    def __len__(self) -> int: ...
    def __getitem__(self, key_index: int) -> t.Any: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

@t.final
class InternalBibleBookSectionIndex:
    """
    Section index for a Bible book.

    Maps section starting points (C:V) to section entries.
    Accepts (str, str) tuples for keys.
    """
    def __init__(self, work_name: str, bos_book_code: str) -> None:
        """Create a new empty section index."""

    def __getnewargs__(self) -> tuple[str, str]: ...
    @property
    def workName(self) -> str: ...
    @property
    def BBB(self) -> str: ...
    @property
    def _indexedFlag(self) -> bool: ...
    @property
    def givenBibleEntries(self) -> InternalBibleEntryList: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: tuple[str, str]) -> bool: ...
    def __getitem__(
        self, key: tuple[str, str]
    ) -> InternalBibleBookSectionIndexEntry: ...
    def __iter__(self) -> PySectionIndexIter: ...
    def items(
        self,
    ) -> list[tuple[tuple[str, str], InternalBibleBookSectionIndexEntry]]: ...
    def makeBookSectionIndex(self, entries: InternalBibleEntryList) -> None:
        """Build the section index from processed entries."""

    def getSectionEntries(self, key: tuple[str, str]) -> InternalBibleEntryList:
        """Get entries for a section by (C,V) key."""

    def getSectionEntriesWithContext(
        self, key: tuple[str, str]
    ) -> tuple[InternalBibleEntryList, list[str]]:
        """Get section entries with context markers."""

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getstate__(self) -> t.Any: ...
    def __setstate__(self, state: t.Any) -> None: ...

@t.final
class PySectionIndexIter:
    """Iterator for PyInternalBibleBookSectionIndex, yields (C, V) string tuples."""
    def __iter__(self) -> t.Self: ...
    def __next__(self) -> tuple[str, str] | None: ...

@t.final
class ObjectType: ...

@t.final
class ProcessLinesOptions:
    @property
    def replace_angle_brackets(self) -> bool: ...
    @replace_angle_brackets.setter
    def replace_angle_brackets(self, value: bool) -> None: ...
    @property
    def replace_straight_double_quotes(self) -> bool: ...
    @replace_straight_double_quotes.setter
    def replace_straight_double_quotes(self, value: bool) -> None: ...
    @property
    def strict_checking(self) -> bool: ...
    @strict_checking.setter
    def strict_checking(self, value: bool) -> None: ...
    @property
    def object_type(self) -> ObjectType: ...
    @object_type.setter
    def object_type(self, value: ObjectType) -> None: ...
    def __init__(
        self,
        replace_angle_brackets: bool = True,
        replace_straight_double_quotes: bool = False,
        strict_checking: bool = False,
        object_type: ObjectType | None = None,
    ) -> None: ...
