# /home/robert/Programming/WebDevelopment/OpenScriptures/BibleOrgSys/DataFiles/PunctuationSystems/../DerivedFiles/BiblePunctuationSystems_Tables.py
#
# This UTF-8 file was automatically generated by BiblePunctuationSystems.py V0.44 on 2020-01-15 08:56:53.233048
#
#   3 BiblePunctuationSystem loaded from the original XML files.
#

bookDataDict = {
  # Key is versificationSystemName
  # Fields are omittedVersesSystem

  "Matigsalug": {
    # Key is referenceAbbreviation
    # Fields are: id
    'sentenceCapitalisation': 'Y',
    'properNounCapitalisation': 'Y',
    'statementTerminator': '.',
    'questionTerminator': '?',
    'exclamationTerminator': '!',
    'commaPauseCharacter': ',',
    'startQuoteLevel1': '“',
    'endQuoteLevel1': '”',
    'startQuoteLevel2': '‘',
    'endQuoteLevel2': '’',
    'startQuoteLevel3': '“',
    'endQuoteLevel3': '”',
    'startQuoteLevel4': '',
    'endQuoteLevel4': '',
    'booknameCase': 'ME',
    'booknameLength': '3',
    'punctuationAfterBookAbbreviation': '',
    'bookChapterSeparator': ' ',
    'spaceAllowedAfterBCS': 'E',
    'chapterVerseSeparator': ':',
    'verseSeparator': ',',
    'bookBridgeCharacter': '–',
    'chapterBridgeCharacter': '–',
    'verseBridgeCharacter': '-',
    'chapterSeparator': ';',
    'bookSeparator': ';',
    'allowedVerseSuffixes': 'ab',
  }, # end of Matigsalug (27 entries)

  "English": {
    # Key is referenceAbbreviation
    # Fields are: id
    'sentenceCapitalisation': 'Y',
    'properNounCapitalisation': 'Y',
    'statementTerminator': '.',
    'questionTerminator': '?',
    'exclamationTerminator': '!',
    'commaPauseCharacter': ',',
    'startQuoteLevel1': '“',
    'endQuoteLevel1': '”',
    'startQuoteLevel2': '‘',
    'endQuoteLevel2': '’',
    'startQuoteLevel3': '“',
    'endQuoteLevel3': '”',
    'startQuoteLevel4': '',
    'endQuoteLevel4': '',
    'booknameCase': 'ME',
    'booknameLength': '3',
    'punctuationAfterBookAbbreviation': '.',
    'bookChapterSeparator': ' ',
    'spaceAllowedAfterBCS': 'E',
    'chapterVerseSeparator': ':',
    'verseSeparator': ',',
    'bookBridgeCharacter': '-',
    'chapterBridgeCharacter': '-',
    'verseBridgeCharacter': '-',
    'chapterSeparator': ';',
    'bookSeparator': ';',
    'allowedVerseSuffixes': 'abcdef',
  }, # end of English (27 entries)

  "English_brief": {
    # Key is referenceAbbreviation
    # Fields are: id
    'sentenceCapitalisation': 'Y',
    'properNounCapitalisation': 'Y',
    'statementTerminator': '.',
    'questionTerminator': '?',
    'exclamationTerminator': '!',
    'commaPauseCharacter': ',',
    'startQuoteLevel1': '“',
    'endQuoteLevel1': '”',
    'startQuoteLevel2': '‘',
    'endQuoteLevel2': '’',
    'startQuoteLevel3': '“',
    'endQuoteLevel3': '”',
    'startQuoteLevel4': '',
    'endQuoteLevel4': '',
    'booknameCase': 'ME',
    'booknameLength': '3',
    'punctuationAfterBookAbbreviation': '',
    'bookChapterSeparator': ' ',
    'spaceAllowedAfterBCS': 'E',
    'chapterVerseSeparator': ':',
    'verseSeparator': ',',
    'bookBridgeCharacter': '-',
    'chapterBridgeCharacter': '-',
    'verseBridgeCharacter': '-',
    'chapterSeparator': ';',
    'bookSeparator': ';',
    'allowedVerseSuffixes': 'abcdef',
  }, # end of English_brief (27 entries)

} # end of bookDataDict (3 systems)



# end of BiblePunctuationSystems_Tables.py