//./DataFiles/VersificationSystems/../DerivedFiles/BibleVersificationSystems_Tables.c
//
// This UTF-8 file was automatically generated by BibleVersificationSystems.py V0.50 on 2013-05-28 21:23:45.123460
//
//  26BibleVersificationSystem loaded from the original XML file.
//

#include "BibleVersificationSystems_Tables.h"

