# /mnt/SSD/Programming/WebDevelopment/OpenScriptures/BibleOrgSys/DataFiles/DerivedFiles/BibleBooksCodes_Tables.py
#
# This UTF-8 file was automatically generated by BibleBooksCodes.py V0.79 on 2019-12-29 21:51:28.272815
#
# Bible books codes list data
#  Version: 0.79
#  Date: 2019-09-06
#
#   240 BibleBooksCodes loaded from the original XML file.
#

