# ./DataFiles/DerivedFiles/BibleBooksCodes_Tables.py
#
# This UTF-8 file was automatically generated by BibleBooksCodes.py V0.68 on 2013-06-14 20:06:57.557608
#
# Bible books codes list data
#  Version: 0.69
#  Date: 2013-05-20
#
#   230 BibleBooksCodes loaded from the original XML file.
#

