// ./DataFiles/DerivedFiles/BibleBooksCodes_Tables.h
//
// This UTF-8 file was automatically generated by BibleBooksCodes.py V0.77 on 2015-09-25 14:43:44.289838
//
// Bible books codes list data
//  Version: 0.76
//  Date: 2015-05-21
//

#ifndef BIBLEBOOKSCODES_Tables_h
#define BIBLEBOOKSCODES_Tables_h

typedef struct UnboundCodeDictEntryStruct {
    const unsigned char UnboundCodeString[3+1];
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
    const unsigned char USFMAbbreviation[3+1];
} UnboundCodeDictEntry;

typedef struct EnglishNameDictEntryStruct {
    const unsigned char* nameEnglish;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} EnglishNameDictEntry;

typedef struct CCELDictEntryStruct {
    const unsigned char* CCELNumberString;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} CCELDictEntry;

