# ./DataFiles/PunctuationSystems/../DerivedFiles/BiblePunctuationSystems_Tables.py
#
# This UTF-8 file was automatically generated by BiblePunctuationSystems.py V0.43 on 2013-08-02 04:10:10.259375
#
#   3 BiblePunctuationSystem loaded from the original XML files.
#

from collections import OrderedDict


bookDataDict = {
  # Key is versificationSystemName
  # Fields are omittedVersesSystem

  "English": {
    # Key is referenceAbbreviation
    # Fields are: id
    'commaPauseCharacter': ',',
    'chapterSeparator': ';',
    'chapterBridgeCharacter': '-',
    'sentenceCapitalisation': 'Y',
    'exclamationTerminator': '!',
    'startQuoteLevel1': '“',
    'bookBridgeCharacter': '-',
    'startQuoteLevel3': '“',
    'startQuoteLevel2': '‘',
    'startQuoteLevel4': '',
    'chapterVerseSeparator': ':',
    'spaceAllowedAfterBCS': 'E',
    'booknameCase': 'ME',
    'verseBridgeCharacter': '-',
    'endQuoteLevel4': '',
    'endQuoteLevel2': '’',
    'endQuoteLevel3': '”',
    'bookSeparator': ';',
    'endQuoteLevel1': '”',
    'statementTerminator': '.',
    'punctuationAfterBookAbbreviation': '.',
    'allowedVerseSuffixes': 'abcdef',
    'bookChapterSeparator': ' ',
    'questionTerminator': '?',
    'booknameLength': '3',
    'properNounCapitalisation': 'Y',
    'verseSeparator': ',',
  }, # end of English (27 entries)

  "Matigsalug": {
    # Key is referenceAbbreviation
    # Fields are: id
    'commaPauseCharacter': ',',
    'chapterSeparator': ';',
    'chapterBridgeCharacter': '–',
    'sentenceCapitalisation': 'Y',
    'exclamationTerminator': '!',
    'startQuoteLevel1': '“',
    'bookBridgeCharacter': '–',
    'startQuoteLevel3': '“',
    'startQuoteLevel2': '‘',
    'startQuoteLevel4': '',
    'chapterVerseSeparator': ':',
    'spaceAllowedAfterBCS': 'E',
    'booknameCase': 'ME',
    'verseBridgeCharacter': '-',
    'endQuoteLevel4': '',
    'endQuoteLevel2': '’',
    'endQuoteLevel3': '”',
    'bookSeparator': ';',
    'endQuoteLevel1': '”',
    'statementTerminator': '.',
    'punctuationAfterBookAbbreviation': '',
    'allowedVerseSuffixes': 'ab',
    'bookChapterSeparator': ' ',
    'questionTerminator': '?',
    'booknameLength': '3',
    'properNounCapitalisation': 'Y',
    'verseSeparator': ',',
  }, # end of Matigsalug (27 entries)

  "English_brief": {
    # Key is referenceAbbreviation
    # Fields are: id
    'commaPauseCharacter': ',',
    'chapterSeparator': ';',
    'chapterBridgeCharacter': '-',
    'sentenceCapitalisation': 'Y',
    'exclamationTerminator': '!',
    'startQuoteLevel1': '“',
    'bookBridgeCharacter': '-',
    'startQuoteLevel3': '“',
    'startQuoteLevel2': '‘',
    'startQuoteLevel4': '',
    'chapterVerseSeparator': ':',
    'spaceAllowedAfterBCS': 'E',
    'booknameCase': 'ME',
    'verseBridgeCharacter': '-',
    'endQuoteLevel4': '',
    'endQuoteLevel2': '’',
    'endQuoteLevel3': '”',
    'bookSeparator': ';',
    'endQuoteLevel1': '”',
    'statementTerminator': '.',
    'punctuationAfterBookAbbreviation': '',
    'allowedVerseSuffixes': 'abcdef',
    'bookChapterSeparator': ' ',
    'questionTerminator': '?',
    'booknameLength': '3',
    'properNounCapitalisation': 'Y',
    'verseSeparator': ',',
  }, # end of English_brief (27 entries)

} # end of bookDataDict (3 systems)



# end of BiblePunctuationSystems_Tables.py