// ./DataFiles/DerivedFiles/BibleBooksCodes_Tables.c
//
// This UTF-8 file was automatically generated by BibleBooksCodes.py V0.68 on 2013-07-16 18:19:10.179704
//
// Bible books codes list data
//  Version: 0.69
//  Date: 2013-05-20
//
//   230 BibleBooksCodes loaded from the original XML file.
//

#include "BibleBooksCodes_Tables.h"

const static OSISAbbreviationDictEntry
 OSISAbbreviationDict[86] = {
  // Fields (3) are const unsigned char* OSISAbbreviation; const int referenceNumber; const unsigned char referenceAbbreviation[3+1];
  // Sorted by OSISAbbreviation
  {"1CHR", 13, "CH1"},
  {"1COR", 46, "CO1"},
  {"1ESD", 90, "GES"},
  {"1JOHN", 62, "JN1"},
  {"1KGS", 11, "KI1"},
  {"1MACC", 111, "MA1"},
  {"1PET", 60, "PE1"},
  {"1SAM", 9, "SA1"},
  {"1THESS", 52, "TH1"},
  {"1TIM", 54, "TI1"},
  {"2CHR", 14, "CH2"},
  {"2COR", 47, "CO2"},
  {"2ESD", 91, "LES"},
  {"2JOHN", 63, "JN2"},
  {"2KGS", 12, "KI2"},
  {"2MACC", 112, "MA2"},
  {"2PET", 61, "PE2"},
  {"2SAM", 10, "SA2"},
  {"2THESS", 53, "TH2"},
  {"2TIM", 55, "TI2"},
  {"3JOHN", 64, "JN3"},
  {"3MACC", 113, "MA3"},
  {"4MACC", 114, "MA4"},
  {"ACTS", 44, "ACT"},
