// ./DataFiles/DerivedFiles/BibleBooksCodes_Tables.h
//
// This UTF-8 file was automatically generated by BibleBooksCodes.py V0.68 on 2013-07-03 18:07:19.865032
//
// Bible books codes list data
//  Version: 0.69
//  Date: 2013-05-20
//

#ifndef BIBLEBOOKSCODES_Tables_h
#define BIBLEBOOKSCODES_Tables_h

typedef struct CCELDictEntryStruct {
    const unsigned char* CCELNumberString;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} CCELDictEntry;

