//./DataFiles/VersificationSystems/../DerivedFiles/BibleVersificationSystems_Tables.c
//
// This UTF-8 file was automatically generated by BibleVersificationSystems.py V0.50 on 2013-07-25 22:11:04.748154
//
//  26BibleVersificationSystem loaded from the original XML file.
//

#include "BibleVersificationSystems_Tables.h"

