//./DataFiles/VersificationSystems/../DerivedFiles/BibleVersificationSystems_Tables.h
//
// This UTF-8 file was automatically generated by BibleVersificationSystems.py V0.50 on 2013-07-25 22:11:04.748154
//

#ifndefBIBLEVERSIFICATIONSYSTEMS_Tables_h
#defineBIBLEVERSIFICATIONSYSTEMS_Tables_h

