// ./DataFiles/DerivedFiles/BibleBooksCodes_Tables.c
//
// This UTF-8 file was automatically generated by BibleBooksCodes.py V0.68 on 2013-04-09 14:28:02.460317
//
// Bible books codes list data
//  Version: 0.68
//  Date: 2013-04-08
//
//   230 BibleBooksCodes loaded from the original XML file.
//

#include "BibleBooksCodes_Tables.h"

const static referenceAbbreviationDictEntry
 referenceAbbreviationDict[230] = {
  // Fields (16) are const unsigned char referenceAbbreviation[3+1]; const unsigned char* ByzantineAbbreviation; const unsigned char* CCELNumberString; const int referenceNumber; const unsigned char* NETBibleAbbreviation; const unsigned char* OSISAbbreviation; const unsigned char USFMAbbreviation[3+1]; const unsigned char USFMNumberString[2+1]; const unsigned char* SBLAbbreviation; const unsigned char* SwordAbbreviation; const unsigned char* nameEnglish; const unsigned char* numExpectedChapters; const unsigned char* possibleAlternativeBooks;
  // Sorted by referenceAbbreviation
  {"ABL", "", "", "", "", "", "", "", "", "", "", "", "Aristobulus", "", "", 193},
  {"ACK", "", "", "", "", "", "", "", "", "", "", "", "Acknowledgements", "", "", 710},
