//./DataFiles/VersificationSystems/../DerivedFiles/BibleVersificationSystems_Tables.h
//
// This UTF-8 file was automatically generated by BibleVersificationSystems.py V0.50 on 2013-05-29 13:48:41.572253
//

#ifndefBIBLEVERSIFICATIONSYSTEMS_Tables_h
#defineBIBLEVERSIFICATIONSYSTEMS_Tables_h

