// ./DataFiles/DerivedFiles/BibleBooksCodes_Tables.c
//
// This UTF-8 file was automatically generated by BibleBooksCodes.py V0.68 on 2013-06-23 09:11:07.366906
//
// Bible books codes list data
//  Version: 0.69
//  Date: 2013-05-20
//
//   230 BibleBooksCodes loaded from the original XML file.
//

#include "BibleBooksCodes_Tables.h"

const static referenceNumberDictEntry
 referenceNumberDict[230] = {
  // Fields (16) are const int referenceNumber; const unsigned char* ByzantineAbbreviation; const unsigned char* CCELNumberString; const unsigned char* NETBibleAbbreviation; const unsigned char* OSISAbbreviation; const unsigned char USFMAbbreviation[3+1]; const unsigned char USFMNumberString[2+1]; const unsigned char* SBLAbbreviation; const unsigned char* SwordAbbreviation; const unsigned char* nameEnglish; const unsigned char* numExpectedChapters; const unsigned char* possibleAlternativeBooks; const unsigned char referenceAbbreviation[3+1];
  // Sorted by referenceNumber (integer 1..255)
  {1, "1", "", "1", "Gen", "Gen", "Gen", "Gen", "Gen", "01", "001", "01O", "Genesis / 1 Moses", "50", "", "GEN"},
  {2, "2", "", "2", "Exo", "Exod", "Exod", "Exod", "Exo", "02", "002", "02O", "Exodus / 2 Moses", "40", "", "EXO"},
  {3, "3", "", "3", "Lev", "Lev", "Lev", "Lev", "Lev", "03", "003", "03O", "Leviticus / 3 Moses", "27", "", "LEV"},
  {4, "4", "", "4", "Num", "Num", "Num", "Num", "Num", "04", "004", "04O", "Numbers / 4 Moses", "36", "", "NUM"},
  {5, "5", "", "5", "Deu", "Deut", "Deut", "Deut", "Deu", "05", "005", "05O", "Deuteronomy / 5 Moses", "34", "", "DEU"},
