//./DataFiles/VersificationSystems/../DerivedFiles/BibleVersificationSystems_Tables.c
//
// This UTF-8 file was automatically generated by BibleVersificationSystems.py V0.50 on 2014-12-19 10:24:18.729517
//
//  26BibleVersificationSystem loaded from the original XML file.
//

#include "BibleVersificationSystems_Tables.h"

