# ./DataFiles/DerivedFiles/BibleBooksCodes_Tables.py
#
# This UTF-8 file was automatically generated by BibleBooksCodes.py V0.79 on 2018-02-10 16:08:57.969258
#
# Bible books codes list data
#  Version: 0.77
#  Date: 2017-01-03
#
#   238 BibleBooksCodes loaded from the original XML file.
#

