# ./DataFiles/DerivedFiles/USFMMarkers_Tables.py
#
# This UTF-8 file was automatically generated by USFMMarkers.py V0.54 on 2013-02-18 17:02:04.146146
#
# USFM 2.35 markers list data
#  Version: 0.55
#  Date: 2012-12-08
#
#   128 USFMMarkers loaded from the original XML file.
#

from collections import OrderedDict

conversionDict = {
  # Key is rawMarker
  # Fields (1) are: numberedMarker
  'h': 'h1',
  'ili': 'ili1',
  'imt': 'imt1',
  'imte': 'imte1',
  'io': 'io1',
  'iq': 'iq1',
  'is': 'is1',
  'li': 'li1',
  'ms': 'ms1',
  'mt': 'mt1',
  'mte': 'mte1',
  'ph': 'ph1',
  'pi': 'pi1',
  'q': 'q1',
  'qm': 'qm1',
  's': 's1',
  'tc': 'tc1',
  'tcr': 'tcr1',
  'th': 'th1',
  'thr': 'thr1',
}
# end of conversionDict (20 entries)

combinedMarkerDict = {
  # Key is marker
  # Fields (1) are: rawMarker
  'add': 'add',
  'b': 'b',
  'bd': 'bd',
  'bdit': 'bdit',
  'bk': 'bk',
  'c': 'c',
  'ca': 'ca',
  'cat': 'cat',
  'cd': 'cd',
  'cl': 'cl',
  'cls': 'cls',
  'cp': 'cp',
  'd': 'd',
  'dc': 'dc',
  'e': 'e',
  'ef': 'ef',
  'em': 'em',
  'esb': 'esb',
  'ex': 'ex',
  'f': 'f',
  'fdc': 'fdc',
  'fig': 'fig',
  'fk': 'fk',
  'fl': 'fl',
  'fm': 'fm',
  'fp': 'fp',
  'fq': 'fq',
  'fqa': 'fqa',
  'fr': 'fr',
  'fs': 'fs',
  'ft': 'ft',
  'fv': 'fv',
  'h': 'h',
  'h1': 'h',
  'h2': 'h',
  'h3': 'h',
  'ib': 'ib',
  'id': 'id',
  'ide': 'ide',
  'ie': 'ie',
  'iex': 'iex',
  'ili': 'ili',
  'ili1': 'ili',
  'ili2': 'ili',
  'ili3': 'ili',
  'im': 'im',
  'imi': 'imi',
  'imq': 'imq',
  'imt': 'imt',
  'imt1': 'imt',
  'imt2': 'imt',
  'imt3': 'imt',
  'imte': 'imte',
  'imte1': 'imte',
  'imte2': 'imte',
  'imte3': 'imte',
  'io': 'io',
  'io1': 'io',
  'io2': 'io',
  'io3': 'io',
  'ior': 'ior',
  'iot': 'iot',
  'ip': 'ip',
  'ipi': 'ipi',
  'ipq': 'ipq',
  'ipr': 'ipr',
  'iq': 'iq',
  'iq1': 'iq',
  'iq2': 'iq',
  'iq3': 'iq',
  'iqt': 'iqt',
  'is': 'is',
  'is1': 'is',
  'is2': 'is',
  'is3': 'is',
  'it': 'it',
  'k': 'k',
  'li': 'li',
  'li1': 'li',
  'li2': 'li',
  'li3': 'li',
  'lit': 'lit',
  'm': 'm',
  'mi': 'mi',
  'mr': 'mr',
  'ms': 'ms',
  'ms1': 'ms',
  'ms2': 'ms',
  'ms3': 'ms',
  'mt': 'mt',
  'mt1': 'mt',
  'mt2': 'mt',
  'mt3': 'mt',
  'mte': 'mte',
  'mte1': 'mte',
  'mte2': 'mte',
  'mte3': 'mte',
  'nb': 'nb',
  'nd': 'nd',
  'ndx': 'ndx',
  'no': 'no',
  'ord': 'ord',
  'p': 'p',
  'pb': 'pb',
  'pc': 'pc',
  'pde': 'pde',
  'pdi': 'pdi',
  'periph': 'periph',
  'ph': 'ph',
  'ph1': 'ph',
  'ph2': 'ph',
  'ph3': 'ph',
  'pi': 'pi',
  'pi1': 'pi',
  'pi2': 'pi',
  'pi3': 'pi',
  'pm': 'pm',
  'pmc': 'pmc',
  'pmo': 'pmo',
  'pmr': 'pmr',
  'pn': 'pn',
  'pr': 'pr',
  'pro': 'pro',
  'ps': 'ps',
  'q': 'q',
  'q1': 'q',
  'q2': 'q',
  'q3': 'q',
  'qa': 'qa',
  'qac': 'qac',
  'qc': 'qc',
  'qm': 'qm',
  'qm1': 'qm',
  'qm2': 'qm',
  'qm3': 'qm',
  'qr': 'qr',
  'qs': 'qs',
  'qt': 'qt',
  'r': 'r',
  'rem': 'rem',
  'rq': 'rq',
  's': 's',
  's1': 's',
  's2': 's',
  's3': 's',
  'sc': 'sc',
  'sig': 'sig',
  'sls': 'sls',
  'sp': 'sp',
  'sr': 'sr',
  'sts': 'sts',
  'tc': 'tc',
  'tc1': 'tc',
  'tc2': 'tc',
  'tc3': 'tc',
  'tcr': 'tcr',
  'tcr1': 'tcr',
  'tcr2': 'tcr',
  'tcr3': 'tcr',
  'th': 'th',
  'th1': 'th',
  'th2': 'th',
  'th3': 'th',
  'thr': 'thr',
  'thr1': 'thr',
  'thr2': 'thr',
  'thr3': 'thr',
  'tl': 'tl',
  'toc1': 'toc1',
  'toc2': 'toc2',
  'toc3': 'toc3',
  'tr': 'tr',
  'v': 'v',
  'va': 'va',
  'vp': 'vp',
  'w': 'w',
  'wg': 'wg',
  'wh': 'wh',
  'wj': 'wj',
  'wr': 'wr',
  'x': 'x',
  'xdc': 'xdc',
  'xk': 'xk',
  'xnt': 'xnt',
  'xo': 'xo',
  'xot': 'xot',
  'xq': 'xq',
  'xt': 'xt',
}
# end of combinedMarkerDict (188 entries)

newlineMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'ide', # 1
  'sts', # 2
  'rem', # 3
  'h', # 4
  'toc1', # 5
  'toc2', # 6
  'toc3', # 7
  'imt', # 8
  'is', # 9
  'ip', # 10
  'ipi', # 11
  'im', # 12
  'imi', # 13
  'ipq', # 14
  'imq', # 15
  'ipr', # 16
  'iq', # 17
  'ib', # 18
  'ili', # 19
  'iot', # 20
  'io', # 21
  'iex', # 22
  'imte', # 23
  'ie', # 24
  'mt', # 25
  'mte', # 26
  'ms', # 27
  'mr', # 28
  's', # 29
  'sr', # 30
  'r', # 31
  'd', # 32
  'sp', # 33
  'c', # 34
  'cl', # 35
  'cp', # 36
  'cd', # 37
  'v', # 38
  'p', # 39
  'm', # 40
  'pmo', # 41
  'pm', # 42
  'pmc', # 43
  'pmr', # 44
  'pi', # 45
  'mi', # 46
  'nb', # 47
  'cls', # 48
  'li', # 49
  'pc', # 50
  'pr', # 51
  'ph', # 52
  'b', # 53
  'q', # 54
  'qr', # 55
  'qc', # 56
  'qa', # 57
  'qm', # 58
  'tr', # 59
  'th', # 60
  'thr', # 61
  'lit', # 62
  'pb', # 63
  'periph', # 64
  'esb', # 65
  'pdi', # 66
  'pde', # 67
  'ps', # 68
], # end of newlineMarkersList (69 entries)

combinedInternalMarkersList = [
    # Fields (1) are: rawMarker
  'tc1', # 0
  'tc2', # 1
  'tc3', # 2
  'tcr1', # 3
  'tcr2', # 4
  'tcr3', # 5
], # end of combinedInternalMarkersList (6 entries)

numberedNewlineMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'ide', # 1
  'sts', # 2
  'rem', # 3
  'h1', # 4
  'h2', # 5
  'h3', # 6
  'toc1', # 7
  'toc2', # 8
  'toc3', # 9
  'imt1', # 10
  'imt2', # 11
  'imt3', # 12
  'is1', # 13
  'is2', # 14
  'is3', # 15
  'ip', # 16
  'ipi', # 17
  'im', # 18
  'imi', # 19
  'ipq', # 20
  'imq', # 21
  'ipr', # 22
  'iq1', # 23
  'iq2', # 24
  'iq3', # 25
  'ib', # 26
  'ili1', # 27
  'ili2', # 28
  'ili3', # 29
  'iot', # 30
  'io1', # 31
  'io2', # 32
  'io3', # 33
  'iex', # 34
  'imte1', # 35
  'imte2', # 36
  'imte3', # 37
  'ie', # 38
  'mt1', # 39
  'mt2', # 40
  'mt3', # 41
  'mte1', # 42
  'mte2', # 43
  'mte3', # 44
  'ms1', # 45
  'ms2', # 46
  'ms3', # 47
  'mr', # 48
  's1', # 49
  's2', # 50
  's3', # 51
  'sr', # 52
  'r', # 53
  'd', # 54
  'sp', # 55
  'c', # 56
  'cl', # 57
  'cp', # 58
  'cd', # 59
  'v', # 60
  'p', # 61
  'm', # 62
  'pmo', # 63
  'pm', # 64
  'pmc', # 65
  'pmr', # 66
  'pi1', # 67
  'pi2', # 68
  'pi3', # 69
  'mi', # 70
  'nb', # 71
  'cls', # 72
  'li1', # 73
  'li2', # 74
  'li3', # 75
  'pc', # 76
  'pr', # 77
  'ph1', # 78
  'ph2', # 79
  'ph3', # 80
  'b', # 81
  'q1', # 82
  'q2', # 83
  'q3', # 84
  'qr', # 85
  'qc', # 86
  'qa', # 87
  'qm1', # 88
  'qm2', # 89
  'qm3', # 90
  'tr', # 91
  'th1', # 92
  'th2', # 93
  'th3', # 94
  'thr1', # 95
  'thr2', # 96
  'thr3', # 97
  'lit', # 98
  'pb', # 99
  'periph', # 100
  'esb', # 101
  'pdi', # 102
  'pde', # 103
  'ps', # 104
], # end of numberedNewlineMarkersList (105 entries)

rawMarkerDict = OrderedDict([
    # Key is rawMarker (in the original XML order)
    # Fields (11) are: specified
  ('id', {'occursIn': 'Header', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': True, 'description': 'This is the initial USFM marker in any scripture text file', 'nameEnglish': 'File identification', 'level': 'Newline', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ide', {'occursIn': 'Header', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'This marker should be used to specify the character encoding of the text within the file', 'nameEnglish': 'An optional character encoding specification', 'level': 'Newline', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'No'}),
  ('sts', {'occursIn': 'Header', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'The contents of the status marker can be defined by the downstream system being used to track project status', 'nameEnglish': 'Project status tracking', 'level': 'Newline', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'No'}),
  ('rem', {'occursIn': 'Header', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Used for adding brief comments by a translator, consultant, or support person', 'nameEnglish': 'Remark/Comment', 'level': 'Newline', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'No'}),
  ('h', {'occursIn': 'Header', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': True, 'description': None, 'nameEnglish': 'Running header text', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('toc1', {'occursIn': 'Header', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Not for use directly within the front matter (FRT) peripheral file', 'nameEnglish': 'Long table of contents text', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('toc2', {'occursIn': 'Header', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Not for use directly within the front matter (FRT) peripheral file', 'nameEnglish': 'Short table of contents text', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('toc3', {'occursIn': 'Header', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Not for use directly within the front matter (FRT) peripheral file', 'nameEnglish': 'Book abbreviation', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('imt', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'May be used for the introduction title or other major introduction division (rather than \\is) when the introduction text contains numerous additional sub-divisions.', 'nameEnglish': 'Introduction main title', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('is', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Introduction section heading', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ip', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Introduction paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ipi', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Indented introduction paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('im', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Introduction flush left (margin) paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('imi', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Introduction flush left (margin) indented paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ipq', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Introduction quote from text paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('imq', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Introduction flush left (margin) quote from text paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ipr', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Typically used for a quote from text reference', 'nameEnglish': 'Introduction right-aligned paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('iq', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Introduction poetic line', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ib', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Never', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'May be used to explicitly indicate additional white space between paragraphs', 'nameEnglish': 'Introduction blank line', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ili', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Introduction list item', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('iot', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Introduction outline title', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('io', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'The outline entry typically ends with a range of references in parentheses', 'nameEnglish': 'Introduction outline entry', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ior', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'An outline entry typically ends with a range of references in parentheses. This is an optional character style for marking (and potentially formatting) these references separately', 'nameEnglish': 'Introduction outline reference range', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('iex', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'e.g. explanation of missing book in a short Old Testament', 'nameEnglish': 'Introduction explanatory or bridge text', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('iqt', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Scripture quotations, or other quoted text, appearing in the introduction', 'nameEnglish': 'Introduction quoted text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('imte', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'Used to mark a major title indicating the end of the introduction', 'nameEnglish': 'Introduction major title ending', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ie', {'occursIn': 'Introduction', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Optionally included to explicitly indicate the end of the introduction material', 'nameEnglish': 'Introduction end', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('mt', {'occursIn': 'Header', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'The key components in the title of a biblical book', 'nameEnglish': 'Major title', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('mte', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'May be used in texts which repeat the main title at the end of the introduction, or to mark a major title indicating the end of the introduction. The content is not typically identical to \\mt#.', 'nameEnglish': 'Major title at ending', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ms', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'These are headings before larger text divisions than what is typically considered a "section" division (see \\s#)', 'nameEnglish': 'Major section heading', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('mr', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'The text reference range listed under a major section heading', 'nameEnglish': 'Major section reference range', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('s', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'The typical (common) section division heading', 'nameEnglish': 'Section heading', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('sr', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'The text reference range listed under a section heading. \\sr is not equivalent to \\r which is used for marking parallel references.', 'nameEnglish': 'Section reference range', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('r', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'A reference to a parallel passage usually located under a section heading \\s#', 'nameEnglish': 'Parallel passage reference(s)', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('rq', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'A (cross) reference indicating the source text for the preceding quotation (usually an Old Testament quote). The reference(s) are intended to be formatted (typeset) within the scripture body text column, and not extracted from the text as are regular cross-references (\\x...\\x*). They are also typically separated from the main text of Scripture using a different type style and alignment.', 'nameEnglish': 'Inline quotation reference(s)', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('d', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Sometimes used in Psalms under the section title (e.g. "For the director of Music")', 'nameEnglish': 'Descriptive title (or "Hebrew subtitle")', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('sp', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': '(e.g. Job and Song of Songs)', 'nameEnglish': 'Speaker Identification', 'level': 'Newline', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'No'}),
  ('c', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': True, 'description': 'No text should follow this marker (i.e., after the chapter number? But some versions have footnotes here!', 'nameEnglish': 'Chapter number', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ca', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Used for marking the chapter number used in an alternate versification scheme. Required when different versification traditions need to be supported in the same translation text.', 'nameEnglish': 'Alternate (second) chapter number', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('cl', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Used when the chosen publishing presentation will render chapter divisions as headings, and not drop cap numerals. Usage note: If \\cl is entered once before chapter 1 (\\c 1) it represents the text for "chapter" to be used throughout the current book. If \\cl is used after each individual chapter marker, it represents the particular text to be used for the display of the current chapter heading (usually done if numbers are being presented as words, not numerals).', 'nameEnglish': 'Chapter label', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('cp', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'This is a chapter marker (number, letter) which would be displayed in the published text (where the published marker is different than the \\c # used within the translation editing environment)', 'nameEnglish': 'Published chapter character', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('cd', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'A brief description of chapter content (similar to \\d - descriptive heading, or \\iex - )', 'nameEnglish': 'Chapter description', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('v', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': True, 'description': 'Marker is followed by the verse number #, and the text of the verse', 'nameEnglish': 'Verse number', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('va', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Used for marking verse numbers used in an alternate versification scheme. Required when different versification traditions need to be supported in the same translation text.', 'nameEnglish': 'Alternate (second) verse number', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('vp', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'This is a verse marker (number, letter) which would be displayed in the published text (where the published marker is different than the \\v # used within the translation editing environment)', 'nameEnglish': 'Published verse character', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('p', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Followed immediately by a space and paragraph text, or by a new line and a verse marker', 'nameEnglish': 'Normal paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('m', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'No first line indent. Followed immediately by a space and paragraph text, or by a new line and a verse marker. Usually used to resume prose at the margin (without indent) after poetry or OT quotation (i.e. continuation of the previous paragraph).', 'nameEnglish': 'Flush left (margin) paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('pmo', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Embedded text opening', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('pm', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Embedded text paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('pmc', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Embedded text closing', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('pmr', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Embedded text refrain', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('pi', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'Used in some texts for discourse sections. The variable # represents the level of indent. See also \\pm.', 'nameEnglish': 'Indented paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('mi', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'No first line indent', 'nameEnglish': 'Indented flush left paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('nb', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Never', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Indicates "no-break" with previous paragraph (regardless of previous paragraph type). Commonly used in cases where the previous paragraph spans the chapter boundary. No-break markup within poetry: Some translations have a publishing tradition of inserting a small amount of additional white-space at chapter boundaries. It is important in these texts to use the \nb marker within any specific poetic contexts where no visible break in the flow of the the text is intended at a particular chapter boundary.', 'nameEnglish': 'No-break paragraph continuation', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('cls', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Similar to "With love," or "Sincerely yours,"', 'nameEnglish': 'Closure of an epistle/letter', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('li', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'An out-dented paragraph meant to highlight the items of a list. Lists may be used to markup the elements of a recurrent structure, such as the days within the creation account, or the Decalogue (10 commandments). The variable # represents the level of indent.', 'nameEnglish': 'List item', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('pc', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Recommended for inscriptions', 'nameEnglish': 'Centered paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('pr', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': False, 'compulsoryFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged). Recommended alternate: \\pmr', 'nameEnglish': 'Right-aligned paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': True, 'closed': 'No'}),
  ('ph', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': True, 'compulsoryFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged). The variable # represents the level of overall paragraph indent.', 'nameEnglish': 'Indented paragraph with hanging indent', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': True, 'closed': 'No'}),
  ('b', {'occursIn': 'Text, Poetry', 'nestsFlag': False, 'hasContent': 'Never', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'May be used to explicitly indicate additional white space between paragraphs. No text should follow this marker, and it should not be used before or after titles to indicate white-space. Also use for stanza breaks in poetry, or between poetry and prose.', 'nameEnglish': 'Blank line', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('q', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'The variable # represents the level of indent (i.e. \\q1, \\q2, \\q3 etc.)', 'nameEnglish': 'Poetic line', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('qr', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Common use: Poetic refrain', 'nameEnglish': 'Right-aligned poetic line', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('qc', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Centered poetic line', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('qs', {'occursIn': 'Poetry', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Used for the expression "Selah" commonly found in Psalms and Habakkuk. This text is frequently right aligned, and rendered on the same line as the previous poetic text, if space allows.', 'nameEnglish': 'Selah field', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('qa', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Acrostic heading', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('qac', {'occursIn': 'Acrostic verse', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Marker to indicate the acrostic letter within a poetic line', 'nameEnglish': 'Acrostic letter', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('qm', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'The variable # represents the level of indent (i.e. \\qm1, \\qm2 etc.)', 'nameEnglish': 'Embedded text poetic line', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('tr', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'The first \\tr initiates a new table. Rows contain column headings or cells', 'nameEnglish': 'Table row start', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('th', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'The variable # represents the table column number', 'nameEnglish': 'Table column heading', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('thr', {'occursIn': 'Table row', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'The variable # represents the table column number', 'nameEnglish': 'Right-aligned table column heading', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('tc', {'occursIn': 'Table row', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'The variable # represents the table column number. An empty table cell still requires a corresponding marker in the table text.', 'nameEnglish': 'Table cell', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('tcr', {'occursIn': 'Table row', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': True, 'compulsoryFlag': False, 'description': 'The variable # represents the table column number. An empty table cell still requires a corresponding marker in the table text.', 'nameEnglish': 'Right-aligned table cell', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('f', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Footnotes are entered inline within the main scripture body text. The boundaries of the footnote text are defined by an opening and closing marker.', 'nameEnglish': 'Footnote', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('e', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Endnotes are entered inline within the main scripture body text. The boundaries of the endnote text are defined by an opening and closing marker.', 'nameEnglish': 'Endnote', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('fr', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'This is the chapter and verse(s) that note refers to. Chapter and verse numbers must have a separator between them.', 'nameEnglish': 'Footnote "origin" reference', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('fk', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'The specific keyword/term from the text for which the footnote is being provided.', 'nameEnglish': 'Footnote keyword', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('fq', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'A quotation from the current scripture text translation for which the note is being provided. Longer quotations are sometimes shortened using an ellipsis (i.e. suspension dots "..."). Many existing translation texts have marked both quotations from the existing translation text, as well as alternative translations, using \\fq. An additional marker – \\fqa – is provided for marking alternative translations, and can be used to distinguish between quotations and alternatives.', 'nameEnglish': 'Footnote translation quotation', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('fqa', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Used to distinguish between a quotation of the current scripture text translation, and an alternate translation', 'nameEnglish': 'Footnote alternate translation', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('fl', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Can be used for marking or "labeling" a word or words which are used consistently across certain types of translation notes (such as the words "Or" in an alternative translation note, "Others", "Heb.", "LXX" etc.)', 'nameEnglish': 'Footnote "label" text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('fp', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Use this marker to if you need to indicate the start of a new paragraph within a footnote (uncommon in standard Bible notes)', 'nameEnglish': 'Footnote additional paragraph', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('fv', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'To mark the location of a verse number in the the text quotation or alternative translation', 'nameEnglish': 'Footnote verse number', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('ft', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'The essential (explanatory) text of the footnote', 'nameEnglish': 'Footnote text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('fdc', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Text between these markers is material to be included only in published editions that contain the Deuterocanonical books.', 'nameEnglish': 'Deuterocanon footnote text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('fm', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Used where two or more locations in the scripture text should ideally refer the reader to the same footnote text (as seen in identical footnote text which is referred to at Gen 2.9 and Gen 2.17 in some English translations). Because the nature of this marker is related directly to the published form of the text, it is not intended for use in scripture authoring. It may be used during the publishing process to connect two callers to the same footnote text.', 'nameEnglish': 'Footnote reference mark', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('x', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Cross-references are entered inline within the main scripture body text. The boundaries of the cross-reference text are defined by an opening and closing marker.', 'nameEnglish': 'Cross-reference', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('xo', {'occursIn': 'Cross-reference', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'This is the chapter and verse(s) that note refers to. Chapter and verse numbers must have a separator between them.', 'nameEnglish': 'Cross-reference "origin" reference', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('xk', {'occursIn': 'Cross-reference', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'A keyword from the scripture translation text which the target reference(s) also refer to', 'nameEnglish': 'Cross-reference keyword', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('xq', {'occursIn': 'Cross-reference', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'A quotation from the scripture text. Use of a quotation would be intended to help the reader to understand the portion of text (or concept) for which the target reference(s) are being supplied.', 'nameEnglish': 'Cross-reference quotation', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('xt', {'occursIn': 'Cross-reference', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'The list of target scripture locations being provided as alternate references to the text (or concept) of the origin reference. This is a list of book name abbreviations and chapter + verse references, separated by semicolons (though there may be an alternate references format for this list in different areas and countries).', 'nameEnglish': 'Target reference(s)', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Optional'}),
  ('xot', {'occursIn': 'Cross-reference', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the Old Testament books. (optional)', 'nameEnglish': 'Old Testament reference(s)', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('xnt', {'occursIn': 'Cross-reference', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the New Testament books. (optional)', 'nameEnglish': 'New Testament reference(s)', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('xdc', {'occursIn': 'Cross-reference', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the Deuterocanonical books. (optional)', 'nameEnglish': 'Deuterocanon reference(s)', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('add', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': "A translator's explanation; words added by the translator for clarity – text which is not literally a part of the original language, but which was supplied to make the meaning of the original clear", 'nameEnglish': "Translator's addition", 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('bk', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Quoted book title', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('dc', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Deuterocanonical/LXX additions or insertions in the Protocanonical text', 'nameEnglish': 'Deuterocanonical addition', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('k', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Keyword/keyterm', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('lit', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'e.g. a guide which tells the reader/worshipper that he should recite a prayer or recitation etc.', 'nameEnglish': 'Liturgical note/comment', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('nd', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Name of God/Deity', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('ord', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'i.e. in "1st"', 'nameEnglish': 'Ordinal number ending', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('pn', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Proper name', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('qt', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Old Testament quotations in the New Testament, or other quotations', 'nameEnglish': 'Quoted text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('sig', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'of the author of an epistle/letter', 'nameEnglish': 'Signature', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('sls', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Passage of text based on a secondary language or alternate text source. E.g. The NBS02 has large sections of text in EZR and DAN in italics, to represent where the original text is in Aramaic, not Hebrew.', 'nameEnglish': 'Secondary language source', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('tl', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Or foreign words', 'nameEnglish': 'Transliterated word(s)', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('wj', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Words of Jesus', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('em', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Emphasis text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('bd', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Bold text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('it', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Italic text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('bdit', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Bold-italic text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('no', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Normal text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('sc', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Small-caps text', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('pb', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Never', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Page break', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('fig', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Figure', 'level': 'Internal', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('ndx', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the subject index', 'nameEnglish': 'Subject index entry', 'level': 'Internal', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('pro', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Used for Chinese/Japanese/Korean texts', 'nameEnglish': 'Pronunciation information', 'level': 'Internal', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('w', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the word list', 'nameEnglish': 'Wordlist/glossary/dictionary entry', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('wg', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the Greek word list', 'nameEnglish': 'Greek wordlist entry', 'level': 'Internal', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('wh', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the Hebrew word list', 'nameEnglish': 'Hebrew wordlist entry', 'level': 'Internal', 'printedFlag': False, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('periph', {'occursIn': 'Front and back matter', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': None, 'nameEnglish': 'Peripheral content', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('ef', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Extended footnotes (for study Bibles) are entered inline within the main scripture body text. The boundaries of the footnote text are defined by an opening and closing marker.', 'nameEnglish': 'Extended footnote', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('fs', {'occursIn': 'Footnote', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged). A summary text for the concept/idea/quotation from the current Scripture text translation for which the note is being provided.', 'nameEnglish': 'Footnote summary', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': True, 'closed': 'Optional'}),
  ('ex', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Extended cross-references (for study Bibles) are entered inline within the main scripture body text. The boundaries of the cross-reference text are defined by an opening and closing marker.', 'nameEnglish': 'Extended cross-reference', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('esb', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Never', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'In study Bibles. Finishes at next \\esb marker or at end of chapter.', 'nameEnglish': 'Sidebar content', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'No'}),
  ('cat', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': 'Categories can optionally be assigned to extended study notes or sidebars by supplying a category tag (name) inside of opening and closing \\cat ... \\cat* markers. Category tags should be restricted to alpha-numeric characters. A list of category tags are defined individually and uniquely for each study Bible project.', 'nameEnglish': 'Category tag', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': False, 'closed': 'Always'}),
  ('pdi', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. Substituted with embedded text markup.', 'nameEnglish': 'PDI', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': True, 'closed': 'No'}),
  ('pde', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. Substituted with embedded text markup.', 'nameEnglish': 'PDE', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': True, 'closed': 'No'}),
  ('wr', {'occursIn': 'Text', 'nestsFlag': True, 'hasContent': 'Always', 'numberableFlag': False, 'compulsoryFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. Was really a duplicate of \\w ... \\w* used for marking words in the Scripture text which are included in the wordlist.', 'nameEnglish': 'WR', 'level': 'Internal', 'printedFlag': True, 'deprecatedFlag': True, 'closed': 'Always'}),
  ('ps', {'occursIn': 'Text', 'nestsFlag': False, 'hasContent': 'Sometimes', 'numberableFlag': False, 'compulsoryFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. This was used in conjunction with \\nb to indicate that the paragraph spans the chapter boundary. It should be sufficient to just start the new chapter with \\nb and use the appropriate paragraph marker for the previous chapter (\\p, \\m, etc.).', 'nameEnglish': 'Span paragraph', 'level': 'Newline', 'printedFlag': True, 'deprecatedFlag': True, 'closed': 'No'}),
]), # end of rawMarkerDict (128 entries)

deprecatedMarkersList = [
    # Fields (1) are: rawMarker
  'pr', # 0
  'ph1', # 1
  'ph2', # 2
  'ph3', # 3
  'fs', # 4
  'pdi', # 5
  'pde', # 6
  'wr', # 7
  'ps', # 8
], # end of deprecatedMarkersList (9 entries)

internalMarkersList = [
    # Fields (1) are: rawMarker
  'ior', # 0
  'iqt', # 1
  'rq', # 2
  'ca', # 3
  'va', # 4
  'vp', # 5
  'qs', # 6
  'qac', # 7
  'tc', # 8
  'tcr', # 9
  'f', # 10
  'e', # 11
  'fr', # 12
  'fk', # 13
  'fq', # 14
  'fqa', # 15
  'fl', # 16
  'fp', # 17
  'fv', # 18
  'ft', # 19
  'fdc', # 20
  'fm', # 21
  'x', # 22
  'xo', # 23
  'xk', # 24
  'xq', # 25
  'xt', # 26
  'xot', # 27
  'xnt', # 28
  'xdc', # 29
  'add', # 30
  'bk', # 31
  'dc', # 32
  'k', # 33
  'nd', # 34
  'ord', # 35
  'pn', # 36
  'qt', # 37
  'sig', # 38
  'sls', # 39
  'tl', # 40
  'wj', # 41
  'em', # 42
  'bd', # 43
  'it', # 44
  'bdit', # 45
  'no', # 46
  'sc', # 47
  'fig', # 48
  'ndx', # 49
  'pro', # 50
  'w', # 51
  'wg', # 52
  'wh', # 53
  'ef', # 54
  'fs', # 55
  'ex', # 56
  'cat', # 57
  'wr', # 58
], # end of internalMarkersList (59 entries)

combinedNewlineMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'ide', # 1
  'sts', # 2
  'rem', # 3
  'h', # 4
  'h1', # 5
  'h2', # 6
  'h3', # 7
  'toc1', # 8
  'toc2', # 9
  'toc3', # 10
  'imt', # 11
  'imt1', # 12
  'imt2', # 13
  'imt3', # 14
  'is', # 15
  'is1', # 16
  'is2', # 17
  'is3', # 18
  'ip', # 19
  'ipi', # 20
  'im', # 21
  'imi', # 22
  'ipq', # 23
  'imq', # 24
  'ipr', # 25
  'iq', # 26
  'iq1', # 27
  'iq2', # 28
  'iq3', # 29
  'ib', # 30
  'ili', # 31
  'ili1', # 32
  'ili2', # 33
  'ili3', # 34
  'iot', # 35
  'io', # 36
  'io1', # 37
  'io2', # 38
  'io3', # 39
  'iex', # 40
  'imte', # 41
  'imte1', # 42
  'imte2', # 43
  'imte3', # 44
  'ie', # 45
  'mt', # 46
  'mt1', # 47
  'mt2', # 48
  'mt3', # 49
  'mte', # 50
  'mte1', # 51
  'mte2', # 52
  'mte3', # 53
  'ms', # 54
  'ms1', # 55
  'ms2', # 56
  'ms3', # 57
  'mr', # 58
  's', # 59
  's1', # 60
  's2', # 61
  's3', # 62
  'sr', # 63
  'r', # 64
  'd', # 65
  'sp', # 66
  'c', # 67
  'cl', # 68
  'cp', # 69
  'cd', # 70
  'v', # 71
  'p', # 72
  'm', # 73
  'pmo', # 74
  'pm', # 75
  'pmc', # 76
  'pmr', # 77
  'pi', # 78
  'pi1', # 79
  'pi2', # 80
  'pi3', # 81
  'mi', # 82
  'nb', # 83
  'cls', # 84
  'li', # 85
  'li1', # 86
  'li2', # 87
  'li3', # 88
  'pc', # 89
  'pr', # 90
  'ph', # 91
  'ph1', # 92
  'ph2', # 93
  'ph3', # 94
  'b', # 95
  'q', # 96
  'q1', # 97
  'q2', # 98
  'q3', # 99
  'qr', # 100
  'qc', # 101
  'qa', # 102
  'qm', # 103
  'qm1', # 104
  'qm2', # 105
  'qm3', # 106
  'tr', # 107
  'th', # 108
  'th1', # 109
  'th2', # 110
  'th3', # 111
  'thr', # 112
  'thr1', # 113
  'thr2', # 114
  'thr3', # 115
  'lit', # 116
  'pb', # 117
  'periph', # 118
  'esb', # 119
  'pdi', # 120
  'pde', # 121
  'ps', # 122
], # end of combinedNewlineMarkersList (123 entries)

numberedInternalMarkersList = [
    # Fields (1) are: rawMarker
  'ior', # 0
  'iqt', # 1
  'rq', # 2
  'ca', # 3
  'va', # 4
  'vp', # 5
  'qs', # 6
  'qac', # 7
  'tc1', # 8
  'tc2', # 9
  'tc3', # 10
  'tcr1', # 11
  'tcr2', # 12
  'tcr3', # 13
  'f', # 14
  'e', # 15
  'fr', # 16
  'fk', # 17
  'fq', # 18
  'fqa', # 19
  'fl', # 20
  'fp', # 21
  'fv', # 22
  'ft', # 23
  'fdc', # 24
  'fm', # 25
  'x', # 26
  'xo', # 27
  'xk', # 28
  'xq', # 29
  'xt', # 30
  'xot', # 31
  'xnt', # 32
  'xdc', # 33
  'add', # 34
  'bk', # 35
  'dc', # 36
  'k', # 37
  'nd', # 38
  'ord', # 39
  'pn', # 40
  'qt', # 41
  'sig', # 42
  'sls', # 43
  'tl', # 44
  'wj', # 45
  'em', # 46
  'bd', # 47
  'it', # 48
  'bdit', # 49
  'no', # 50
  'sc', # 51
  'fig', # 52
  'ndx', # 53
  'pro', # 54
  'w', # 55
  'wg', # 56
  'wh', # 57
  'ef', # 58
  'fs', # 59
  'ex', # 60
  'cat', # 61
  'wr', # 62
], # end of numberedInternalMarkersList (63 entries)

numberedMarkerList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'ide', # 1
  'sts', # 2
  'rem', # 3
  'h1', # 4
  'h2', # 5
  'h3', # 6
  'toc1', # 7
  'toc2', # 8
  'toc3', # 9
  'imt1', # 10
  'imt2', # 11
  'imt3', # 12
  'is1', # 13
  'is2', # 14
  'is3', # 15
  'ip', # 16
  'ipi', # 17
  'im', # 18
  'imi', # 19
  'ipq', # 20
  'imq', # 21
  'ipr', # 22
  'iq1', # 23
  'iq2', # 24
  'iq3', # 25
  'ib', # 26
  'ili1', # 27
  'ili2', # 28
  'ili3', # 29
  'iot', # 30
  'io1', # 31
  'io2', # 32
  'io3', # 33
  'ior', # 34
  'iex', # 35
  'iqt', # 36
  'imte1', # 37
  'imte2', # 38
  'imte3', # 39
  'ie', # 40
  'mt1', # 41
  'mt2', # 42
  'mt3', # 43
  'mte1', # 44
  'mte2', # 45
  'mte3', # 46
  'ms1', # 47
  'ms2', # 48
  'ms3', # 49
  'mr', # 50
  's1', # 51
  's2', # 52
  's3', # 53
  'sr', # 54
  'r', # 55
  'rq', # 56
  'd', # 57
  'sp', # 58
  'c', # 59
  'ca', # 60
  'cl', # 61
  'cp', # 62
  'cd', # 63
  'v', # 64
  'va', # 65
  'vp', # 66
  'p', # 67
  'm', # 68
  'pmo', # 69
  'pm', # 70
  'pmc', # 71
  'pmr', # 72
  'pi1', # 73
  'pi2', # 74
  'pi3', # 75
  'mi', # 76
  'nb', # 77
  'cls', # 78
  'li1', # 79
  'li2', # 80
  'li3', # 81
  'pc', # 82
  'pr', # 83
  'ph1', # 84
  'ph2', # 85
  'ph3', # 86
  'b', # 87
  'q1', # 88
  'q2', # 89
  'q3', # 90
  'qr', # 91
  'qc', # 92
  'qs', # 93
  'qa', # 94
  'qac', # 95
  'qm1', # 96
  'qm2', # 97
  'qm3', # 98
  'tr', # 99
  'th1', # 100
  'th2', # 101
  'th3', # 102
  'thr1', # 103
  'thr2', # 104
  'thr3', # 105
  'tc1', # 106
  'tc2', # 107
  'tc3', # 108
  'tcr1', # 109
  'tcr2', # 110
  'tcr3', # 111
  'f', # 112
  'e', # 113
  'fr', # 114
  'fk', # 115
  'fq', # 116
  'fqa', # 117
  'fl', # 118
  'fp', # 119
  'fv', # 120
  'ft', # 121
  'fdc', # 122
  'fm', # 123
  'x', # 124
  'xo', # 125
  'xk', # 126
  'xq', # 127
  'xt', # 128
  'xot', # 129
  'xnt', # 130
  'xdc', # 131
  'add', # 132
  'bk', # 133
  'dc', # 134
  'k', # 135
  'lit', # 136
  'nd', # 137
  'ord', # 138
  'pn', # 139
  'qt', # 140
  'sig', # 141
  'sls', # 142
  'tl', # 143
  'wj', # 144
  'em', # 145
  'bd', # 146
  'it', # 147
  'bdit', # 148
  'no', # 149
  'sc', # 150
  'pb', # 151
  'fig', # 152
  'ndx', # 153
  'pro', # 154
  'w', # 155
  'wg', # 156
  'wh', # 157
  'periph', # 158
  'ef', # 159
  'fs', # 160
  'ex', # 161
  'esb', # 162
  'cat', # 163
  'pdi', # 164
  'pde', # 165
  'wr', # 166
  'ps', # 167
], # end of numberedMarkerList (168 entries)

backConversionDict = {
  # Key is numberedMarker
  # Fields (1) are: rawMarker
  'h1': 'h',
  'h2': 'h',
  'h3': 'h',
  'ili1': 'ili',
  'ili2': 'ili',
  'ili3': 'ili',
  'imt1': 'imt',
  'imt2': 'imt',
  'imt3': 'imt',
  'imte1': 'imte',
  'imte2': 'imte',
  'imte3': 'imte',
  'io1': 'io',
  'io2': 'io',
  'io3': 'io',
  'iq1': 'iq',
  'iq2': 'iq',
  'iq3': 'iq',
  'is1': 'is',
  'is2': 'is',
  'is3': 'is',
  'li1': 'li',
  'li2': 'li',
  'li3': 'li',
  'ms1': 'ms',
  'ms2': 'ms',
  'ms3': 'ms',
  'mt1': 'mt',
  'mt2': 'mt',
  'mt3': 'mt',
  'mte1': 'mte',
  'mte2': 'mte',
  'mte3': 'mte',
  'ph1': 'ph',
  'ph2': 'ph',
  'ph3': 'ph',
  'pi1': 'pi',
  'pi2': 'pi',
  'pi3': 'pi',
  'q1': 'q',
  'q2': 'q',
  'q3': 'q',
  'qm1': 'qm',
  'qm2': 'qm',
  'qm3': 'qm',
  's1': 's',
  's2': 's',
  's3': 's',
  'tc1': 'tc',
  'tc2': 'tc',
  'tc3': 'tc',
  'tcr1': 'tcr',
  'tcr2': 'tcr',
  'tcr3': 'tcr',
  'th1': 'th',
  'th2': 'th',
  'th3': 'th',
  'thr1': 'thr',
  'thr2': 'thr',
  'thr3': 'thr',
}
# end of backConversionDict (60 entries)

# end of USFMMarkers_Tables.py