# /home/robert/Programming/WebDevelopment/OpenScriptures/BibleOrgSys/DataFiles/DerivedFiles/USFM3Markers_Tables.py
#
# This UTF-8 file was automatically generated by USFM3Markers.py V0.04 on 2020-02-24 14:38:01.517877
#
# USFM 3.0 markers list data
#  Version: 0.03
#  Date: 2020-02-24
#
#   136 USFM3Markers loaded from the original XML file.
#

rawMarkerDict = {
  # Key is rawMarker (in the original XML order)
  # Fields (11) are: specified
  'add': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': "A translator's explanation; words added by the translator for clarity – text which is not literally a part of the original language, but which was supplied to make the meaning of the original clear", 'nameEnglish': "Translator's addition"},
  'b': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Never', 'occursIn': 'Text, Poetry', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'May be used to explicitly indicate additional white space between paragraphs.\n        No text should follow this marker, and it should not be used before or after titles to indicate white-space.\n        Also use for stanza breaks in poetry, or between poetry and prose.', 'nameEnglish': 'Blank line'},
  'bd': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Bold text'},
  'bdit': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Bold-italic text'},
  'bk': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Quoted book title'},
  'c': {'compulsoryFlag': True, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Numbering', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'No text should follow this marker (i.e., after the chapter number? But some versions have footnotes here!', 'nameEnglish': 'Chapter number'},
  'ca': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Numbering', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Used for marking the chapter number used in an alternate versification scheme. Required when different versification traditions need to be supported in the same translation text.', 'nameEnglish': 'Alternate (second) chapter number'},
  'cat': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Categories can optionally be assigned to extended study notes or sidebars by supplying a category tag (name) inside of opening and closing \\cat … \\cat* markers. Category tags should be restricted to alpha-numeric characters. A list of category tags are defined individually and uniquely for each study Bible project.', 'nameEnglish': 'Category tag'},
  'cd': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'A brief description of chapter content (similar to \\d - descriptive heading, or \\iex - )', 'nameEnglish': 'Chapter description'},
  'cl': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Numbering', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Used when the chosen publishing presentation will render chapter divisions as headings, and not drop cap numerals. Usage note: If \\cl is entered once before chapter 1 (\\c 1) it represents the text for "chapter" to be used throughout the current book. If \\cl is used after each individual chapter marker, it represents the particular text to be used for the display of the current chapter heading (usually done if numbers are being presented as words, not numerals).', 'nameEnglish': 'Chapter label'},
  'cls': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Similar to "With love," or "Sincerely yours,"', 'nameEnglish': 'Closure of an epistle/letter'},
  'cp': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Numbering', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'This is a chapter marker (number, letter) which would be displayed in the published text (where the published marker is different than the \\c # used within the translation editing environment)', 'nameEnglish': 'Published chapter character'},
  'd': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Sometimes used in Psalms under the section title (e.g. "For the director of Music")', 'nameEnglish': 'Descriptive title (or "Hebrew subtitle")'},
  'dc': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Deuterocanonical/LXX additions or insertions in the Protocanonical text', 'nameEnglish': 'Deuterocanonical addition'},
  'e': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Endnotes are entered inline within the main scripture body text. The boundaries of the endnote text are defined by an opening and closing marker.', 'nameEnglish': 'Endnote'},
  'ef': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Extended footnotes (for study Bibles) are entered inline within the main scripture body text. The boundaries of the footnote text are defined by an opening and closing marker.', 'nameEnglish': 'Extended footnote'},
  'em': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Emphasis text'},
  'esb': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Never', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'In study Bibles. Finishes at next \\esb marker or at end of chapter.', 'nameEnglish': 'Sidebar content'},
  'ex': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Extended cross-references (for study Bibles) are entered inline within the main scripture body text. The boundaries of the cross-reference text are defined by an opening and closing marker.', 'nameEnglish': 'Extended cross-reference'},
  'f': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Footnotes are entered inline within the main scripture body text. The boundaries of the footnote text are defined by an opening and closing marker.', 'nameEnglish': 'Footnote'},
  'fdc': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Text between these markers is material to be included only in published editions that contain the Deuterocanonical books.', 'nameEnglish': 'Deuterocanon footnote text'},
  'fig': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': False, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Figure'},
  'fk': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'The specific keyword/term from the text for which the footnote is being provided.', 'nameEnglish': 'Footnote keyword'},
  'fl': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'Can be used for marking or "labeling" a word or words which are used consistently across certain types of translation notes (such as the words "Or" in an alternative translation note, "Others", "Heb.", "LXX" etc.)', 'nameEnglish': 'Footnote "label" text'},
  'fm': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Used where two or more locations in the scripture text should ideally refer the reader to the same footnote text (as seen in identical footnote text which is referred to at Gen 2.9 and Gen 2.17 in some English translations). Because the nature of this marker is related directly to the published form of the text, it is not intended for use in scripture authoring. It may be used during the publishing process to connect two callers to the same footnote text.', 'nameEnglish': 'Footnote reference mark'},
  'fn': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'To mark the location of a sequential footnote number in the the text quotation or alternative translation', 'nameEnglish': 'Footnote number'},
  'fp': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'Use this marker to if you need to indicate the start of a new paragraph within a footnote (uncommon in standard Bible notes)', 'nameEnglish': 'Footnote additional paragraph'},
  'fq': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'A quotation from the current scripture text translation for which the note is being provided. Longer quotations are sometimes shortened using an ellipsis (i.e. suspension dots "…"). Many existing translation texts have marked both quotations from the existing translation text, as well as alternative translations, using \\fq. An additional marker – \\fqa – is provided for marking alternative translations, and can be used to distinguish between quotations and alternatives.', 'nameEnglish': 'Footnote translation quotation'},
  'fqa': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'Used to distinguish between a quotation of the current scripture text translation, and an alternate translation', 'nameEnglish': 'Footnote alternate translation'},
  'fr': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'This is the chapter and verse(s) that note refers to. Chapter and verse numbers must have a separator between them.', 'nameEnglish': 'Footnote "origin" reference'},
  'fs': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': True, 'description': '"Deprecated" (i.e. use is strongly discouraged). A summary text for the concept/idea/quotation from the current Scripture text translation for which the note is being provided.', 'nameEnglish': 'Footnote summary'},
  'ft': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'The essential (explanatory) text of the footnote', 'nameEnglish': 'Footnote text'},
  'fv': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Footnote', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'To mark the location of a verse number in the the text quotation or alternative translation', 'nameEnglish': 'Footnote verse number'},
  'h': {'compulsoryFlag': True, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Running header text'},
  'ib': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Never', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'May be used to explicitly indicate additional white space between paragraphs', 'nameEnglish': 'Introduction blank line'},
  'id': {'compulsoryFlag': True, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': False, 'closed': 'No', 'deprecatedFlag': False, 'description': 'This is the initial USFM marker in any scripture text file', 'nameEnglish': 'File identification'},
  'ide': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': False, 'closed': 'No', 'deprecatedFlag': False, 'description': 'This marker should be used to specify the character encoding of the text within the file. For example: CP-1252, CP-1251, UTF-8, UTF-16, OR Custom <specify font name>. If the character encoding does not conform to a known standard, but is rather a customized solution for the project, a minimum of the name of the font used for the project should be included. For archive purposes, texts which rely upon a custom encoding solution should be converted to Unicode, if at all possible.', 'nameEnglish': 'An optional character encoding specification'},
  'ie': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Optionally included to explicitly indicate the end of the introduction material', 'nameEnglish': 'Introduction end'},
  'iex': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'e.g. explanation of missing book in a short Old Testament', 'nameEnglish': 'Introduction explanatory or bridge text'},
  'ili': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Introduction list item'},
  'im': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Introduction flush left (margin) paragraph'},
  'imi': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Introduction flush left (margin) indented paragraph'},
  'imq': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Introduction flush left (margin) quote from text paragraph'},
  'imt': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'May be used for the introduction title or other major introduction division (rather than \\is) when the introduction text contains numerous additional sub-divisions.', 'nameEnglish': 'Introduction main title'},
  'imte': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Used to mark a major title indicating the end of the introduction', 'nameEnglish': 'Introduction major title ending'},
  'io': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The outline entry typically ends with a range of references in parentheses', 'nameEnglish': 'Introduction outline entry'},
  'ior': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'An outline entry typically ends with a range of references in parentheses. This is an optional character style for marking (and potentially formatting) these references separately', 'nameEnglish': 'Introduction outline reference range'},
  'iot': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Introduction outline title'},
  'ip': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Introduction paragraph'},
  'ipi': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Indented introduction paragraph'},
  'ipq': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Introduction quote from text paragraph'},
  'ipr': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Typically used for a quote from text reference', 'nameEnglish': 'Introduction right-aligned paragraph'},
  'iq': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Introduction poetic line'},
  'iqt': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Scripture quotations, or other quoted text, appearing in the introduction', 'nameEnglish': 'Introduction quoted text'},
  'is': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Introduction', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Introduction section heading'},
  'it': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Italic text'},
  'k': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Keyword/keyterm'},
  'li': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'An out-dented paragraph meant to highlight the items of a list.\n        Lists may be used to markup the elements of a recurrent structure, such as the days within the creation account,\n            or the Decalogue (10 commandments). The variable # represents the level of indent.', 'nameEnglish': 'List item'},
  'lit': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'e.g. a guide which tells the reader/worshipper that he should recite a prayer or recitation etc.', 'nameEnglish': 'Liturgical note/comment'},
  'm': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'No first line indent. Followed immediately by a space and paragraph text, or by a new line and a verse marker. Usually used to resume prose at the margin (without indent) after poetry or OT quotation (i.e. continuation of the previous paragraph).', 'nameEnglish': 'Flush left (margin) paragraph'},
  'mi': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'No first line indent', 'nameEnglish': 'Indented flush left paragraph'},
  'mr': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The text reference range listed under a major section heading. Perhaps it could be described as the verse range which the \\ms major section heading above it applies to.', 'nameEnglish': 'Major section reference range'},
  'ms': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'These are headings before larger text divisions than what is typically considered a "section" division (see \\s#)', 'nameEnglish': 'Major section heading'},
  'mt': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The key components in the title of a biblical book', 'nameEnglish': 'Major title'},
  'mte': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'May be used in texts which repeat the main title at the end of the introduction, or to mark a major title indicating the end of the introduction. The content is not typically identical to \\mt#.', 'nameEnglish': 'Major title at ending'},
  'nb': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Never', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Indicates "no-break" with previous paragraph (regardless of previous paragraph type).\n        Commonly used in cases where the previous paragraph spans the chapter boundary.\n        No-break markup within poetry: Some translations have a publishing tradition of inserting a small\n            amount of additional white-space at chapter boundaries.\n        It is important in these texts to use the b marker within any specific poetic contexts where\n            no visible break in the flow of the the text is intended at a particular chapter boundary.', 'nameEnglish': 'No-break paragraph continuation'},
  'nd': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Name of God/Deity'},
  'ndx': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': False, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the subject index', 'nameEnglish': 'Subject index entry'},
  'no': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Normal text'},
  'ord': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'i.e. in "1st"', 'nameEnglish': 'Ordinal number ending'},
  'p': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Followed immediately by a space and paragraph text, or by a new line and a verse marker', 'nameEnglish': 'Normal paragraph'},
  'pb': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Never', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Page break'},
  'pc': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Recommended for inscriptions', 'nameEnglish': 'Centered paragraph'},
  'pde': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': True, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. Substituted with embedded text markup.', 'nameEnglish': 'PDE'},
  'pdi': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': True, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. Substituted with embedded text markup.', 'nameEnglish': 'PDI'},
  'periph': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Front and back matter', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Peripheral content'},
  'ph': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': True, 'description': '"Deprecated" (i.e. use is strongly discouraged).\n        The variable # represents the level of overall paragraph indent.', 'nameEnglish': 'Indented paragraph with hanging indent'},
  'pi': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Used in some texts for discourse sections. The variable # represents the level of indent.\n        See also \\pm.', 'nameEnglish': 'Indented paragraph'},
  'pm': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Embedded text paragraph'},
  'pmc': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Embedded text closing'},
  'pmo': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Embedded text opening'},
  'pmr': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Embedded text refrain'},
  'pn': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Proper name'},
  'pr': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': True, 'description': '"Deprecated" (i.e. use is strongly discouraged). Recommended alternate: \\pmr', 'nameEnglish': 'Right-aligned paragraph'},
  'pro': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': False, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Used for Chinese/Japanese/Korean texts', 'nameEnglish': 'Pronunciation information'},
  'ps': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': True, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. This was used in conjunction with \\nb to indicate that the paragraph spans the chapter boundary. It should be sufficient to just start the new chapter with \\nb and use the appropriate paragraph marker for the previous chapter (\\p, \\m, etc.).', 'nameEnglish': 'Span paragraph'},
  'q': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Sometimes', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The variable # represents the level of indent (i.e. \\q1, \\q2, \\q3 etc.)', 'nameEnglish': 'Poetic line'},
  'qa': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'For example, the Aleph, Beth, etc. headings in Lamentations or Psalm 119', 'nameEnglish': 'Acrostic heading'},
  'qac': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Acrostic verse', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Marker to indicate the acrostic letter within a poetic line', 'nameEnglish': 'Acrostic letter'},
  'qc': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Centered poetic line'},
  'qm': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The variable # represents the level of indent (i.e. \\qm1, \\qm2 etc.)', 'nameEnglish': 'Embedded text poetic line'},
  'qr': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Common use: Poetic refrain', 'nameEnglish': 'Right-aligned poetic line'},
  'qs': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Canonical Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Used for the expression "Selah" commonly found in Psalms and Habakkuk. This text is frequently right aligned, and rendered on the same line as the previous poetic text, if space allows.', 'nameEnglish': 'Selah field'},
  'qt': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Old Testament quotations in the New Testament, or other quotations', 'nameEnglish': 'Quoted text'},
  'qt-e': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Self', 'deprecatedFlag': False, 'description': 'Quotation end milestone. Typically used for indicating the speaker of the text. The (optional) number represents the level of nesting of the quotation being marked (i.e. a quote within a quote).', 'nameEnglish': 'Quotation end'},
  'qt-s': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Self', 'deprecatedFlag': False, 'description': 'Quotation start milestone. Typically used for indicating the speaker of the text. The (optional) number represents the level of nesting of the quotation being marked (i.e. a quote within a quote).', 'nameEnglish': 'Quotation start'},
  'r': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'A reference to a parallel passage usually located under a section heading \\s#', 'nameEnglish': 'Parallel passage reference(s)'},
  'rem': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': False, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Used for adding brief comments by a translator, consultant, or support person', 'nameEnglish': 'Remark/Comment'},
  'rq': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'A (cross) reference indicating the source text for the preceding quotation (usually an Old Testament quote). The reference(s) are intended to be formatted (typeset) within the scripture body text column, and not extracted from the text as are regular cross-references (\\x…\\x*). They are also typically separated from the main text of Scripture using a different type style and alignment.', 'nameEnglish': 'Inline quotation reference(s)'},
  's': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The typical (common) section division heading', 'nameEnglish': 'Section heading'},
  'sc': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Small-caps text'},
  'sig': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'of the author of an epistle/letter', 'nameEnglish': 'Signature'},
  'sls': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Passage of text based on a secondary language or alternate text source. E.g. The NBS02 has large sections of text in EZR and DAN in italics, to represent where the original text is in Aramaic, not Hebrew.', 'nameEnglish': 'Secondary language source'},
  'sp': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': False, 'closed': 'No', 'deprecatedFlag': False, 'description': '(e.g. Job and Song of Songs)', 'nameEnglish': 'Speaker Identification'},
  'sr': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The text reference range listed under a section heading. \\sr is not equivalent to \\r which is used for marking parallel references. Perhaps it could be described as the verse range which the \\s section heading above it applies to.', 'nameEnglish': 'Section reference range'},
  'sts': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': False, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The contents of the status marker can be defined by the downstream system being used to track project status', 'nameEnglish': 'Project status tracking'},
  'tc': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Table row', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The variable # represents the table column number. An empty table cell still requires a corresponding marker in the table text.', 'nameEnglish': 'Table cell'},
  'tcr': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Table row', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The variable # represents the table column number. An empty table cell still requires a corresponding marker in the table text.', 'nameEnglish': 'Right-aligned table cell'},
  'th': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Table row', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The variable # represents the table column number', 'nameEnglish': 'Table column heading'},
  'thr': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': '4', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Table row', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The variable # represents the table column number', 'nameEnglish': 'Right-aligned table column heading'},
  'tl': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Or foreign words', 'nameEnglish': 'Transliterated word(s)'},
  'toc1': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Not for use directly within the front matter (FRT) peripheral file', 'nameEnglish': 'Long table of contents text'},
  'toc2': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Not for use directly within the front matter (FRT) peripheral file', 'nameEnglish': 'Short table of contents text'},
  'toc3': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Not for use directly within the front matter (FRT) peripheral file', 'nameEnglish': 'Book abbreviation'},
  'toc4': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Not in USFM 2.4 but rather an addition used by Michael Kahunapule Johnson (Haiola/USFX)', 'nameEnglish': 'Psalm singular name'},
  'tr': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'The first \\tr initiates a new table. Rows contain column headings or cells', 'nameEnglish': 'Table row start'},
  'ts': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Never', 'occursIn': 'Text', 'printedFlag': False, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Translator’s section milestone. For identifying a section (chunk) of text suitable for translating at one time.', 'nameEnglish': "Translator's section"},
  'ts-e': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Never', 'occursIn': 'Text', 'printedFlag': False, 'closed': 'Self', 'deprecatedFlag': False, 'description': 'Translator’s section end milestone. For identifying a section (chunk) of text suitable for translating at one time.', 'nameEnglish': "Translator's section end"},
  'ts-s': {'compulsoryFlag': False, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Never', 'occursIn': 'Text', 'printedFlag': False, 'closed': 'Self', 'deprecatedFlag': False, 'description': 'Translator’s section start milestone. For identifying a section (chunk) of text suitable for translating at one time.', 'nameEnglish': "Translator's section start"},
  'usfm': {'compulsoryFlag': True, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Header', 'printedFlag': False, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Used to identify the USFM version which a USFM editor / processor will be required to support in order to manage all markup found within the file.', 'nameEnglish': 'USFM version specification'},
  'v': {'compulsoryFlag': True, 'level': 'Newline', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Numbering', 'printedFlag': True, 'closed': 'No', 'deprecatedFlag': False, 'description': 'Marker is followed by the verse number #, and the text of the verse', 'nameEnglish': 'Verse number'},
  'va': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Numbering', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Used for marking verse numbers used in an alternate versification scheme. Required when different versification traditions need to be supported in the same translation text.', 'nameEnglish': 'Alternate (second) verse number'},
  'vp': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Numbering', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'This is a verse marker (number, letter) which would be displayed in the published text (where the published marker is different than the \\v # used within the translation editing environment)', 'nameEnglish': 'Published verse character'},
  'w': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the word list', 'nameEnglish': 'Wordlist/glossary/dictionary entry'},
  'wg': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': False, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the Greek word list', 'nameEnglish': 'Greek wordlist entry'},
  'wh': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': False, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the Hebrew word list', 'nameEnglish': 'Hebrew wordlist entry'},
  'wj': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': None, 'nameEnglish': 'Words of Jesus'},
  'wr': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': True, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': True, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. Was really a duplicate of \\w … \\w* used for marking words in the Scripture text which are included in the wordlist.', 'nameEnglish': 'WR'},
  'x': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Text', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'Cross-references are entered inline within the main scripture body text. The boundaries of the cross-reference text are defined by an opening and closing marker.', 'nameEnglish': 'Cross-reference'},
  'xdc': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Cross-reference', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the Deuterocanonical books. (optional)', 'nameEnglish': 'Deuterocanon reference(s)'},
  'xk': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Cross-reference', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'A keyword from the scripture translation text which the target reference(s) also refer to', 'nameEnglish': 'Cross-reference keyword'},
  'xnt': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Cross-reference', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the New Testament books. (optional)', 'nameEnglish': 'New Testament reference(s)'},
  'xo': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Cross-reference', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'This is the chapter and verse(s) that note refers to. Chapter and verse numbers must have a separator between them.', 'nameEnglish': 'Cross-reference "origin" reference'},
  'xot': {'compulsoryFlag': False, 'level': 'Internal', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Cross-reference', 'printedFlag': True, 'closed': 'Always', 'deprecatedFlag': False, 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the Old Testament books. (optional)', 'nameEnglish': 'Old Testament reference(s)'},
  'xq': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Cross-reference', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'A quotation from the scripture text. Use of a quotation would be intended to help the reader to understand the portion of text (or concept) for which the target reference(s) are being supplied.', 'nameEnglish': 'Cross-reference quotation'},
  'xt': {'compulsoryFlag': False, 'level': 'Note', 'highestNumberSuffix': 'None', 'nestsFlag': False, 'hasContent': 'Always', 'occursIn': 'Cross-reference', 'printedFlag': True, 'closed': 'Optional', 'deprecatedFlag': False, 'description': 'The list of target scripture locations being provided as alternate references to the text (or concept) of the origin reference. This is a list of book name abbreviations and chapter + verse references, separated by semicolons (though there may be an alternate references format for this list in different areas and countries).', 'nameEnglish': 'Target reference(s)'},
}
# end of rawMarkerDict (136 entries)

numberedMarkerList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'usfm', # 1
  'ide', # 2
  'sts', # 3
  'rem', # 4
  'h', # 5
  'toc1', # 6
  'toc2', # 7
  'toc3', # 8
  'toc4', # 9
  'imt1', # 10
  'imt2', # 11
  'imt3', # 12
  'imt4', # 13
  'is1', # 14
  'is2', # 15
  'is3', # 16
  'is4', # 17
  'ip', # 18
  'ipi', # 19
  'im', # 20
  'imi', # 21
  'ipq', # 22
  'imq', # 23
  'ipr', # 24
  'iq1', # 25
  'iq2', # 26
  'iq3', # 27
  'iq4', # 28
  'ib', # 29
  'ili1', # 30
  'ili2', # 31
  'ili3', # 32
  'ili4', # 33
  'iot', # 34
  'io1', # 35
  'io2', # 36
  'io3', # 37
  'io4', # 38
  'ior', # 39
  'iex', # 40
  'iqt', # 41
  'imte1', # 42
  'imte2', # 43
  'imte3', # 44
  'imte4', # 45
  'ie', # 46
  'mt1', # 47
  'mt2', # 48
  'mt3', # 49
  'mt4', # 50
  'mte1', # 51
  'mte2', # 52
  'mte3', # 53
  'mte4', # 54
  'ms1', # 55
  'ms2', # 56
  'ms3', # 57
  'ms4', # 58
  'mr', # 59
  's1', # 60
  's2', # 61
  's3', # 62
  's4', # 63
  'sr', # 64
  'r', # 65
  'rq', # 66
  'd', # 67
  'sp', # 68
  'c', # 69
  'ca', # 70
  'cl', # 71
  'cp', # 72
  'cd', # 73
  'v', # 74
  'va', # 75
  'vp', # 76
  'p', # 77
  'm', # 78
  'pmo', # 79
  'pm', # 80
  'pmc', # 81
  'pmr', # 82
  'pi1', # 83
  'pi2', # 84
  'pi3', # 85
  'pi4', # 86
  'mi', # 87
  'nb', # 88
  'cls', # 89
  'li1', # 90
  'li2', # 91
  'li3', # 92
  'li4', # 93
  'pc', # 94
  'pr', # 95
  'ph1', # 96
  'ph2', # 97
  'ph3', # 98
  'ph4', # 99
  'b', # 100
  'q1', # 101
  'q2', # 102
  'q3', # 103
  'q4', # 104
  'qr', # 105
  'qc', # 106
  'qs', # 107
  'qa', # 108
  'qac', # 109
  'qm1', # 110
  'qm2', # 111
  'qm3', # 112
  'qm4', # 113
  'tr', # 114
  'th1', # 115
  'th2', # 116
  'th3', # 117
  'th4', # 118
  'thr1', # 119
  'thr2', # 120
  'thr3', # 121
  'thr4', # 122
  'tc1', # 123
  'tc2', # 124
  'tc3', # 125
  'tc4', # 126
  'tcr1', # 127
  'tcr2', # 128
  'tcr3', # 129
  'tcr4', # 130
  'f', # 131
  'e', # 132
  'fr', # 133
  'fk', # 134
  'fq', # 135
  'fqa', # 136
  'fl', # 137
  'fp', # 138
  'fv', # 139
  'fn', # 140
  'ft', # 141
  'fdc', # 142
  'fm', # 143
  'x', # 144
  'xo', # 145
  'xk', # 146
  'xq', # 147
  'xt', # 148
  'xot', # 149
  'xnt', # 150
  'xdc', # 151
  'add', # 152
  'bk', # 153
  'dc', # 154
  'k', # 155
  'lit', # 156
  'nd', # 157
  'ord', # 158
  'pn', # 159
  'qt', # 160
  'sig', # 161
  'sls', # 162
  'tl', # 163
  'wj', # 164
  'em', # 165
  'bd', # 166
  'it', # 167
  'bdit', # 168
  'no', # 169
  'sc', # 170
  'pb', # 171
  'fig', # 172
  'ndx', # 173
  'pro', # 174
  'w', # 175
  'wg', # 176
  'wh', # 177
  'qt1-s', # 178
  'qt2-s', # 179
  'qt3-s', # 180
  'qt4-s', # 181
  'qt1-e', # 182
  'qt2-e', # 183
  'qt3-e', # 184
  'qt4-e', # 185
  'ts', # 186
  'ts-s', # 187
  'ts-e', # 188
  'ef', # 189
  'fs', # 190
  'ex', # 191
  'esb', # 192
  'cat', # 193
  'periph', # 194
  'pdi', # 195
  'pde', # 196
  'wr', # 197
  'ps', # 198
], # end of numberedMarkerList (199 entries)

combinedMarkerDict = {
  # Key is marker
  # Fields (1) are: rawMarker
  'add': 'add',
  'b': 'b',
  'bd': 'bd',
  'bdit': 'bdit',
  'bk': 'bk',
  'c': 'c',
  'ca': 'ca',
  'cat': 'cat',
  'cd': 'cd',
  'cl': 'cl',
  'cls': 'cls',
  'cp': 'cp',
  'd': 'd',
  'dc': 'dc',
  'e': 'e',
  'ef': 'ef',
  'em': 'em',
  'esb': 'esb',
  'ex': 'ex',
  'f': 'f',
  'fdc': 'fdc',
  'fig': 'fig',
  'fk': 'fk',
  'fl': 'fl',
  'fm': 'fm',
  'fn': 'fn',
  'fp': 'fp',
  'fq': 'fq',
  'fqa': 'fqa',
  'fr': 'fr',
  'fs': 'fs',
  'ft': 'ft',
  'fv': 'fv',
  'h': 'h',
  'ib': 'ib',
  'id': 'id',
  'ide': 'ide',
  'ie': 'ie',
  'iex': 'iex',
  'ili': 'ili',
  'ili1': 'ili',
  'ili2': 'ili',
  'ili3': 'ili',
  'ili4': 'ili',
  'im': 'im',
  'imi': 'imi',
  'imq': 'imq',
  'imt': 'imt',
  'imt1': 'imt',
  'imt2': 'imt',
  'imt3': 'imt',
  'imt4': 'imt',
  'imte': 'imte',
  'imte1': 'imte',
  'imte2': 'imte',
  'imte3': 'imte',
  'imte4': 'imte',
  'io': 'io',
  'io1': 'io',
  'io2': 'io',
  'io3': 'io',
  'io4': 'io',
  'ior': 'ior',
  'iot': 'iot',
  'ip': 'ip',
  'ipi': 'ipi',
  'ipq': 'ipq',
  'ipr': 'ipr',
  'iq': 'iq',
  'iq1': 'iq',
  'iq2': 'iq',
  'iq3': 'iq',
  'iq4': 'iq',
  'iqt': 'iqt',
  'is': 'is',
  'is1': 'is',
  'is2': 'is',
  'is3': 'is',
  'is4': 'is',
  'it': 'it',
  'k': 'k',
  'li': 'li',
  'li1': 'li',
  'li2': 'li',
  'li3': 'li',
  'li4': 'li',
  'lit': 'lit',
  'm': 'm',
  'mi': 'mi',
  'mr': 'mr',
  'ms': 'ms',
  'ms1': 'ms',
  'ms2': 'ms',
  'ms3': 'ms',
  'ms4': 'ms',
  'mt': 'mt',
  'mt1': 'mt',
  'mt2': 'mt',
  'mt3': 'mt',
  'mt4': 'mt',
  'mte': 'mte',
  'mte1': 'mte',
  'mte2': 'mte',
  'mte3': 'mte',
  'mte4': 'mte',
  'nb': 'nb',
  'nd': 'nd',
  'ndx': 'ndx',
  'no': 'no',
  'ord': 'ord',
  'p': 'p',
  'pb': 'pb',
  'pc': 'pc',
  'pde': 'pde',
  'pdi': 'pdi',
  'periph': 'periph',
  'ph': 'ph',
  'ph1': 'ph',
  'ph2': 'ph',
  'ph3': 'ph',
  'ph4': 'ph',
  'pi': 'pi',
  'pi1': 'pi',
  'pi2': 'pi',
  'pi3': 'pi',
  'pi4': 'pi',
  'pm': 'pm',
  'pmc': 'pmc',
  'pmo': 'pmo',
  'pmr': 'pmr',
  'pn': 'pn',
  'pr': 'pr',
  'pro': 'pro',
  'ps': 'ps',
  'q': 'q',
  'q1': 'q',
  'q2': 'q',
  'q3': 'q',
  'q4': 'q',
  'qa': 'qa',
  'qac': 'qac',
  'qc': 'qc',
  'qm': 'qm',
  'qm1': 'qm',
  'qm2': 'qm',
  'qm3': 'qm',
  'qm4': 'qm',
  'qr': 'qr',
  'qs': 'qs',
  'qt': 'qt',
  'qt-e': 'qt-e',
  'qt-s': 'qt-s',
  'qt1-e': 'qt-e',
  'qt1-s': 'qt-s',
  'qt2-e': 'qt-e',
  'qt2-s': 'qt-s',
  'qt3-e': 'qt-e',
  'qt3-s': 'qt-s',
  'qt4-e': 'qt-e',
  'qt4-s': 'qt-s',
  'r': 'r',
  'rem': 'rem',
  'rq': 'rq',
  's': 's',
  's1': 's',
  's2': 's',
  's3': 's',
  's4': 's',
  'sc': 'sc',
  'sig': 'sig',
  'sls': 'sls',
  'sp': 'sp',
  'sr': 'sr',
  'sts': 'sts',
  'tc': 'tc',
  'tc1': 'tc',
  'tc2': 'tc',
  'tc3': 'tc',
  'tc4': 'tc',
  'tcr': 'tcr',
  'tcr1': 'tcr',
  'tcr2': 'tcr',
  'tcr3': 'tcr',
  'tcr4': 'tcr',
  'th': 'th',
  'th1': 'th',
  'th2': 'th',
  'th3': 'th',
  'th4': 'th',
  'thr': 'thr',
  'thr1': 'thr',
  'thr2': 'thr',
  'thr3': 'thr',
  'thr4': 'thr',
  'tl': 'tl',
  'toc1': 'toc1',
  'toc2': 'toc2',
  'toc3': 'toc3',
  'toc4': 'toc4',
  'tr': 'tr',
  'ts': 'ts',
  'ts-e': 'ts-e',
  'ts-s': 'ts-s',
  'usfm': 'usfm',
  'v': 'v',
  'va': 'va',
  'vp': 'vp',
  'w': 'w',
  'wg': 'wg',
  'wh': 'wh',
  'wj': 'wj',
  'wr': 'wr',
  'x': 'x',
  'xdc': 'xdc',
  'xk': 'xk',
  'xnt': 'xnt',
  'xo': 'xo',
  'xot': 'xot',
  'xq': 'xq',
  'xt': 'xt',
}
# end of combinedMarkerDict (220 entries)

conversionDict = {
  # Key is rawMarker
  # Fields (1) are: numberedMarker
  'ili': 'ili1',
  'imt': 'imt1',
  'imte': 'imte1',
  'io': 'io1',
  'iq': 'iq1',
  'is': 'is1',
  'li': 'li1',
  'ms': 'ms1',
  'mt': 'mt1',
  'mte': 'mte1',
  'ph': 'ph1',
  'pi': 'pi1',
  'q': 'q1',
  'qm': 'qm1',
  'qt-e': 'qt1-e',
  'qt-s': 'qt1-s',
  's': 's1',
  'tc': 'tc1',
  'tcr': 'tcr1',
  'th': 'th1',
  'thr': 'thr1',
}
# end of conversionDict (21 entries)

backConversionDict = {
  # Key is numberedMarker
  # Fields (1) are: rawMarker
  'ili1': 'ili',
  'ili2': 'ili',
  'ili3': 'ili',
  'ili4': 'ili',
  'imt1': 'imt',
  'imt2': 'imt',
  'imt3': 'imt',
  'imt4': 'imt',
  'imte1': 'imte',
  'imte2': 'imte',
  'imte3': 'imte',
  'imte4': 'imte',
  'io1': 'io',
  'io2': 'io',
  'io3': 'io',
  'io4': 'io',
  'iq1': 'iq',
  'iq2': 'iq',
  'iq3': 'iq',
  'iq4': 'iq',
  'is1': 'is',
  'is2': 'is',
  'is3': 'is',
  'is4': 'is',
  'li1': 'li',
  'li2': 'li',
  'li3': 'li',
  'li4': 'li',
  'ms1': 'ms',
  'ms2': 'ms',
  'ms3': 'ms',
  'ms4': 'ms',
  'mt1': 'mt',
  'mt2': 'mt',
  'mt3': 'mt',
  'mt4': 'mt',
  'mte1': 'mte',
  'mte2': 'mte',
  'mte3': 'mte',
  'mte4': 'mte',
  'ph1': 'ph',
  'ph2': 'ph',
  'ph3': 'ph',
  'ph4': 'ph',
  'pi1': 'pi',
  'pi2': 'pi',
  'pi3': 'pi',
  'pi4': 'pi',
  'q1': 'q',
  'q2': 'q',
  'q3': 'q',
  'q4': 'q',
  'qm1': 'qm',
  'qm2': 'qm',
  'qm3': 'qm',
  'qm4': 'qm',
  'qt1-e': 'qt-e',
  'qt1-s': 'qt-s',
  'qt2-e': 'qt-e',
  'qt2-s': 'qt-s',
  'qt3-e': 'qt-e',
  'qt3-s': 'qt-s',
  'qt4-e': 'qt-e',
  'qt4-s': 'qt-s',
  's1': 's',
  's2': 's',
  's3': 's',
  's4': 's',
  'tc1': 'tc',
  'tc2': 'tc',
  'tc3': 'tc',
  'tc4': 'tc',
  'tcr1': 'tcr',
  'tcr2': 'tcr',
  'tcr3': 'tcr',
  'tcr4': 'tcr',
  'th1': 'th',
  'th2': 'th',
  'th3': 'th',
  'th4': 'th',
  'thr1': 'thr',
  'thr2': 'thr',
  'thr3': 'thr',
  'thr4': 'thr',
}
# end of backConversionDict (84 entries)

newlineMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'usfm', # 1
  'ide', # 2
  'sts', # 3
  'rem', # 4
  'h', # 5
  'toc1', # 6
  'toc2', # 7
  'toc3', # 8
  'toc4', # 9
  'imt', # 10
  'is', # 11
  'ip', # 12
  'ipi', # 13
  'im', # 14
  'imi', # 15
  'ipq', # 16
  'imq', # 17
  'ipr', # 18
  'iq', # 19
  'ib', # 20
  'ili', # 21
  'iot', # 22
  'io', # 23
  'iex', # 24
  'imte', # 25
  'ie', # 26
  'mt', # 27
  'mte', # 28
  'ms', # 29
  'mr', # 30
  's', # 31
  'sr', # 32
  'r', # 33
  'd', # 34
  'sp', # 35
  'c', # 36
  'cl', # 37
  'cp', # 38
  'cd', # 39
  'v', # 40
  'p', # 41
  'm', # 42
  'pmo', # 43
  'pm', # 44
  'pmc', # 45
  'pmr', # 46
  'pi', # 47
  'mi', # 48
  'nb', # 49
  'cls', # 50
  'li', # 51
  'pc', # 52
  'pr', # 53
  'ph', # 54
  'b', # 55
  'q', # 56
  'qr', # 57
  'qc', # 58
  'qa', # 59
  'qm', # 60
  'tr', # 61
  'lit', # 62
  'pb', # 63
  'ts', # 64
  'ts-s', # 65
  'ts-e', # 66
  'esb', # 67
  'periph', # 68
  'pdi', # 69
  'pde', # 70
  'ps', # 71
], # end of newlineMarkersList (72 entries)

numberedNewlineMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'usfm', # 1
  'ide', # 2
  'sts', # 3
  'rem', # 4
  'h', # 5
  'toc1', # 6
  'toc2', # 7
  'toc3', # 8
  'toc4', # 9
  'imt1', # 10
  'imt2', # 11
  'imt3', # 12
  'imt4', # 13
  'is1', # 14
  'is2', # 15
  'is3', # 16
  'is4', # 17
  'ip', # 18
  'ipi', # 19
  'im', # 20
  'imi', # 21
  'ipq', # 22
  'imq', # 23
  'ipr', # 24
  'iq1', # 25
  'iq2', # 26
  'iq3', # 27
  'iq4', # 28
  'ib', # 29
  'ili1', # 30
  'ili2', # 31
  'ili3', # 32
  'ili4', # 33
  'iot', # 34
  'io1', # 35
  'io2', # 36
  'io3', # 37
  'io4', # 38
  'iex', # 39
  'imte1', # 40
  'imte2', # 41
  'imte3', # 42
  'imte4', # 43
  'ie', # 44
  'mt1', # 45
  'mt2', # 46
  'mt3', # 47
  'mt4', # 48
  'mte1', # 49
  'mte2', # 50
  'mte3', # 51
  'mte4', # 52
  'ms1', # 53
  'ms2', # 54
  'ms3', # 55
  'ms4', # 56
  'mr', # 57
  's1', # 58
  's2', # 59
  's3', # 60
  's4', # 61
  'sr', # 62
  'r', # 63
  'd', # 64
  'sp', # 65
  'c', # 66
  'cl', # 67
  'cp', # 68
  'cd', # 69
  'v', # 70
  'p', # 71
  'm', # 72
  'pmo', # 73
  'pm', # 74
  'pmc', # 75
  'pmr', # 76
  'pi1', # 77
  'pi2', # 78
  'pi3', # 79
  'pi4', # 80
  'mi', # 81
  'nb', # 82
  'cls', # 83
  'li1', # 84
  'li2', # 85
  'li3', # 86
  'li4', # 87
  'pc', # 88
  'pr', # 89
  'ph1', # 90
  'ph2', # 91
  'ph3', # 92
  'ph4', # 93
  'b', # 94
  'q1', # 95
  'q2', # 96
  'q3', # 97
  'q4', # 98
  'qr', # 99
  'qc', # 100
  'qa', # 101
  'qm1', # 102
  'qm2', # 103
  'qm3', # 104
  'qm4', # 105
  'tr', # 106
  'lit', # 107
  'pb', # 108
  'ts', # 109
  'ts-s', # 110
  'ts-e', # 111
  'esb', # 112
  'periph', # 113
  'pdi', # 114
  'pde', # 115
  'ps', # 116
], # end of numberedNewlineMarkersList (117 entries)

combinedNewlineMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'usfm', # 1
  'ide', # 2
  'sts', # 3
  'rem', # 4
  'h', # 5
  'toc1', # 6
  'toc2', # 7
  'toc3', # 8
  'toc4', # 9
  'imt', # 10
  'imt1', # 11
  'imt2', # 12
  'imt3', # 13
  'imt4', # 14
  'is', # 15
  'is1', # 16
  'is2', # 17
  'is3', # 18
  'is4', # 19
  'ip', # 20
  'ipi', # 21
  'im', # 22
  'imi', # 23
  'ipq', # 24
  'imq', # 25
  'ipr', # 26
  'iq', # 27
  'iq1', # 28
  'iq2', # 29
  'iq3', # 30
  'iq4', # 31
  'ib', # 32
  'ili', # 33
  'ili1', # 34
  'ili2', # 35
  'ili3', # 36
  'ili4', # 37
  'iot', # 38
  'io', # 39
  'io1', # 40
  'io2', # 41
  'io3', # 42
  'io4', # 43
  'iex', # 44
  'imte', # 45
  'imte1', # 46
  'imte2', # 47
  'imte3', # 48
  'imte4', # 49
  'ie', # 50
  'mt', # 51
  'mt1', # 52
  'mt2', # 53
  'mt3', # 54
  'mt4', # 55
  'mte', # 56
  'mte1', # 57
  'mte2', # 58
  'mte3', # 59
  'mte4', # 60
  'ms', # 61
  'ms1', # 62
  'ms2', # 63
  'ms3', # 64
  'ms4', # 65
  'mr', # 66
  's', # 67
  's1', # 68
  's2', # 69
  's3', # 70
  's4', # 71
  'sr', # 72
  'r', # 73
  'd', # 74
  'sp', # 75
  'c', # 76
  'cl', # 77
  'cp', # 78
  'cd', # 79
  'v', # 80
  'p', # 81
  'm', # 82
  'pmo', # 83
  'pm', # 84
  'pmc', # 85
  'pmr', # 86
  'pi', # 87
  'pi1', # 88
  'pi2', # 89
  'pi3', # 90
  'pi4', # 91
  'mi', # 92
  'nb', # 93
  'cls', # 94
  'li', # 95
  'li1', # 96
  'li2', # 97
  'li3', # 98
  'li4', # 99
  'pc', # 100
  'pr', # 101
  'ph', # 102
  'ph1', # 103
  'ph2', # 104
  'ph3', # 105
  'ph4', # 106
  'b', # 107
  'q', # 108
  'q1', # 109
  'q2', # 110
  'q3', # 111
  'q4', # 112
  'qr', # 113
  'qc', # 114
  'qa', # 115
  'qm', # 116
  'qm1', # 117
  'qm2', # 118
  'qm3', # 119
  'qm4', # 120
  'tr', # 121
  'lit', # 122
  'pb', # 123
  'ts', # 124
  'ts-s', # 125
  'ts-e', # 126
  'esb', # 127
  'periph', # 128
  'pdi', # 129
  'pde', # 130
  'ps', # 131
], # end of combinedNewlineMarkersList (132 entries)

internalMarkersList = [
    # Fields (1) are: rawMarker
  'ior', # 0
  'iqt', # 1
  'rq', # 2
  'ca', # 3
  'va', # 4
  'vp', # 5
  'qs', # 6
  'qac', # 7
  'th', # 8
  'thr', # 9
  'tc', # 10
  'tcr', # 11
  'xot', # 12
  'xnt', # 13
  'xdc', # 14
  'add', # 15
  'bk', # 16
  'dc', # 17
  'k', # 18
  'nd', # 19
  'ord', # 20
  'pn', # 21
  'qt', # 22
  'sig', # 23
  'sls', # 24
  'tl', # 25
  'wj', # 26
  'em', # 27
  'bd', # 28
  'it', # 29
  'bdit', # 30
  'no', # 31
  'sc', # 32
  'ndx', # 33
  'pro', # 34
  'w', # 35
  'wg', # 36
  'wh', # 37
  'qt-s', # 38
  'qt-e', # 39
  'ef', # 40
  'fs', # 41
  'ex', # 42
  'cat', # 43
  'wr', # 44
], # end of internalMarkersList (45 entries)

numberedInternalMarkersList = [
    # Fields (1) are: rawMarker
  'ior', # 0
  'iqt', # 1
  'rq', # 2
  'ca', # 3
  'va', # 4
  'vp', # 5
  'qs', # 6
  'qac', # 7
  'th1', # 8
  'th2', # 9
  'th3', # 10
  'th4', # 11
  'thr1', # 12
  'thr2', # 13
  'thr3', # 14
  'thr4', # 15
  'tc1', # 16
  'tc2', # 17
  'tc3', # 18
  'tc4', # 19
  'tcr1', # 20
  'tcr2', # 21
  'tcr3', # 22
  'tcr4', # 23
  'f', # 24
  'e', # 25
  'fr', # 26
  'fk', # 27
  'fq', # 28
  'fqa', # 29
  'fl', # 30
  'fp', # 31
  'fv', # 32
  'fn', # 33
  'ft', # 34
  'fdc', # 35
  'fm', # 36
  'x', # 37
  'xo', # 38
  'xk', # 39
  'xq', # 40
  'xt', # 41
  'xot', # 42
  'xnt', # 43
  'xdc', # 44
  'add', # 45
  'bk', # 46
  'dc', # 47
  'k', # 48
  'nd', # 49
  'ord', # 50
  'pn', # 51
  'qt', # 52
  'sig', # 53
  'sls', # 54
  'tl', # 55
  'wj', # 56
  'em', # 57
  'bd', # 58
  'it', # 59
  'bdit', # 60
  'no', # 61
  'sc', # 62
  'fig', # 63
  'ndx', # 64
  'pro', # 65
  'w', # 66
  'wg', # 67
  'wh', # 68
  'qt1-s', # 69
  'qt2-s', # 70
  'qt3-s', # 71
  'qt4-s', # 72
  'qt1-e', # 73
  'qt2-e', # 74
  'qt3-e', # 75
  'qt4-e', # 76
  'ef', # 77
  'fs', # 78
  'ex', # 79
  'cat', # 80
  'wr', # 81
], # end of numberedInternalMarkersList (82 entries)

combinedInternalMarkersList = [
    # Fields (1) are: rawMarker
  'th1', # 0
  'th2', # 1
  'th3', # 2
  'th4', # 3
  'thr1', # 4
  'thr2', # 5
  'thr3', # 6
  'thr4', # 7
  'tc1', # 8
  'tc2', # 9
  'tc3', # 10
  'tc4', # 11
  'tcr1', # 12
  'tcr2', # 13
  'tcr3', # 14
  'tcr4', # 15
  'qt1-s', # 16
  'qt2-s', # 17
  'qt3-s', # 18
  'qt4-s', # 19
  'qt1-e', # 20
  'qt2-e', # 21
  'qt3-e', # 22
  'qt4-e', # 23
], # end of combinedInternalMarkersList (24 entries)

noteMarkersList = [
    # Fields (1) are: rawMarker
  'f', # 0
  'e', # 1
  'fr', # 2
  'fk', # 3
  'fq', # 4
  'fqa', # 5
  'fl', # 6
  'fp', # 7
  'fv', # 8
  'fn', # 9
  'ft', # 10
  'fdc', # 11
  'fm', # 12
  'x', # 13
  'xo', # 14
  'xk', # 15
  'xq', # 16
  'xt', # 17
  'fig', # 18
], # end of noteMarkersList (19 entries)

deprecatedMarkersList = [
    # Fields (1) are: rawMarker
  'pr', # 0
  'ph1', # 1
  'ph2', # 2
  'ph3', # 3
  'ph4', # 4
  'fs', # 5
  'pdi', # 6
  'pde', # 7
  'wr', # 8
  'ps', # 9
], # end of deprecatedMarkersList (10 entries)

# end of USFM3Markers_Tables.py