# ./DataFiles/DerivedFiles/USFMMarkers_Tables.py
#
# This UTF-8 file was automatically generated by USFMMarkers.py V0.56 on 2014-01-10 16:36:53.007279
#
# USFM 2.4 markers list data
#  Version: 0.60
#  Date: 2013-12-21
#
#   128 USFMMarkers loaded from the original XML file.
#

from collections import OrderedDict

combinedInternalMarkersList = [
    # Fields (1) are: rawMarker
  'th1', # 0
  'th2', # 1
  'th3', # 2
  'th4', # 3
  'thr1', # 4
  'thr2', # 5
  'thr3', # 6
  'thr4', # 7
  'tc1', # 8
  'tc2', # 9
  'tc3', # 10
  'tc4', # 11
  'tcr1', # 12
  'tcr2', # 13
  'tcr3', # 14
  'tcr4', # 15
], # end of combinedInternalMarkersList (16 entries)

numberedNewlineMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'ide', # 1
  'sts', # 2
  'rem', # 3
  'h', # 4
  'toc1', # 5
  'toc2', # 6
  'toc3', # 7
  'imt1', # 8
  'imt2', # 9
  'imt3', # 10
  'imt4', # 11
  'is1', # 12
  'is2', # 13
  'is3', # 14
  'is4', # 15
  'ip', # 16
  'ipi', # 17
  'im', # 18
  'imi', # 19
  'ipq', # 20
  'imq', # 21
  'ipr', # 22
  'iq1', # 23
  'iq2', # 24
  'iq3', # 25
  'iq4', # 26
  'ib', # 27
  'ili1', # 28
  'ili2', # 29
  'ili3', # 30
  'ili4', # 31
  'iot', # 32
  'io1', # 33
  'io2', # 34
  'io3', # 35
  'io4', # 36
  'iex', # 37
  'imte1', # 38
  'imte2', # 39
  'imte3', # 40
  'imte4', # 41
  'ie', # 42
  'mt1', # 43
  'mt2', # 44
  'mt3', # 45
  'mt4', # 46
  'mte1', # 47
  'mte2', # 48
  'mte3', # 49
  'mte4', # 50
  'ms1', # 51
  'ms2', # 52
  'ms3', # 53
  'ms4', # 54
  'mr', # 55
  's1', # 56
  's2', # 57
  's3', # 58
  's4', # 59
  'sr', # 60
  'r', # 61
  'd', # 62
  'sp', # 63
  'c', # 64
  'cl', # 65
  'cp', # 66
  'cd', # 67
  'v', # 68
  'p', # 69
  'm', # 70
  'pmo', # 71
  'pm', # 72
  'pmc', # 73
  'pmr', # 74
  'pi1', # 75
  'pi2', # 76
  'pi3', # 77
  'pi4', # 78
  'mi', # 79
  'nb', # 80
  'cls', # 81
  'li1', # 82
  'li2', # 83
  'li3', # 84
  'li4', # 85
  'pc', # 86
  'pr', # 87
  'ph1', # 88
  'ph2', # 89
  'ph3', # 90
  'ph4', # 91
  'b', # 92
  'q1', # 93
  'q2', # 94
  'q3', # 95
  'q4', # 96
  'qr', # 97
  'qc', # 98
  'qa', # 99
  'qm1', # 100
  'qm2', # 101
  'qm3', # 102
  'qm4', # 103
  'tr', # 104
  'lit', # 105
  'pb', # 106
  'periph', # 107
  'esb', # 108
  'pdi', # 109
  'pde', # 110
  'ps', # 111
], # end of numberedNewlineMarkersList (112 entries)

numberedInternalMarkersList = [
    # Fields (1) are: rawMarker
  'ior', # 0
  'iqt', # 1
  'rq', # 2
  'ca', # 3
  'va', # 4
  'vp', # 5
  'qs', # 6
  'qac', # 7
  'th1', # 8
  'th2', # 9
  'th3', # 10
  'th4', # 11
  'thr1', # 12
  'thr2', # 13
  'thr3', # 14
  'thr4', # 15
  'tc1', # 16
  'tc2', # 17
  'tc3', # 18
  'tc4', # 19
  'tcr1', # 20
  'tcr2', # 21
  'tcr3', # 22
  'tcr4', # 23
  'f', # 24
  'e', # 25
  'fr', # 26
  'fk', # 27
  'fq', # 28
  'fqa', # 29
  'fl', # 30
  'fp', # 31
  'fv', # 32
  'ft', # 33
  'fdc', # 34
  'fm', # 35
  'x', # 36
  'xo', # 37
  'xk', # 38
  'xq', # 39
  'xt', # 40
  'xot', # 41
  'xnt', # 42
  'xdc', # 43
  'add', # 44
  'bk', # 45
  'dc', # 46
  'k', # 47
  'nd', # 48
  'ord', # 49
  'pn', # 50
  'qt', # 51
  'sig', # 52
  'sls', # 53
  'tl', # 54
  'wj', # 55
  'em', # 56
  'bd', # 57
  'it', # 58
  'bdit', # 59
  'no', # 60
  'sc', # 61
  'fig', # 62
  'ndx', # 63
  'pro', # 64
  'w', # 65
  'wg', # 66
  'wh', # 67
  'ef', # 68
  'fs', # 69
  'ex', # 70
  'cat', # 71
  'wr', # 72
], # end of numberedInternalMarkersList (73 entries)

conversionDict = {
  # Key is rawMarker
  # Fields (1) are: numberedMarker
  'ili': 'ili1',
  'imt': 'imt1',
  'imte': 'imte1',
  'io': 'io1',
  'iq': 'iq1',
  'is': 'is1',
  'li': 'li1',
  'ms': 'ms1',
  'mt': 'mt1',
  'mte': 'mte1',
  'ph': 'ph1',
  'pi': 'pi1',
  'q': 'q1',
  'qm': 'qm1',
  's': 's1',
  'tc': 'tc1',
  'tcr': 'tcr1',
  'th': 'th1',
  'thr': 'thr1',
}
# end of conversionDict (19 entries)

combinedMarkerDict = {
  # Key is marker
  # Fields (1) are: rawMarker
  'add': 'add',
  'b': 'b',
  'bd': 'bd',
  'bdit': 'bdit',
  'bk': 'bk',
  'c': 'c',
  'ca': 'ca',
  'cat': 'cat',
  'cd': 'cd',
  'cl': 'cl',
  'cls': 'cls',
  'cp': 'cp',
  'd': 'd',
  'dc': 'dc',
  'e': 'e',
  'ef': 'ef',
  'em': 'em',
  'esb': 'esb',
  'ex': 'ex',
  'f': 'f',
  'fdc': 'fdc',
  'fig': 'fig',
  'fk': 'fk',
  'fl': 'fl',
  'fm': 'fm',
  'fp': 'fp',
  'fq': 'fq',
  'fqa': 'fqa',
  'fr': 'fr',
  'fs': 'fs',
  'ft': 'ft',
  'fv': 'fv',
  'h': 'h',
  'ib': 'ib',
  'id': 'id',
  'ide': 'ide',
  'ie': 'ie',
  'iex': 'iex',
  'ili': 'ili',
  'ili1': 'ili',
  'ili2': 'ili',
  'ili3': 'ili',
  'ili4': 'ili',
  'im': 'im',
  'imi': 'imi',
  'imq': 'imq',
  'imt': 'imt',
  'imt1': 'imt',
  'imt2': 'imt',
  'imt3': 'imt',
  'imt4': 'imt',
  'imte': 'imte',
  'imte1': 'imte',
  'imte2': 'imte',
  'imte3': 'imte',
  'imte4': 'imte',
  'io': 'io',
  'io1': 'io',
  'io2': 'io',
  'io3': 'io',
  'io4': 'io',
  'ior': 'ior',
  'iot': 'iot',
  'ip': 'ip',
  'ipi': 'ipi',
  'ipq': 'ipq',
  'ipr': 'ipr',
  'iq': 'iq',
  'iq1': 'iq',
  'iq2': 'iq',
  'iq3': 'iq',
  'iq4': 'iq',
  'iqt': 'iqt',
  'is': 'is',
  'is1': 'is',
  'is2': 'is',
  'is3': 'is',
  'is4': 'is',
  'it': 'it',
  'k': 'k',
  'li': 'li',
  'li1': 'li',
  'li2': 'li',
  'li3': 'li',
  'li4': 'li',
  'lit': 'lit',
  'm': 'm',
  'mi': 'mi',
  'mr': 'mr',
  'ms': 'ms',
  'ms1': 'ms',
  'ms2': 'ms',
  'ms3': 'ms',
  'ms4': 'ms',
  'mt': 'mt',
  'mt1': 'mt',
  'mt2': 'mt',
  'mt3': 'mt',
  'mt4': 'mt',
  'mte': 'mte',
  'mte1': 'mte',
  'mte2': 'mte',
  'mte3': 'mte',
  'mte4': 'mte',
  'nb': 'nb',
  'nd': 'nd',
  'ndx': 'ndx',
  'no': 'no',
  'ord': 'ord',
  'p': 'p',
  'pb': 'pb',
  'pc': 'pc',
  'pde': 'pde',
  'pdi': 'pdi',
  'periph': 'periph',
  'ph': 'ph',
  'ph1': 'ph',
  'ph2': 'ph',
  'ph3': 'ph',
  'ph4': 'ph',
  'pi': 'pi',
  'pi1': 'pi',
  'pi2': 'pi',
  'pi3': 'pi',
  'pi4': 'pi',
  'pm': 'pm',
  'pmc': 'pmc',
  'pmo': 'pmo',
  'pmr': 'pmr',
  'pn': 'pn',
  'pr': 'pr',
  'pro': 'pro',
  'ps': 'ps',
  'q': 'q',
  'q1': 'q',
  'q2': 'q',
  'q3': 'q',
  'q4': 'q',
  'qa': 'qa',
  'qac': 'qac',
  'qc': 'qc',
  'qm': 'qm',
  'qm1': 'qm',
  'qm2': 'qm',
  'qm3': 'qm',
  'qm4': 'qm',
  'qr': 'qr',
  'qs': 'qs',
  'qt': 'qt',
  'r': 'r',
  'rem': 'rem',
  'rq': 'rq',
  's': 's',
  's1': 's',
  's2': 's',
  's3': 's',
  's4': 's',
  'sc': 'sc',
  'sig': 'sig',
  'sls': 'sls',
  'sp': 'sp',
  'sr': 'sr',
  'sts': 'sts',
  'tc': 'tc',
  'tc1': 'tc',
  'tc2': 'tc',
  'tc3': 'tc',
  'tc4': 'tc',
  'tcr': 'tcr',
  'tcr1': 'tcr',
  'tcr2': 'tcr',
  'tcr3': 'tcr',
  'tcr4': 'tcr',
  'th': 'th',
  'th1': 'th',
  'th2': 'th',
  'th3': 'th',
  'th4': 'th',
  'thr': 'thr',
  'thr1': 'thr',
  'thr2': 'thr',
  'thr3': 'thr',
  'thr4': 'thr',
  'tl': 'tl',
  'toc1': 'toc1',
  'toc2': 'toc2',
  'toc3': 'toc3',
  'tr': 'tr',
  'v': 'v',
  'va': 'va',
  'vp': 'vp',
  'w': 'w',
  'wg': 'wg',
  'wh': 'wh',
  'wj': 'wj',
  'wr': 'wr',
  'x': 'x',
  'xdc': 'xdc',
  'xk': 'xk',
  'xnt': 'xnt',
  'xo': 'xo',
  'xot': 'xot',
  'xq': 'xq',
  'xt': 'xt',
}
# end of combinedMarkerDict (204 entries)

rawMarkerDict = OrderedDict([
    # Key is rawMarker (in the original XML order)
    # Fields (11) are: specified
  ('id', {'nestsFlag': False, 'nameEnglish': 'File identification', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': True, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'This is the initial USFM marker in any scripture text file', 'level': 'Newline', 'occursIn': 'Header'}),
  ('ide', {'nestsFlag': False, 'nameEnglish': 'An optional character encoding specification', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'This marker should be used to specify the character encoding of the text within the file', 'level': 'Newline', 'occursIn': 'Header'}),
  ('sts', {'nestsFlag': False, 'nameEnglish': 'Project status tracking', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'The contents of the status marker can be defined by the downstream system being used to track project status', 'level': 'Newline', 'occursIn': 'Header'}),
  ('rem', {'nestsFlag': False, 'nameEnglish': 'Remark/Comment', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Used for adding brief comments by a translator, consultant, or support person', 'level': 'Newline', 'occursIn': 'Header'}),
  ('h', {'nestsFlag': False, 'nameEnglish': 'Running header text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': True, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Header'}),
  ('toc1', {'nestsFlag': False, 'nameEnglish': 'Long table of contents text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Not for use directly within the front matter (FRT) peripheral file', 'level': 'Newline', 'occursIn': 'Header'}),
  ('toc2', {'nestsFlag': False, 'nameEnglish': 'Short table of contents text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Not for use directly within the front matter (FRT) peripheral file', 'level': 'Newline', 'occursIn': 'Header'}),
  ('toc3', {'nestsFlag': False, 'nameEnglish': 'Book abbreviation', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Not for use directly within the front matter (FRT) peripheral file', 'level': 'Newline', 'occursIn': 'Header'}),
  ('imt', {'nestsFlag': False, 'nameEnglish': 'Introduction main title', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'May be used for the introduction title or other major introduction division (rather than \\is) when the introduction text contains numerous additional sub-divisions.', 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('is', {'nestsFlag': False, 'nameEnglish': 'Introduction section heading', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('ip', {'nestsFlag': False, 'nameEnglish': 'Introduction paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('ipi', {'nestsFlag': False, 'nameEnglish': 'Indented introduction paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('im', {'nestsFlag': False, 'nameEnglish': 'Introduction flush left (margin) paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('imi', {'nestsFlag': False, 'nameEnglish': 'Introduction flush left (margin) indented paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('ipq', {'nestsFlag': False, 'nameEnglish': 'Introduction quote from text paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('imq', {'nestsFlag': False, 'nameEnglish': 'Introduction flush left (margin) quote from text paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('ipr', {'nestsFlag': False, 'nameEnglish': 'Introduction right-aligned paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Typically used for a quote from text reference', 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('iq', {'nestsFlag': False, 'nameEnglish': 'Introduction poetic line', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('ib', {'nestsFlag': False, 'nameEnglish': 'Introduction blank line', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': 'No', 'numberableFlag': False, 'description': 'May be used to explicitly indicate additional white space between paragraphs', 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('ili', {'nestsFlag': False, 'nameEnglish': 'Introduction list item', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('iot', {'nestsFlag': False, 'nameEnglish': 'Introduction outline title', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('io', {'nestsFlag': False, 'nameEnglish': 'Introduction outline entry', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'The outline entry typically ends with a range of references in parentheses', 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('ior', {'nestsFlag': False, 'nameEnglish': 'Introduction outline reference range', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'An outline entry typically ends with a range of references in parentheses. This is an optional character style for marking (and potentially formatting) these references separately', 'level': 'Internal', 'occursIn': 'Introduction'}),
  ('iex', {'nestsFlag': False, 'nameEnglish': 'Introduction explanatory or bridge text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'e.g. explanation of missing book in a short Old Testament', 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('iqt', {'nestsFlag': False, 'nameEnglish': 'Introduction quoted text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Scripture quotations, or other quoted text, appearing in the introduction', 'level': 'Internal', 'occursIn': 'Introduction'}),
  ('imte', {'nestsFlag': False, 'nameEnglish': 'Introduction major title ending', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'Used to mark a major title indicating the end of the introduction', 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('ie', {'nestsFlag': False, 'nameEnglish': 'Introduction end', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Optionally included to explicitly indicate the end of the introduction material', 'level': 'Newline', 'occursIn': 'Introduction'}),
  ('mt', {'nestsFlag': False, 'nameEnglish': 'Major title', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'The key components in the title of a biblical book', 'level': 'Newline', 'occursIn': 'Header'}),
  ('mte', {'nestsFlag': False, 'nameEnglish': 'Major title at ending', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'May be used in texts which repeat the main title at the end of the introduction, or to mark a major title indicating the end of the introduction. The content is not typically identical to \\mt#.', 'level': 'Newline', 'occursIn': 'Text'}),
  ('ms', {'nestsFlag': False, 'nameEnglish': 'Major section heading', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'These are headings before larger text divisions than what is typically considered a "section" division (see \\s#)', 'level': 'Newline', 'occursIn': 'Text'}),
  ('mr', {'nestsFlag': False, 'nameEnglish': 'Major section reference range', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'The text reference range listed under a major section heading. Perhaps it could be described as the verse range which the \\ms major section heading above it applies to.', 'level': 'Newline', 'occursIn': 'Text'}),
  ('s', {'nestsFlag': False, 'nameEnglish': 'Section heading', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'The typical (common) section division heading', 'level': 'Newline', 'occursIn': 'Text'}),
  ('sr', {'nestsFlag': False, 'nameEnglish': 'Section reference range', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'The text reference range listed under a section heading. \\sr is not equivalent to \\r which is used for marking parallel references. Perhaps it could be described as the verse range which the \\s section heading above it applies to.', 'level': 'Newline', 'occursIn': 'Text'}),
  ('r', {'nestsFlag': False, 'nameEnglish': 'Parallel passage reference(s)', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'A reference to a parallel passage usually located under a section heading \\s#', 'level': 'Newline', 'occursIn': 'Text'}),
  ('rq', {'nestsFlag': False, 'nameEnglish': 'Inline quotation reference(s)', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'A (cross) reference indicating the source text for the preceding quotation (usually an Old Testament quote). The reference(s) are intended to be formatted (typeset) within the scripture body text column, and not extracted from the text as are regular cross-references (\\x...\\x*). They are also typically separated from the main text of Scripture using a different type style and alignment.', 'level': 'Internal', 'occursIn': 'Text'}),
  ('d', {'nestsFlag': False, 'nameEnglish': 'Descriptive title (or "Hebrew subtitle")', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Sometimes used in Psalms under the section title (e.g. "For the director of Music")', 'level': 'Newline', 'occursIn': 'Text'}),
  ('sp', {'nestsFlag': False, 'nameEnglish': 'Speaker Identification', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': '(e.g. Job and Song of Songs)', 'level': 'Newline', 'occursIn': 'Text'}),
  ('c', {'nestsFlag': False, 'nameEnglish': 'Chapter number', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': True, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'No text should follow this marker (i.e., after the chapter number? But some versions have footnotes here!', 'level': 'Newline', 'occursIn': 'Numbering'}),
  ('ca', {'nestsFlag': False, 'nameEnglish': 'Alternate (second) chapter number', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Used for marking the chapter number used in an alternate versification scheme. Required when different versification traditions need to be supported in the same translation text.', 'level': 'Internal', 'occursIn': 'Numbering'}),
  ('cl', {'nestsFlag': False, 'nameEnglish': 'Chapter label', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Used when the chosen publishing presentation will render chapter divisions as headings, and not drop cap numerals. Usage note: If \\cl is entered once before chapter 1 (\\c 1) it represents the text for "chapter" to be used throughout the current book. If \\cl is used after each individual chapter marker, it represents the particular text to be used for the display of the current chapter heading (usually done if numbers are being presented as words, not numerals).', 'level': 'Newline', 'occursIn': 'Numbering'}),
  ('cp', {'nestsFlag': False, 'nameEnglish': 'Published chapter character', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'This is a chapter marker (number, letter) which would be displayed in the published text (where the published marker is different than the \\c # used within the translation editing environment)', 'level': 'Newline', 'occursIn': 'Numbering'}),
  ('cd', {'nestsFlag': False, 'nameEnglish': 'Chapter description', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'A brief description of chapter content (similar to \\d - descriptive heading, or \\iex - )', 'level': 'Newline', 'occursIn': 'Text'}),
  ('v', {'nestsFlag': False, 'nameEnglish': 'Verse number', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': True, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Marker is followed by the verse number #, and the text of the verse', 'level': 'Newline', 'occursIn': 'Numbering'}),
  ('va', {'nestsFlag': False, 'nameEnglish': 'Alternate (second) verse number', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Used for marking verse numbers used in an alternate versification scheme. Required when different versification traditions need to be supported in the same translation text.', 'level': 'Internal', 'occursIn': 'Numbering'}),
  ('vp', {'nestsFlag': False, 'nameEnglish': 'Published verse character', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'This is a verse marker (number, letter) which would be displayed in the published text (where the published marker is different than the \\v # used within the translation editing environment)', 'level': 'Internal', 'occursIn': 'Numbering'}),
  ('p', {'nestsFlag': False, 'nameEnglish': 'Normal paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': False, 'description': 'Followed immediately by a space and paragraph text, or by a new line and a verse marker', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('m', {'nestsFlag': False, 'nameEnglish': 'Flush left (margin) paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': False, 'description': 'No first line indent. Followed immediately by a space and paragraph text, or by a new line and a verse marker. Usually used to resume prose at the margin (without indent) after poetry or OT quotation (i.e. continuation of the previous paragraph).', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('pmo', {'nestsFlag': False, 'nameEnglish': 'Embedded text opening', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('pm', {'nestsFlag': False, 'nameEnglish': 'Embedded text paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('pmc', {'nestsFlag': False, 'nameEnglish': 'Embedded text closing', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('pmr', {'nestsFlag': False, 'nameEnglish': 'Embedded text refrain', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('pi', {'nestsFlag': False, 'nameEnglish': 'Indented paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': True, 'description': 'Used in some texts for discourse sections. The variable # represents the level of indent.\n        See also \\pm.', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('mi', {'nestsFlag': False, 'nameEnglish': 'Indented flush left paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': False, 'description': 'No first line indent', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('nb', {'nestsFlag': False, 'nameEnglish': 'No-break paragraph continuation', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': 'No', 'numberableFlag': False, 'description': 'Indicates "no-break" with previous paragraph (regardless of previous paragraph type).\n        Commonly used in cases where the previous paragraph spans the chapter boundary.\n        No-break markup within poetry: Some translations have a publishing tradition of inserting a small\n            amount of additional white-space at chapter boundaries.\n        It is important in these texts to use the b marker within any specific poetic contexts where\n            no visible break in the flow of the the text is intended at a particular chapter boundary.', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('cls', {'nestsFlag': False, 'nameEnglish': 'Closure of an epistle/letter', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Similar to "With love," or "Sincerely yours,"', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('li', {'nestsFlag': False, 'nameEnglish': 'List item', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': True, 'description': 'An out-dented paragraph meant to highlight the items of a list.\n        Lists may be used to markup the elements of a recurrent structure, such as the days within the creation account,\n            or the Decalogue (10 commandments). The variable # represents the level of indent.', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('pc', {'nestsFlag': False, 'nameEnglish': 'Centered paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': False, 'description': 'Recommended for inscriptions', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('pr', {'nestsFlag': False, 'nameEnglish': 'Right-aligned paragraph', 'deprecatedFlag': True, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged). Recommended alternate: \\pmr', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('ph', {'nestsFlag': False, 'nameEnglish': 'Indented paragraph with hanging indent', 'deprecatedFlag': True, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': True, 'description': '"Deprecated" (i.e. use is strongly discouraged).\n        The variable # represents the level of overall paragraph indent.', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('b', {'nestsFlag': False, 'nameEnglish': 'Blank line', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': 'No', 'numberableFlag': False, 'description': 'May be used to explicitly indicate additional white space between paragraphs.\n        No text should follow this marker, and it should not be used before or after titles to indicate white-space.\n        Also use for stanza breaks in poetry, or between poetry and prose.', 'level': 'Newline', 'occursIn': 'Text, Poetry'}),
  ('q', {'nestsFlag': False, 'nameEnglish': 'Poetic line', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': True, 'description': 'The variable # represents the level of indent (i.e. \\q1, \\q2, \\q3 etc.)', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('qr', {'nestsFlag': False, 'nameEnglish': 'Right-aligned poetic line', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'Common use: Poetic refrain', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('qc', {'nestsFlag': False, 'nameEnglish': 'Centered poetic line', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('qs', {'nestsFlag': False, 'nameEnglish': 'Selah field', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Used for the expression "Selah" commonly found in Psalms and Habakkuk. This text is frequently right aligned, and rendered on the same line as the previous poetic text, if space allows.', 'level': 'Internal', 'occursIn': 'Canonical Text'}),
  ('qa', {'nestsFlag': False, 'nameEnglish': 'Acrostic heading', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('qac', {'nestsFlag': False, 'nameEnglish': 'Acrostic letter', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Marker to indicate the acrostic letter within a poetic line', 'level': 'Internal', 'occursIn': 'Acrostic verse'}),
  ('qm', {'nestsFlag': False, 'nameEnglish': 'Embedded text poetic line', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'The variable # represents the level of indent (i.e. \\qm1, \\qm2 etc.)', 'level': 'Newline', 'occursIn': 'Canonical Text'}),
  ('tr', {'nestsFlag': False, 'nameEnglish': 'Table row start', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'The first \\tr initiates a new table. Rows contain column headings or cells', 'level': 'Newline', 'occursIn': 'Text'}),
  ('th', {'nestsFlag': False, 'nameEnglish': 'Table column heading', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'The variable # represents the table column number', 'level': 'Internal', 'occursIn': 'Table row'}),
  ('thr', {'nestsFlag': False, 'nameEnglish': 'Right-aligned table column heading', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'The variable # represents the table column number', 'level': 'Internal', 'occursIn': 'Table row'}),
  ('tc', {'nestsFlag': False, 'nameEnglish': 'Table cell', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'The variable # represents the table column number. An empty table cell still requires a corresponding marker in the table text.', 'level': 'Internal', 'occursIn': 'Table row'}),
  ('tcr', {'nestsFlag': False, 'nameEnglish': 'Right-aligned table cell', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': True, 'description': 'The variable # represents the table column number. An empty table cell still requires a corresponding marker in the table text.', 'level': 'Internal', 'occursIn': 'Table row'}),
  ('f', {'nestsFlag': False, 'nameEnglish': 'Footnote', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Footnotes are entered inline within the main scripture body text. The boundaries of the footnote text are defined by an opening and closing marker.', 'level': 'Internal', 'occursIn': 'Text'}),
  ('e', {'nestsFlag': False, 'nameEnglish': 'Endnote', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Endnotes are entered inline within the main scripture body text. The boundaries of the endnote text are defined by an opening and closing marker.', 'level': 'Internal', 'occursIn': 'Text'}),
  ('fr', {'nestsFlag': False, 'nameEnglish': 'Footnote "origin" reference', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'This is the chapter and verse(s) that note refers to. Chapter and verse numbers must have a separator between them.', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('fk', {'nestsFlag': False, 'nameEnglish': 'Footnote keyword', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'The specific keyword/term from the text for which the footnote is being provided.', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('fq', {'nestsFlag': False, 'nameEnglish': 'Footnote translation quotation', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'A quotation from the current scripture text translation for which the note is being provided. Longer quotations are sometimes shortened using an ellipsis (i.e. suspension dots "..."). Many existing translation texts have marked both quotations from the existing translation text, as well as alternative translations, using \\fq. An additional marker – \\fqa – is provided for marking alternative translations, and can be used to distinguish between quotations and alternatives.', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('fqa', {'nestsFlag': False, 'nameEnglish': 'Footnote alternate translation', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'Used to distinguish between a quotation of the current scripture text translation, and an alternate translation', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('fl', {'nestsFlag': False, 'nameEnglish': 'Footnote "label" text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'Can be used for marking or "labeling" a word or words which are used consistently across certain types of translation notes (such as the words "Or" in an alternative translation note, "Others", "Heb.", "LXX" etc.)', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('fp', {'nestsFlag': False, 'nameEnglish': 'Footnote additional paragraph', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'Use this marker to if you need to indicate the start of a new paragraph within a footnote (uncommon in standard Bible notes)', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('fv', {'nestsFlag': False, 'nameEnglish': 'Footnote verse number', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'To mark the location of a verse number in the the text quotation or alternative translation', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('ft', {'nestsFlag': False, 'nameEnglish': 'Footnote text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'The essential (explanatory) text of the footnote', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('fdc', {'nestsFlag': False, 'nameEnglish': 'Deuterocanon footnote text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Text between these markers is material to be included only in published editions that contain the Deuterocanonical books.', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('fm', {'nestsFlag': False, 'nameEnglish': 'Footnote reference mark', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Used where two or more locations in the scripture text should ideally refer the reader to the same footnote text (as seen in identical footnote text which is referred to at Gen 2.9 and Gen 2.17 in some English translations). Because the nature of this marker is related directly to the published form of the text, it is not intended for use in scripture authoring. It may be used during the publishing process to connect two callers to the same footnote text.', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('x', {'nestsFlag': False, 'nameEnglish': 'Cross-reference', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Cross-references are entered inline within the main scripture body text. The boundaries of the cross-reference text are defined by an opening and closing marker.', 'level': 'Internal', 'occursIn': 'Text'}),
  ('xo', {'nestsFlag': False, 'nameEnglish': 'Cross-reference "origin" reference', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'This is the chapter and verse(s) that note refers to. Chapter and verse numbers must have a separator between them.', 'level': 'Internal', 'occursIn': 'Cross-reference'}),
  ('xk', {'nestsFlag': False, 'nameEnglish': 'Cross-reference keyword', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'A keyword from the scripture translation text which the target reference(s) also refer to', 'level': 'Internal', 'occursIn': 'Cross-reference'}),
  ('xq', {'nestsFlag': False, 'nameEnglish': 'Cross-reference quotation', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'A quotation from the scripture text. Use of a quotation would be intended to help the reader to understand the portion of text (or concept) for which the target reference(s) are being supplied.', 'level': 'Internal', 'occursIn': 'Cross-reference'}),
  ('xt', {'nestsFlag': False, 'nameEnglish': 'Target reference(s)', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': 'The list of target scripture locations being provided as alternate references to the text (or concept) of the origin reference. This is a list of book name abbreviations and chapter + verse references, separated by semicolons (though there may be an alternate references format for this list in different areas and countries).', 'level': 'Internal', 'occursIn': 'Cross-reference'}),
  ('xot', {'nestsFlag': False, 'nameEnglish': 'Old Testament reference(s)', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the Old Testament books. (optional)', 'level': 'Internal', 'occursIn': 'Cross-reference'}),
  ('xnt', {'nestsFlag': False, 'nameEnglish': 'New Testament reference(s)', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the New Testament books. (optional)', 'level': 'Internal', 'occursIn': 'Cross-reference'}),
  ('xdc', {'nestsFlag': False, 'nameEnglish': 'Deuterocanon reference(s)', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the Deuterocanonical books. (optional)', 'level': 'Internal', 'occursIn': 'Cross-reference'}),
  ('add', {'nestsFlag': True, 'nameEnglish': "Translator's addition", 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': "A translator's explanation; words added by the translator for clarity – text which is not literally a part of the original language, but which was supplied to make the meaning of the original clear", 'level': 'Internal', 'occursIn': 'Text'}),
  ('bk', {'nestsFlag': True, 'nameEnglish': 'Quoted book title', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('dc', {'nestsFlag': False, 'nameEnglish': 'Deuterocanonical addition', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Deuterocanonical/LXX additions or insertions in the Protocanonical text', 'level': 'Internal', 'occursIn': 'Text'}),
  ('k', {'nestsFlag': False, 'nameEnglish': 'Keyword/keyterm', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('lit', {'nestsFlag': False, 'nameEnglish': 'Liturgical note/comment', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': 'e.g. a guide which tells the reader/worshipper that he should recite a prayer or recitation etc.', 'level': 'Newline', 'occursIn': 'Text'}),
  ('nd', {'nestsFlag': True, 'nameEnglish': 'Name of God/Deity', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('ord', {'nestsFlag': True, 'nameEnglish': 'Ordinal number ending', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'i.e. in "1st"', 'level': 'Internal', 'occursIn': 'Text'}),
  ('pn', {'nestsFlag': True, 'nameEnglish': 'Proper name', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('qt', {'nestsFlag': True, 'nameEnglish': 'Quoted text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Old Testament quotations in the New Testament, or other quotations', 'level': 'Internal', 'occursIn': 'Text'}),
  ('sig', {'nestsFlag': True, 'nameEnglish': 'Signature', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'of the author of an epistle/letter', 'level': 'Internal', 'occursIn': 'Text'}),
  ('sls', {'nestsFlag': False, 'nameEnglish': 'Secondary language source', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Passage of text based on a secondary language or alternate text source. E.g. The NBS02 has large sections of text in EZR and DAN in italics, to represent where the original text is in Aramaic, not Hebrew.', 'level': 'Internal', 'occursIn': 'Text'}),
  ('tl', {'nestsFlag': True, 'nameEnglish': 'Transliterated word(s)', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Or foreign words', 'level': 'Internal', 'occursIn': 'Text'}),
  ('wj', {'nestsFlag': True, 'nameEnglish': 'Words of Jesus', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('em', {'nestsFlag': True, 'nameEnglish': 'Emphasis text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('bd', {'nestsFlag': True, 'nameEnglish': 'Bold text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('it', {'nestsFlag': True, 'nameEnglish': 'Italic text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('bdit', {'nestsFlag': False, 'nameEnglish': 'Bold-italic text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('no', {'nestsFlag': True, 'nameEnglish': 'Normal text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('sc', {'nestsFlag': True, 'nameEnglish': 'Small-caps text', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('pb', {'nestsFlag': False, 'nameEnglish': 'Page break', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Text'}),
  ('fig', {'nestsFlag': False, 'nameEnglish': 'Figure', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': None, 'level': 'Internal', 'occursIn': 'Text'}),
  ('ndx', {'nestsFlag': False, 'nameEnglish': 'Subject index entry', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the subject index', 'level': 'Internal', 'occursIn': 'Text'}),
  ('pro', {'nestsFlag': False, 'nameEnglish': 'Pronunciation information', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Used for Chinese/Japanese/Korean texts', 'level': 'Internal', 'occursIn': 'Text'}),
  ('w', {'nestsFlag': False, 'nameEnglish': 'Wordlist/glossary/dictionary entry', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the word list', 'level': 'Internal', 'occursIn': 'Text'}),
  ('wg', {'nestsFlag': False, 'nameEnglish': 'Greek wordlist entry', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the Greek word list', 'level': 'Internal', 'occursIn': 'Text'}),
  ('wh', {'nestsFlag': False, 'nameEnglish': 'Hebrew wordlist entry', 'deprecatedFlag': False, 'printedFlag': False, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Surround word(s) with this markup to indicate that it should appear in the Hebrew word list', 'level': 'Internal', 'occursIn': 'Text'}),
  ('periph', {'nestsFlag': False, 'nameEnglish': 'Peripheral content', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': None, 'level': 'Newline', 'occursIn': 'Front and back matter'}),
  ('ef', {'nestsFlag': False, 'nameEnglish': 'Extended footnote', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Extended footnotes (for study Bibles) are entered inline within the main scripture body text. The boundaries of the footnote text are defined by an opening and closing marker.', 'level': 'Internal', 'occursIn': 'Text'}),
  ('fs', {'nestsFlag': False, 'nameEnglish': 'Footnote summary', 'deprecatedFlag': True, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'numberableFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged). A summary text for the concept/idea/quotation from the current Scripture text translation for which the note is being provided.', 'level': 'Internal', 'occursIn': 'Footnote'}),
  ('ex', {'nestsFlag': False, 'nameEnglish': 'Extended cross-reference', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Extended cross-references (for study Bibles) are entered inline within the main scripture body text. The boundaries of the cross-reference text are defined by an opening and closing marker.', 'level': 'Internal', 'occursIn': 'Text'}),
  ('esb', {'nestsFlag': False, 'nameEnglish': 'Sidebar content', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': 'No', 'numberableFlag': False, 'description': 'In study Bibles. Finishes at next \\esb marker or at end of chapter.', 'level': 'Newline', 'occursIn': 'Text'}),
  ('cat', {'nestsFlag': False, 'nameEnglish': 'Category tag', 'deprecatedFlag': False, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': 'Categories can optionally be assigned to extended study notes or sidebars by supplying a category tag (name) inside of opening and closing \\cat ... \\cat* markers. Category tags should be restricted to alpha-numeric characters. A list of category tags are defined individually and uniquely for each study Bible project.', 'level': 'Internal', 'occursIn': 'Text'}),
  ('pdi', {'nestsFlag': False, 'nameEnglish': 'PDI', 'deprecatedFlag': True, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. Substituted with embedded text markup.', 'level': 'Newline', 'occursIn': 'Text'}),
  ('pde', {'nestsFlag': False, 'nameEnglish': 'PDE', 'deprecatedFlag': True, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'No', 'numberableFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. Substituted with embedded text markup.', 'level': 'Newline', 'occursIn': 'Text'}),
  ('wr', {'nestsFlag': True, 'nameEnglish': 'WR', 'deprecatedFlag': True, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'numberableFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. Was really a duplicate of \\w ... \\w* used for marking words in the Scripture text which are included in the wordlist.', 'level': 'Internal', 'occursIn': 'Text'}),
  ('ps', {'nestsFlag': False, 'nameEnglish': 'Span paragraph', 'deprecatedFlag': True, 'printedFlag': True, 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': 'No', 'numberableFlag': False, 'description': '"Deprecated" (i.e. use is strongly discouraged) in 2004 for USFM 2.0. This was used in conjunction with \\nb to indicate that the paragraph spans the chapter boundary. It should be sufficient to just start the new chapter with \\nb and use the appropriate paragraph marker for the previous chapter (\\p, \\m, etc.).', 'level': 'Newline', 'occursIn': 'Text'}),
]), # end of rawMarkerDict (128 entries)

numberedMarkerList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'ide', # 1
  'sts', # 2
  'rem', # 3
  'h', # 4
  'toc1', # 5
  'toc2', # 6
  'toc3', # 7
  'imt1', # 8
  'imt2', # 9
  'imt3', # 10
  'imt4', # 11
  'is1', # 12
  'is2', # 13
  'is3', # 14
  'is4', # 15
  'ip', # 16
  'ipi', # 17
  'im', # 18
  'imi', # 19
  'ipq', # 20
  'imq', # 21
  'ipr', # 22
  'iq1', # 23
  'iq2', # 24
  'iq3', # 25
  'iq4', # 26
  'ib', # 27
  'ili1', # 28
  'ili2', # 29
  'ili3', # 30
  'ili4', # 31
  'iot', # 32
  'io1', # 33
  'io2', # 34
  'io3', # 35
  'io4', # 36
  'ior', # 37
  'iex', # 38
  'iqt', # 39
  'imte1', # 40
  'imte2', # 41
  'imte3', # 42
  'imte4', # 43
  'ie', # 44
  'mt1', # 45
  'mt2', # 46
  'mt3', # 47
  'mt4', # 48
  'mte1', # 49
  'mte2', # 50
  'mte3', # 51
  'mte4', # 52
  'ms1', # 53
  'ms2', # 54
  'ms3', # 55
  'ms4', # 56
  'mr', # 57
  's1', # 58
  's2', # 59
  's3', # 60
  's4', # 61
  'sr', # 62
  'r', # 63
  'rq', # 64
  'd', # 65
  'sp', # 66
  'c', # 67
  'ca', # 68
  'cl', # 69
  'cp', # 70
  'cd', # 71
  'v', # 72
  'va', # 73
  'vp', # 74
  'p', # 75
  'm', # 76
  'pmo', # 77
  'pm', # 78
  'pmc', # 79
  'pmr', # 80
  'pi1', # 81
  'pi2', # 82
  'pi3', # 83
  'pi4', # 84
  'mi', # 85
  'nb', # 86
  'cls', # 87
  'li1', # 88
  'li2', # 89
  'li3', # 90
  'li4', # 91
  'pc', # 92
  'pr', # 93
  'ph1', # 94
  'ph2', # 95
  'ph3', # 96
  'ph4', # 97
  'b', # 98
  'q1', # 99
  'q2', # 100
  'q3', # 101
  'q4', # 102
  'qr', # 103
  'qc', # 104
  'qs', # 105
  'qa', # 106
  'qac', # 107
  'qm1', # 108
  'qm2', # 109
  'qm3', # 110
  'qm4', # 111
  'tr', # 112
  'th1', # 113
  'th2', # 114
  'th3', # 115
  'th4', # 116
  'thr1', # 117
  'thr2', # 118
  'thr3', # 119
  'thr4', # 120
  'tc1', # 121
  'tc2', # 122
  'tc3', # 123
  'tc4', # 124
  'tcr1', # 125
  'tcr2', # 126
  'tcr3', # 127
  'tcr4', # 128
  'f', # 129
  'e', # 130
  'fr', # 131
  'fk', # 132
  'fq', # 133
  'fqa', # 134
  'fl', # 135
  'fp', # 136
  'fv', # 137
  'ft', # 138
  'fdc', # 139
  'fm', # 140
  'x', # 141
  'xo', # 142
  'xk', # 143
  'xq', # 144
  'xt', # 145
  'xot', # 146
  'xnt', # 147
  'xdc', # 148
  'add', # 149
  'bk', # 150
  'dc', # 151
  'k', # 152
  'lit', # 153
  'nd', # 154
  'ord', # 155
  'pn', # 156
  'qt', # 157
  'sig', # 158
  'sls', # 159
  'tl', # 160
  'wj', # 161
  'em', # 162
  'bd', # 163
  'it', # 164
  'bdit', # 165
  'no', # 166
  'sc', # 167
  'pb', # 168
  'fig', # 169
  'ndx', # 170
  'pro', # 171
  'w', # 172
  'wg', # 173
  'wh', # 174
  'periph', # 175
  'ef', # 176
  'fs', # 177
  'ex', # 178
  'esb', # 179
  'cat', # 180
  'pdi', # 181
  'pde', # 182
  'wr', # 183
  'ps', # 184
], # end of numberedMarkerList (185 entries)

backConversionDict = {
  # Key is numberedMarker
  # Fields (1) are: rawMarker
  'ili1': 'ili',
  'ili2': 'ili',
  'ili3': 'ili',
  'ili4': 'ili',
  'imt1': 'imt',
  'imt2': 'imt',
  'imt3': 'imt',
  'imt4': 'imt',
  'imte1': 'imte',
  'imte2': 'imte',
  'imte3': 'imte',
  'imte4': 'imte',
  'io1': 'io',
  'io2': 'io',
  'io3': 'io',
  'io4': 'io',
  'iq1': 'iq',
  'iq2': 'iq',
  'iq3': 'iq',
  'iq4': 'iq',
  'is1': 'is',
  'is2': 'is',
  'is3': 'is',
  'is4': 'is',
  'li1': 'li',
  'li2': 'li',
  'li3': 'li',
  'li4': 'li',
  'ms1': 'ms',
  'ms2': 'ms',
  'ms3': 'ms',
  'ms4': 'ms',
  'mt1': 'mt',
  'mt2': 'mt',
  'mt3': 'mt',
  'mt4': 'mt',
  'mte1': 'mte',
  'mte2': 'mte',
  'mte3': 'mte',
  'mte4': 'mte',
  'ph1': 'ph',
  'ph2': 'ph',
  'ph3': 'ph',
  'ph4': 'ph',
  'pi1': 'pi',
  'pi2': 'pi',
  'pi3': 'pi',
  'pi4': 'pi',
  'q1': 'q',
  'q2': 'q',
  'q3': 'q',
  'q4': 'q',
  'qm1': 'qm',
  'qm2': 'qm',
  'qm3': 'qm',
  'qm4': 'qm',
  's1': 's',
  's2': 's',
  's3': 's',
  's4': 's',
  'tc1': 'tc',
  'tc2': 'tc',
  'tc3': 'tc',
  'tc4': 'tc',
  'tcr1': 'tcr',
  'tcr2': 'tcr',
  'tcr3': 'tcr',
  'tcr4': 'tcr',
  'th1': 'th',
  'th2': 'th',
  'th3': 'th',
  'th4': 'th',
  'thr1': 'thr',
  'thr2': 'thr',
  'thr3': 'thr',
  'thr4': 'thr',
}
# end of backConversionDict (76 entries)

deprecatedMarkersList = [
    # Fields (1) are: rawMarker
  'pr', # 0
  'ph1', # 1
  'ph2', # 2
  'ph3', # 3
  'ph4', # 4
  'fs', # 5
  'pdi', # 6
  'pde', # 7
  'wr', # 8
  'ps', # 9
], # end of deprecatedMarkersList (10 entries)

combinedNewlineMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'ide', # 1
  'sts', # 2
  'rem', # 3
  'h', # 4
  'toc1', # 5
  'toc2', # 6
  'toc3', # 7
  'imt', # 8
  'imt1', # 9
  'imt2', # 10
  'imt3', # 11
  'imt4', # 12
  'is', # 13
  'is1', # 14
  'is2', # 15
  'is3', # 16
  'is4', # 17
  'ip', # 18
  'ipi', # 19
  'im', # 20
  'imi', # 21
  'ipq', # 22
  'imq', # 23
  'ipr', # 24
  'iq', # 25
  'iq1', # 26
  'iq2', # 27
  'iq3', # 28
  'iq4', # 29
  'ib', # 30
  'ili', # 31
  'ili1', # 32
  'ili2', # 33
  'ili3', # 34
  'ili4', # 35
  'iot', # 36
  'io', # 37
  'io1', # 38
  'io2', # 39
  'io3', # 40
  'io4', # 41
  'iex', # 42
  'imte', # 43
  'imte1', # 44
  'imte2', # 45
  'imte3', # 46
  'imte4', # 47
  'ie', # 48
  'mt', # 49
  'mt1', # 50
  'mt2', # 51
  'mt3', # 52
  'mt4', # 53
  'mte', # 54
  'mte1', # 55
  'mte2', # 56
  'mte3', # 57
  'mte4', # 58
  'ms', # 59
  'ms1', # 60
  'ms2', # 61
  'ms3', # 62
  'ms4', # 63
  'mr', # 64
  's', # 65
  's1', # 66
  's2', # 67
  's3', # 68
  's4', # 69
  'sr', # 70
  'r', # 71
  'd', # 72
  'sp', # 73
  'c', # 74
  'cl', # 75
  'cp', # 76
  'cd', # 77
  'v', # 78
  'p', # 79
  'm', # 80
  'pmo', # 81
  'pm', # 82
  'pmc', # 83
  'pmr', # 84
  'pi', # 85
  'pi1', # 86
  'pi2', # 87
  'pi3', # 88
  'pi4', # 89
  'mi', # 90
  'nb', # 91
  'cls', # 92
  'li', # 93
  'li1', # 94
  'li2', # 95
  'li3', # 96
  'li4', # 97
  'pc', # 98
  'pr', # 99
  'ph', # 100
  'ph1', # 101
  'ph2', # 102
  'ph3', # 103
  'ph4', # 104
  'b', # 105
  'q', # 106
  'q1', # 107
  'q2', # 108
  'q3', # 109
  'q4', # 110
  'qr', # 111
  'qc', # 112
  'qa', # 113
  'qm', # 114
  'qm1', # 115
  'qm2', # 116
  'qm3', # 117
  'qm4', # 118
  'tr', # 119
  'lit', # 120
  'pb', # 121
  'periph', # 122
  'esb', # 123
  'pdi', # 124
  'pde', # 125
  'ps', # 126
], # end of combinedNewlineMarkersList (127 entries)

newlineMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'ide', # 1
  'sts', # 2
  'rem', # 3
  'h', # 4
  'toc1', # 5
  'toc2', # 6
  'toc3', # 7
  'imt', # 8
  'is', # 9
  'ip', # 10
  'ipi', # 11
  'im', # 12
  'imi', # 13
  'ipq', # 14
  'imq', # 15
  'ipr', # 16
  'iq', # 17
  'ib', # 18
  'ili', # 19
  'iot', # 20
  'io', # 21
  'iex', # 22
  'imte', # 23
  'ie', # 24
  'mt', # 25
  'mte', # 26
  'ms', # 27
  'mr', # 28
  's', # 29
  'sr', # 30
  'r', # 31
  'd', # 32
  'sp', # 33
  'c', # 34
  'cl', # 35
  'cp', # 36
  'cd', # 37
  'v', # 38
  'p', # 39
  'm', # 40
  'pmo', # 41
  'pm', # 42
  'pmc', # 43
  'pmr', # 44
  'pi', # 45
  'mi', # 46
  'nb', # 47
  'cls', # 48
  'li', # 49
  'pc', # 50
  'pr', # 51
  'ph', # 52
  'b', # 53
  'q', # 54
  'qr', # 55
  'qc', # 56
  'qa', # 57
  'qm', # 58
  'tr', # 59
  'lit', # 60
  'pb', # 61
  'periph', # 62
  'esb', # 63
  'pdi', # 64
  'pde', # 65
  'ps', # 66
], # end of newlineMarkersList (67 entries)

internalMarkersList = [
    # Fields (1) are: rawMarker
  'ior', # 0
  'iqt', # 1
  'rq', # 2
  'ca', # 3
  'va', # 4
  'vp', # 5
  'qs', # 6
  'qac', # 7
  'th', # 8
  'thr', # 9
  'tc', # 10
  'tcr', # 11
  'f', # 12
  'e', # 13
  'fr', # 14
  'fk', # 15
  'fq', # 16
  'fqa', # 17
  'fl', # 18
  'fp', # 19
  'fv', # 20
  'ft', # 21
  'fdc', # 22
  'fm', # 23
  'x', # 24
  'xo', # 25
  'xk', # 26
  'xq', # 27
  'xt', # 28
  'xot', # 29
  'xnt', # 30
  'xdc', # 31
  'add', # 32
  'bk', # 33
  'dc', # 34
  'k', # 35
  'nd', # 36
  'ord', # 37
  'pn', # 38
  'qt', # 39
  'sig', # 40
  'sls', # 41
  'tl', # 42
  'wj', # 43
  'em', # 44
  'bd', # 45
  'it', # 46
  'bdit', # 47
  'no', # 48
  'sc', # 49
  'fig', # 50
  'ndx', # 51
  'pro', # 52
  'w', # 53
  'wg', # 54
  'wh', # 55
  'ef', # 56
  'fs', # 57
  'ex', # 58
  'cat', # 59
  'wr', # 60
], # end of internalMarkersList (61 entries)

# end of USFMMarkers_Tables.py