[package]
name = "bible_organisational_system"
version = "0.2.2"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "bible_organisational_system"
crate-type = ["rlib", "cdylib"]

[dependencies]
log.workspace = true
pyo3-log.workspace = true
bos-internals.workspace = true
indexmap = { workspace = true, features = ["rayon"] }
rayon.workspace = true
pyo3.workspace = true
rkyv.workspace = true
thiserror.workspace = true
