[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "bibleorgsys-rust"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
[tool.maturin]
features = ["pyo3/extension-module"]

[tool.rylai]
format = ["uvx ruff format", "uvx ruff check --select I --fix"]

[tool.rylai.output]
python_version = "3.13"
add_header = true
all_include_private = false

[tool.rylai.fallback]
strategy = "any"

[tool.uv]
# Rebuild the extension module if the rust code changes.
cache-keys = [{file = "pyproject.toml"}, {file = "Cargo.toml"}, {file = "**/*.rs"}, {file = "../bos-internals/Cargo.toml"}, {file = "../bos-internals/**/*.rs"}]
