[package]
name = "usfm_markers_py"
version = "0.2.1"
edition.workspace = true

[lib]
name = "usfm_markers_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true, features = ["extension-module", "abi3-py38"] }
usfm_markers = { path = "../usfm_markers", editable = true }  # Local dependency
compact_str.workspace = true
