// DerivedFiles/BibleBooksCodes_Tables.h
//
// This UTF-8 file was automatically generated by BibleBooksCodes.py V0.53 on 2011-05-09 10:02:57.806646
//
// Bible books codes list data
//  Version: 0.51
//  Date: 2011-03-24
//

#ifndef BIBLEBOOKSCODES_Tables_h
#define BIBLEBOOKSCODES_Tables_h

typedef struct referenceAbbreviationDictEntryStruct {
    const unsigned char referenceAbbreviation[3+1];
    const unsigned char* ByzantineAbbreviation;
    const unsigned char* CCELNumberString;
    const int referenceNumber;
    const unsigned char* NETBibleAbbreviation;
    const unsigned char* OSISAbbreviation;
    const unsigned char ParatextAbbreviation[3+1];
    const unsigned char ParatextNumberString[2+1];
    const unsigned char* SBLAbbreviation;
    const unsigned char* SwordAbbreviation;
    const unsigned char* nameEnglish;
    const unsigned char* numExpectedChapters;
    const unsigned char* possibleAlternativeBooks;
} referenceAbbreviationDictEntry;

typedef struct SwordAbbreviationDictEntryStruct {
    const unsigned char* SwordAbbreviation;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} SwordAbbreviationDictEntry;

typedef struct ParatextNumberDictEntryStruct {
    const unsigned char ParatextNumberString[2+1];
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
    const unsigned char ParatextAbbreviation[3+1];
} ParatextNumberDictEntry;

typedef struct referenceNumberDictEntryStruct {
    const int referenceNumber;
    const unsigned char* ByzantineAbbreviation;
    const unsigned char* CCELNumberString;
    const unsigned char* NETBibleAbbreviation;
    const unsigned char* OSISAbbreviation;
    const unsigned char ParatextAbbreviation[3+1];
    const unsigned char ParatextNumberString[2+1];
    const unsigned char* SBLAbbreviation;
    const unsigned char* SwordAbbreviation;
    const unsigned char* nameEnglish;
    const unsigned char* numExpectedChapters;
    const unsigned char* possibleAlternativeBooks;
    const unsigned char referenceAbbreviation[3+1];
} referenceNumberDictEntry;

typedef struct ParatextAbbreviationDictEntryStruct {
    const unsigned char ParatextAbbreviation[3+1];
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
    const unsigned char ParatextNumberString[2+1];
} ParatextAbbreviationDictEntry;

typedef struct ByzantineAbbreviationDictEntryStruct {
    const unsigned char* ByzantineAbbreviation;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} ByzantineAbbreviationDictEntry;

typedef struct SBLDictEntryStruct {
    const unsigned char* SBLAbbreviation;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} SBLDictEntry;

typedef struct EnglishNameDictEntryStruct {
    const unsigned char* nameEnglish;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} EnglishNameDictEntry;

typedef struct CCELDictEntryStruct {
    const unsigned char* CCELNumberString;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} CCELDictEntry;

typedef struct OSISAbbreviationDictEntryStruct {
    const unsigned char* OSISAbbreviation;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} OSISAbbreviationDictEntry;

typedef struct NETBibleAbbreviationDictEntryStruct {
    const unsigned char* NETBibleAbbreviation;
    const int referenceNumber;
    const unsigned char referenceAbbreviation[3+1];
} NETBibleAbbreviationDictEntry;

#endif // BIBLEBOOKSCODES_Tables_h

// end of BibleBooksCodes_Tables.h