# DerivedFiles/USFMMarkers_Tables.py
#
# This UTF-8 file was automatically generated by USFMMarkers.py V0.50 on 2011-03-17 16:24:50.303138
#
# USFM 2.3 markers list data
#  Version: 0.50
#  Date: 2011-03-17
#
#   120 USFMMarkers loaded from the original XML file.
#

from collections import OrderedDict

conversionDict = {
  # Key is rawMarker
  # Fields (1) are: numberedMarker
  'h': 'h1',
  'ili': 'ili1',
  'imt': 'imt1',
  'imte': 'imte1',
  'io': 'io1',
  'iq': 'iq1',
  'is': 'is1',
  'li': 'li1',
  'ms': 'ms1',
  'mt': 'mt1',
  'mte': 'mte1',
  'ph': 'ph1',
  'pi': 'pi1',
  'q': 'q1',
  'qm': 'qm1',
  's': 's1',
  'tc': 'tc1',
  'tcr': 'tcr1',
  'th': 'th1',
  'thr': 'thr1',
}
# end of conversionDict (20 entries)

adjustedMarkerDict = {
  # Key is marker
  # Fields (1) are: rawMarker
  'add': 'add',
  'b': 'b',
  'bd': 'bd',
  'bdit': 'bdit',
  'bk': 'bk',
  'c': 'c',
  'ca': 'ca',
  'cd': 'cd',
  'cl': 'cl',
  'cls': 'cls',
  'cp': 'cp',
  'd': 'd',
  'dc': 'dc',
  'e': 'e',
  'em': 'em',
  'esb': 'esb',
  'f': 'f',
  'fdc': 'fdc',
  'fig': 'fig',
  'fk': 'fk',
  'fl': 'fl',
  'fm': 'fm',
  'fp': 'fp',
  'fq': 'fq',
  'fqa': 'fqa',
  'fr': 'fr',
  'ft': 'ft',
  'fv': 'fv',
  'h': 'h',
  'h1': 'h',
  'h2': 'h',
  'h3': 'h',
  'ib': 'ib',
  'id': 'id',
  'ide': 'ide',
  'ie': 'ie',
  'iex': 'iex',
  'ili': 'ili',
  'ili1': 'ili',
  'ili2': 'ili',
  'ili3': 'ili',
  'im': 'im',
  'imi': 'imi',
  'imq': 'imq',
  'imt': 'imt',
  'imt1': 'imt',
  'imt2': 'imt',
  'imt3': 'imt',
  'imte': 'imte',
  'imte1': 'imte',
  'imte2': 'imte',
  'imte3': 'imte',
  'io': 'io',
  'io1': 'io',
  'io2': 'io',
  'io3': 'io',
  'ior': 'ior',
  'iot': 'iot',
  'ip': 'ip',
  'ipi': 'ipi',
  'ipq': 'ipq',
  'ipr': 'ipr',
  'iq': 'iq',
  'iq1': 'iq',
  'iq2': 'iq',
  'iq3': 'iq',
  'iqt': 'iqt',
  'is': 'is',
  'is1': 'is',
  'is2': 'is',
  'is3': 'is',
  'it': 'it',
  'k': 'k',
  'li': 'li',
  'li1': 'li',
  'li2': 'li',
  'li3': 'li',
  'lit': 'lit',
  'm': 'm',
  'mi': 'mi',
  'mr': 'mr',
  'ms': 'ms',
  'ms1': 'ms',
  'ms2': 'ms',
  'ms3': 'ms',
  'mt': 'mt',
  'mt1': 'mt',
  'mt2': 'mt',
  'mt3': 'mt',
  'mte': 'mte',
  'mte1': 'mte',
  'mte2': 'mte',
  'mte3': 'mte',
  'nb': 'nb',
  'nd': 'nd',
  'ndx': 'ndx',
  'no': 'no',
  'ord': 'ord',
  'p': 'p',
  'pb': 'pb',
  'pc': 'pc',
  'periph': 'periph',
  'ph': 'ph',
  'ph1': 'ph',
  'ph2': 'ph',
  'ph3': 'ph',
  'pi': 'pi',
  'pi1': 'pi',
  'pi2': 'pi',
  'pi3': 'pi',
  'pm': 'pm',
  'pmc': 'pmc',
  'pmo': 'pmo',
  'pmr': 'pmr',
  'pn': 'pn',
  'pr': 'pr',
  'pro': 'pro',
  'q': 'q',
  'q1': 'q',
  'q2': 'q',
  'q3': 'q',
  'qa': 'qa',
  'qac': 'qac',
  'qc': 'qc',
  'qm': 'qm',
  'qm1': 'qm',
  'qm2': 'qm',
  'qm3': 'qm',
  'qr': 'qr',
  'qs': 'qs',
  'qt': 'qt',
  'r': 'r',
  'rem': 'rem',
  'rq': 'rq',
  's': 's',
  's1': 's',
  's2': 's',
  's3': 's',
  'sc': 'sc',
  'sig': 'sig',
  'sls': 'sls',
  'sp': 'sp',
  'sr': 'sr',
  'sts': 'sts',
  'tc': 'tc',
  'tc1': 'tc',
  'tc2': 'tc',
  'tc3': 'tc',
  'tcr': 'tcr',
  'tcr1': 'tcr',
  'tcr2': 'tcr',
  'tcr3': 'tcr',
  'th': 'th',
  'th1': 'th',
  'th2': 'th',
  'th3': 'th',
  'thr': 'thr',
  'thr1': 'thr',
  'thr2': 'thr',
  'thr3': 'thr',
  'tl': 'tl',
  'toc1': 'toc1',
  'toc2': 'toc2',
  'toc3': 'toc3',
  'tr': 'tr',
  'v': 'v',
  'va': 'va',
  'vp': 'vp',
  'w': 'w',
  'wg': 'wg',
  'wh': 'wh',
  'wj': 'wj',
  'x': 'x',
  'xdc': 'xdc',
  'xk': 'xk',
  'xnt': 'xnt',
  'xo': 'xo',
  'xot': 'xot',
  'xq': 'xq',
  'xt': 'xt',
}
# end of adjustedMarkerDict (180 entries)

characterMarkersList = [
    # Fields (1) are: rawMarker
  'ior', # 0
  'iqt', # 1
  'rq', # 2
  'qs', # 3
  'qac', # 4
  'f', # 5
  'e', # 6
  'fr', # 7
  'fk', # 8
  'fq', # 9
  'fqa', # 10
  'fl', # 11
  'fp', # 12
  'fv', # 13
  'ft', # 14
  'fdc', # 15
  'fm', # 16
  'x', # 17
  'xo', # 18
  'xk', # 19
  'xq', # 20
  'xt', # 21
  'xot', # 22
  'xnt', # 23
  'xdc', # 24
  'add', # 25
  'bk', # 26
  'dc', # 27
  'k', # 28
  'nd', # 29
  'ord', # 30
  'pn', # 31
  'qt', # 32
  'sig', # 33
  'sls', # 34
  'tl', # 35
  'wj', # 36
  'em', # 37
  'bd', # 38
  'it', # 39
  'bdit', # 40
  'no', # 41
  'sc', # 42
  'fig', # 43
  'ndx', # 44
  'pro', # 45
  'w', # 46
  'wg', # 47
  'wh', # 48
], # end of characterMarkersList (49 entries)

rawMarkerDict = OrderedDict([
    # Key is rawMarker (in the original XML order)
    # Fields (8) are: specified
  ('id', {'nameEnglish': 'File identification', 'compulsoryFlag': True, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Header', 'description': 'This is the initial USFM marker in any scripture text file'}),
  ('ide', {'nameEnglish': 'An optional character encoding specification', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Header', 'description': 'This marker should be used to specify the character encoding of the text within the file'}),
  ('sts', {'nameEnglish': 'Project status tracking', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Header', 'description': 'The contents of the status marker can be defined by the downstream system being used to track project status'}),
  ('rem', {'nameEnglish': 'Remark/Comment', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Header', 'description': 'Used for adding brief comments by a translator, consultant, or support person'}),
  ('h', {'nameEnglish': 'Running header text', 'compulsoryFlag': True, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Header', 'description': None}),
  ('toc1', {'nameEnglish': 'Long table of contents text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Header', 'description': 'Not for use directly within the front matter (FRT) peripheral file'}),
  ('toc2', {'nameEnglish': 'Short table of contents text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Header', 'description': 'Not for use directly within the front matter (FRT) peripheral file'}),
  ('toc3', {'nameEnglish': 'Book abbreviation', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Header', 'description': 'Not for use directly within the front matter (FRT) peripheral file'}),
  ('imt', {'nameEnglish': 'Introduction main title', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Introduction', 'description': 'May be used for the introduction title or other major introduction division (rather than \\is) when the introduction text contains numerous additional sub-divisions.'}),
  ('is', {'nameEnglish': 'Introduction section heading', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Introduction', 'description': None}),
  ('ip', {'nameEnglish': 'Introduction paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': None}),
  ('ipi', {'nameEnglish': 'Indented introduction paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': None}),
  ('im', {'nameEnglish': 'Introduction flush left (margin) paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': None}),
  ('imi', {'nameEnglish': 'Introduction flush left (margin) indented paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': None}),
  ('ipq', {'nameEnglish': 'Introduction quote from text paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': None}),
  ('imq', {'nameEnglish': 'Introduction flush left (margin) quote from text paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': None}),
  ('ipr', {'nameEnglish': 'Introduction right-aligned paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': 'Typically used for a quote from text reference'}),
  ('iq', {'nameEnglish': 'Introduction poetic line', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Introduction', 'description': None}),
  ('ib', {'nameEnglish': 'Introduction blank line', 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': 'May be used to explicitly indicate additional white space between paragraphs'}),
  ('ili', {'nameEnglish': 'Introduction list item', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Introduction', 'description': None}),
  ('iot', {'nameEnglish': 'Introduction outline title', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': None}),
  ('io', {'nameEnglish': 'Introduction outline entry', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Introduction', 'description': 'The outline entry typically ends with a range of references in parentheses'}),
  ('ior', {'nameEnglish': 'Introduction outline reference range', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': 'An outline entry typically ends with a range of references in parentheses. This is an optional character style for marking (and potentially formatting) these references separately'}),
  ('iex', {'nameEnglish': 'Introduction explanatory or bridge text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': 'e.g. explanation of missing book in a short Old Testament'}),
  ('iqt', {'nameEnglish': 'Introduction quoted text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': 'Scripture quotations, or other quoted text, appearing in the introduction'}),
  ('imte', {'nameEnglish': 'Introduction major title ending', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Introduction', 'description': 'Used to mark a major title indicating the end of the introduction'}),
  ('ie', {'nameEnglish': 'Introduction end', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Introduction', 'description': 'Optionally included to explicitly indicate the end of the introduction material'}),
  ('mt', {'nameEnglish': 'Major title', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': 'The key components in the title of a biblical book'}),
  ('mte', {'nameEnglish': 'Major title at ending', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': 'May be used in texts which repeat the main title at the end of the introduction, or to mark a major title indicating the end of the introduction. The content is not typically identical to \\mt#.'}),
  ('ms', {'nameEnglish': 'Major section heading', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': 'These are headings before larger text divisions than what is typically considered a "section" division (see \\s#)'}),
  ('mr', {'nameEnglish': 'Major section reference range', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'The text reference range listed under a major section heading'}),
  ('s', {'nameEnglish': 'Section heading', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': 'The typical (common) section division heading'}),
  ('sr', {'nameEnglish': 'Section reference range', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'The text reference range listed under a section heading. \\sr is not equivalent to \\r which is used for marking parallel references.'}),
  ('r', {'nameEnglish': 'Parallel passage reference(s)', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'A reference to a parallel passage usually located under a section heading \\s#'}),
  ('rq', {'nameEnglish': 'Inline quotation reference(s)', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'A (cross) reference indicating the source text for the preceding quotation (usually an Old Testament quote). The reference(s) are intended to be formatted (typeset) within the scripture body text column, and not extracted from the text as are regular cross references (\\x...\\x*). They are also typically separated from the main text of Scripture using a different type style and alignment.'}),
  ('d', {'nameEnglish': 'Descriptive title (or "Hebrew subtitle")', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Sometimes used in Psalms under the section title (e.g. "For the director of Music")'}),
  ('sp', {'nameEnglish': 'Speaker Identification', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': '(e.g. Job and Song of Songs)'}),
  ('c', {'nameEnglish': 'Chapter number', 'compulsoryFlag': True, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'No text should follow this marker (i.e., after the chapter number? But some versions have footnotes here!'}),
  ('ca', {'nameEnglish': 'Alternate (second) chapter number', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Used for marking the chapter number used in an alternate versification scheme. Required when different versification traditions need to be supported in the same translation text.'}),
  ('cl', {'nameEnglish': 'Chapter label', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Used when the chosen publishing presentation will render chapter divisions as headings, and not drop cap numerals. Usage note: If \\cl is entered once before chapter 1 (\\c 1) it represents the text for "chapter" to be used throughout the current book. If \\cl is used after each individual chapter marker, it represents the particular text to be used for the display of the current chapter heading (usually done if numbers are being presented as words, not numerals).'}),
  ('cp', {'nameEnglish': 'Published chapter character', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'This is a chapter marker (number, letter) which would be displayed in the published text (where the published marker is different than the \\c # used within the translation editing environment)'}),
  ('cd', {'nameEnglish': 'Chapter description', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'A brief description of chapter content (similar to \\d - descriptive heading, or \\iex - )'}),
  ('v', {'nameEnglish': 'Verse number', 'compulsoryFlag': True, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Marker is followed by the verse number #, and the text of the verse'}),
  ('va', {'nameEnglish': 'Alternate (second) verse number', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Used for marking verse numbers used in an alternate versification scheme. Required when different versification traditions need to be supported in the same translation text.'}),
  ('vp', {'nameEnglish': 'Published verse character', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'This is a verse marker (number, letter) which would be displayed in the published text (where the published marker is different than the \\v # used within the translation editing environment)'}),
  ('p', {'nameEnglish': 'Normal paragraph', 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Followed immediately by a space and paragraph text, or by a new line and a verse marker'}),
  ('m', {'nameEnglish': 'Flush left (margin) paragraph', 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'No first line indent. Followed immediately by a space and paragraph text, or by a new line and a verse marker. Usually used to resume prose at the margin (without indent) after poetry or OT quotation (i.e. continuation of the previous paragraph).'}),
  ('pmo', {'nameEnglish': 'Embedded text opening', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('pm', {'nameEnglish': 'Embedded text paragraph', 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('pmc', {'nameEnglish': 'Embedded text closing', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('pmr', {'nameEnglish': 'Embedded text refrain', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('pi', {'nameEnglish': 'Indented paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': 'Used in some texts for discourse sections. The variable # represents the level of indent. See also \\pm.'}),
  ('mi', {'nameEnglish': 'Indented flush left paragraph', 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'No first line indent'}),
  ('nb', {'nameEnglish': 'No-break paragraph continuation', 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Indicates "no-break" with previous paragraph (regardless of previous paragraph type). Commonly used in cases where the previous paragraph spans the chapter boundary. No-break markup within poetry: Some translations have a publishing tradition of inserting a small amount of additional white-space at chapter boundaries. It is important in these texts to use the \\nb marker within any specific poetic contexts where no visible break in the flow of the the text is intended at a particular chapter boundary.'}),
  ('cls', {'nameEnglish': 'Closure of an epistle/letter', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Similar to "With love," or "Sincerely yours,"'}),
  ('li', {'nameEnglish': 'List item', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': 'An out-dented paragraph meant to highlight the items of a list. Lists may be used to markup the elements of a recurrent structure, such as the days within the creation account, or the Decalogue (10 commandments). The variable # represents the level of indent.'}),
  ('pc', {'nameEnglish': 'Centered paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Recommended for inscriptions'}),
  ('pr', {'nameEnglish': 'Right-aligned paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': '"Deprecated" (i.e. use is strongly discouraged). Recommended alternate: \\pmr'}),
  ('ph', {'nameEnglish': 'Indented paragraph with hanging indent', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': '"Deprecated" (i.e. use is strongly discouraged). The variable # represents the level of overall paragraph indent.'}),
  ('b', {'nameEnglish': 'Blank line', 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text, Poetry', 'description': 'May be used to explicitly indicate additional white space between paragraphs. No text should follow this marker, and it should not be used before or after titles to indicate white-space. Also use for stanza breaks in poetry, or between poetry and prose.'}),
  ('q', {'nameEnglish': 'Poetic line', 'compulsoryFlag': False, 'hasContent': 'Sometimes', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': 'The variable # represents the level of indent (i.e. \\q1, \\q2, \\q3 etc.)'}),
  ('qr', {'nameEnglish': 'Right-aligned poetic line', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Common use: Poetic refrain'}),
  ('qc', {'nameEnglish': 'Centered poetic line', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('qs', {'nameEnglish': 'Selah field', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Poetry', 'description': 'Used for the expression "Selah" commonly found in Psalms and Habakkuk. This text is frequently right aligned, and rendered on the same line as the previous poetic text, if space allows.'}),
  ('qa', {'nameEnglish': 'Acrostic heading', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('qac', {'nameEnglish': 'Acrostic letter', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Acrostic verse', 'description': 'Marker to indicate the acrostic letter within a poetic line'}),
  ('qm', {'nameEnglish': 'Embedded text poetic line', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': 'The variable # represents the level of indent (i.e. \\qm1, \\qm2 etc.)'}),
  ('tr', {'nameEnglish': 'Table row start', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'The first \\tr initiates a new table. Rows contain column headings or cells'}),
  ('th', {'nameEnglish': 'Table column heading', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Text', 'description': 'The variable # represents the table column number'}),
  ('thr', {'nameEnglish': 'Right-aligned table column heading', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Table row', 'description': 'The variable # represents the table column number'}),
  ('tc', {'nameEnglish': 'Table cell', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Table row', 'description': 'The variable # represents the table column number. An empty table cell still requires a corresponding marker in the table text.'}),
  ('tcr', {'nameEnglish': 'Right-aligned table cell', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': True, 'occursIn': 'Table row', 'description': 'The variable # represents the table column number. An empty table cell still requires a corresponding marker in the table text.'}),
  ('f', {'nameEnglish': 'Footnote', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Footnotes are entered inline within the main scripture body text. The boundaries of the footnote text are defined by an opening and closing marker.'}),
  ('e', {'nameEnglish': 'Endnote', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Endnotes are entered inline within the main scripture body text. The boundaries of the endnote text are defined by an opening and closing marker.'}),
  ('fr', {'nameEnglish': 'Footnote "origin" reference', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'This is the chapter and verse(s) that note refers to. Chapter and verse numbers must have a separator between them.'}),
  ('fk', {'nameEnglish': 'Footnote keyword', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'The specific keyword/term from the text for which the footnote is being provided'}),
  ('fq', {'nameEnglish': 'Footnote translation quotation', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'A quotation from the current scripture text translation for which the note is being provided. Longer quotations are sometimes shortened using an ellipsis (i.e. suspension dots "..."). Many existing translation texts have marked both quotations from the existing translation text, as well as alternative translations, using \\fq. An additional marker – \\fqa – is provided for marking alternative translations, and can be used to distinguish between quotations and alternatives.'}),
  ('fqa', {'nameEnglish': 'Footnote alternate translation', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'Used to distinguish between a quotation of the current scripture text translation, and an alternate translation'}),
  ('fl', {'nameEnglish': 'Footnote "label" text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'Can be used for marking or "labeling" a word or words which are used consistently across certain types of translation notes (such as the words "Or" in an alternative translation note, "Others", "Heb.", "LXX" etc.)'}),
  ('fp', {'nameEnglish': 'Footnote additional paragraph', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'Use this marker to if you need to indicate the start of a new paragraph within a footnote (uncommon in standard Bible notes)'}),
  ('fv', {'nameEnglish': 'Footnote verse number', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'To mark the location of a verse number in the the text quotation or alternative translation'}),
  ('ft', {'nameEnglish': 'Footnote text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'The essential (explanatory) text of the footnote'}),
  ('fdc', {'nameEnglish': 'Deuterocanon footnote text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'Text between these markers is material to be included only in published editions that contain the Deuterocanonical books.'}),
  ('fm', {'nameEnglish': 'Footnote reference mark', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Footnote', 'description': 'Used where two or more locations in the scripture text should ideally refer the reader to the same footnote text (as seen in identical footnote text which is referred to at Gen 2.9 and Gen 2.17 in some English translations). Because the nature of this marker is related directly to the published form of the text, it is not intended for use in scripture authoring. It may be used during the publishing process to connect two callers to the same footnote text.'}),
  ('x', {'nameEnglish': 'Cross reference', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Cross references are entered inline within the main scripture body text. The boundaries of the cross reference text are defined by an opening and closing marker.'}),
  ('xo', {'nameEnglish': 'Cross reference "origin" reference', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Cross reference', 'description': 'This is the chapter and verse(s) that note refers to. Chapter and verse numbers must have a separator between them.'}),
  ('xk', {'nameEnglish': 'Cross reference keyword', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Cross reference', 'description': 'A keyword from the scripture translation text which the target reference(s) also refer to'}),
  ('xq', {'nameEnglish': 'Cross reference quotation', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Cross reference', 'description': 'A quotation from the scripture text. Use of a quotation would be intended to help the reader to understand the portion of text (or concept) for which the target reference(s) are being supplied.'}),
  ('xt', {'nameEnglish': 'Target reference(s)', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Optional', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Cross reference', 'description': 'The list of target scripture locations being provided as alternate references to the text (or concept) of the origin reference. This is a list of book name abbreviations and chapter + verse references, separated by semicolons (though there may be an alternate references format for this list in different areas and countries).'}),
  ('xot', {'nameEnglish': 'Old Testament reference(s)', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Cross reference', 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the Old Testament books. (optional)'}),
  ('xnt', {'nameEnglish': 'New Testament reference(s)', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Cross reference', 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the New Testament books. (optional)'}),
  ('xdc', {'nameEnglish': 'Deuterocanon reference(s)', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Cross reference', 'description': 'References (or other text) between these markers is material to be included only in published editions that contain the Deuterocanonical books. (optional)'}),
  ('add', {'nameEnglish': "Translator's addition", 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': "A translator's explanation; words added by the translator for clarity – text which is not literally a part of the original language, but which was supplied to make the meaning of the original clear"}),
  ('bk', {'nameEnglish': 'Quoted book title', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('dc', {'nameEnglish': 'Deuterocanonical addition', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Deuterocanonical/LXX additions or insertions in the Protocanonical text'}),
  ('k', {'nameEnglish': 'Keyword/keyterm', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('lit', {'nameEnglish': 'Liturgical note/comment', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'e.g. a guide which tells the reader/worshipper that he should recite a prayer or recitation etc.'}),
  ('nd', {'nameEnglish': 'Name of God/Deity', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('ord', {'nameEnglish': 'Ordinal number ending', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'i.e. in "1st"'}),
  ('pn', {'nameEnglish': 'Proper name', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('qt', {'nameEnglish': 'Quoted text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Old Testament quotations in the New Testament, or other quotations'}),
  ('sig', {'nameEnglish': 'Signature', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'of the author of an epistle/letter'}),
  ('sls', {'nameEnglish': 'Secondary language source', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Passage of text based on a secondary language or alternate text source. E.g. The NBS02 has large sections of text in EZR and DAN in italics, to represent where the original text is in Aramaic, not Hebrew.'}),
  ('tl', {'nameEnglish': 'Transliterated word(s)', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Or foreign words'}),
  ('wj', {'nameEnglish': 'Words of Jesus', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('em', {'nameEnglish': 'Emphasis text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('bd', {'nameEnglish': 'Bold text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('it', {'nameEnglish': 'Italic text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('bdit', {'nameEnglish': 'Bold-italic text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('no', {'nameEnglish': 'Normal text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('sc', {'nameEnglish': 'Small-caps text', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('pb', {'nameEnglish': 'Page break', 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('fig', {'nameEnglish': 'Figure', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': None}),
  ('ndx', {'nameEnglish': 'Subject index entry', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Surround word(s) with this markup to indicate that it should appear in the subject index'}),
  ('pro', {'nameEnglish': 'Pronunciation information', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Used for Chinese/Japanese/Korean texts'}),
  ('w', {'nameEnglish': 'Wordlist/glossary/dictionary entry', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Surround word(s) with this markup to indicate that it should appear in the word list'}),
  ('wg', {'nameEnglish': 'Greek wordlist entry', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Surround word(s) with this markup to indicate that it should appear in the Greek word list'}),
  ('wh', {'nameEnglish': 'Hebrew wordlist entry', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': 'Always', 'level': 'Character', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'Surround word(s) with this markup to indicate that it should appear in the Hebrew word list'}),
  ('periph', {'nameEnglish': 'Peripheral content', 'compulsoryFlag': False, 'hasContent': 'Always', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Front and back matter', 'description': None}),
  ('esb', {'nameEnglish': 'Sidebar content', 'compulsoryFlag': False, 'hasContent': 'Never', 'closed': None, 'level': 'Paragraph', 'numberableFlag': False, 'occursIn': 'Text', 'description': 'In study Bibles. Finishes at next \\esb marker or at end of chapter.'}),
]), # end of rawMarkerDict (120 entries)

backConversionDict = {
  # Key is numberedMarker
  # Fields (1) are: rawMarker
  'h1': 'h',
  'h2': 'h',
  'h3': 'h',
  'ili1': 'ili',
  'ili2': 'ili',
  'ili3': 'ili',
  'imt1': 'imt',
  'imt2': 'imt',
  'imt3': 'imt',
  'imte1': 'imte',
  'imte2': 'imte',
  'imte3': 'imte',
  'io1': 'io',
  'io2': 'io',
  'io3': 'io',
  'iq1': 'iq',
  'iq2': 'iq',
  'iq3': 'iq',
  'is1': 'is',
  'is2': 'is',
  'is3': 'is',
  'li1': 'li',
  'li2': 'li',
  'li3': 'li',
  'ms1': 'ms',
  'ms2': 'ms',
  'ms3': 'ms',
  'mt1': 'mt',
  'mt2': 'mt',
  'mt3': 'mt',
  'mte1': 'mte',
  'mte2': 'mte',
  'mte3': 'mte',
  'ph1': 'ph',
  'ph2': 'ph',
  'ph3': 'ph',
  'pi1': 'pi',
  'pi2': 'pi',
  'pi3': 'pi',
  'q1': 'q',
  'q2': 'q',
  'q3': 'q',
  'qm1': 'qm',
  'qm2': 'qm',
  'qm3': 'qm',
  's1': 's',
  's2': 's',
  's3': 's',
  'tc1': 'tc',
  'tc2': 'tc',
  'tc3': 'tc',
  'tcr1': 'tcr',
  'tcr2': 'tcr',
  'tcr3': 'tcr',
  'th1': 'th',
  'th2': 'th',
  'th3': 'th',
  'thr1': 'thr',
  'thr2': 'thr',
  'thr3': 'thr',
}
# end of backConversionDict (60 entries)

paragraphMarkersList = [
    # Fields (1) are: rawMarker
  'id', # 0
  'ide', # 1
  'sts', # 2
  'rem', # 3
  'h', # 4
  'toc1', # 5
  'toc2', # 6
  'toc3', # 7
  'imt', # 8
  'is', # 9
  'ip', # 10
  'ipi', # 11
  'im', # 12
  'imi', # 13
  'ipq', # 14
  'imq', # 15
  'ipr', # 16
  'iq', # 17
  'ib', # 18
  'ili', # 19
  'iot', # 20
  'io', # 21
  'iex', # 22
  'imte', # 23
  'ie', # 24
  'mt', # 25
  'mte', # 26
  'ms', # 27
  'mr', # 28
  's', # 29
  'sr', # 30
  'r', # 31
  'd', # 32
  'sp', # 33
  'c', # 34
  'ca', # 35
  'cl', # 36
  'cp', # 37
  'cd', # 38
  'v', # 39
  'va', # 40
  'vp', # 41
  'p', # 42
  'm', # 43
  'pmo', # 44
  'pm', # 45
  'pmc', # 46
  'pmr', # 47
  'pi', # 48
  'mi', # 49
  'nb', # 50
  'cls', # 51
  'li', # 52
  'pc', # 53
  'pr', # 54
  'ph', # 55
  'b', # 56
  'q', # 57
  'qr', # 58
  'qc', # 59
  'qa', # 60
  'qm', # 61
  'tr', # 62
  'th', # 63
  'thr', # 64
  'tc', # 65
  'tcr', # 66
  'lit', # 67
  'pb', # 68
  'periph', # 69
  'esb', # 70
], # end of paragraphMarkersList (71 entries)

# end of USFMMarkers_Tables.py