// DerivedFiles/USFMMarkers_Tables.h
//
// This UTF-8 file was automatically generated by USFMMarkers.py V0.50 on 2011-03-17 14:58:25.339648
//
// USFM 2.3 markers list data
//  Version: 0.50
//  Date: 2011-03-17
//

#ifndef USFMMARKERS_Tables_h
#define USFMMARKERS_Tables_h

