#!/usr/bin/env -S uv run
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: GPL-3.0-or-later
#
# build_static_tables.py
#
# Script taking USFM3Markers TSV data table
#       and formatting it into static declarations in a Rust include file.
#
# Copyright (C) 2026 Robert Hunt
# Author: Robert Hunt <Freely.Given.org+BOS@gmail.com>
# License: See gpl-3.0.txt

"""
Script taking USFM3Markers TSV data table
       and formatting it into static declarations in a Rust include file.
"""
from pathlib import Path
from csv import DictReader
import logging


VERSION_STR = 'v0.1.0'
TSV_SOURCE = Path( 'USFM3Markers_Tables.tsv' )
RUST_SOURCE = Path( 'lib.src.rs' )
RUST_OUTPUT = Path( 'src/lib.rs' )

if __name__ == '__main__':
    print( f"usfm_markers build_static_tables.py {VERSION_STR}" )

    if not TSV_SOURCE.exists():
        print(f"Error: {TSV_SOURCE} not found")
        exit(1)

    with open( TSV_SOURCE, 'rt', encoding='utf-8' ) as tsv_file:
        tsv_lines = tsv_file.readlines()
    print( f"Loaded {len(tsv_lines):,} tsv lines." )

    fullArrayEntries = []
    markerDictEntries = {}

    for n, row in enumerate( DictReader(tsv_lines, delimiter='\t') ):
        marker = row['marker']
        
        compulsory = 'true' if row['compulsory'] == 'Yes' else 'false'
        nests = 'true' if row['nests'] == 'Yes' else 'false'
        printed = 'true' if row['printed'] == 'Yes' else 'false'
        deprecated = 'true' if row['deprecated'] == 'Yes' else 'false'
        
        highest_suffix_val = row['highestNumberSuffix']
        highest_suffix = 'None' if highest_suffix_val == 'None' else f"Some({highest_suffix_val})"
        
        level = row['level'] # Newline, Internal, Note
        has_content = row['hasContent'] # Sometimes, Always, Never
        closed_val = row['closed']
        closed = 'SelfMarker' if closed_val == 'Self' else closed_val
        
        description_raw = row['description'].replace('\\', '\\\\').replace('"', '\\"').replace('\n', ' ')
        description = f'Some("{description_raw}")' if description_raw else 'None'
        name_english = row['nameEnglish'].replace('\\', '\\\\').replace('"', '\\"')
        occurs_in = row['occursIn'].replace('\\', '\\\\').replace('"', '\\"')

        fullArrayEntries.append( f'''    USFMMarkerArrayEntry {{
        name_english: "{name_english}",
        marker: "{marker}",
        compulsory: {compulsory},
        level: USFMMarkerLevel::{level},
        highest_number_suffix: {highest_suffix},
        nests: {nests},
        has_content: USFMMarkerContent::{has_content},
        printed: {printed},
        closed: USFMMarkerClosed::{closed},
        occurs_in: "{occurs_in}",
        deprecated: {deprecated},
        description: {description},
        }},''' )
        
        markerDictEntries[f'"{marker}"'] = f'=>{n},'
        if highest_suffix_val != 'None':
            for i in range(1, int(highest_suffix_val) + 1):
                markerDictEntries[f'"{marker}{i}"'] = f'=>{n},'

    static_rust_structs_str = f'''
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum USFMMarkerLevel {{
    Newline,
    Internal,
    Note,
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum USFMMarkerContent {{
    Sometimes,
    Always,
    Never,
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum USFMMarkerClosed {{
    Always,
    Optional,
    No,
    SelfMarker,
}}

#[derive(Debug)]
pub struct USFMMarkerArrayEntry<'a> {{
    pub name_english: &'a str,
    pub marker: &'a str,
    pub compulsory: bool,
    pub level: USFMMarkerLevel,
    pub highest_number_suffix: Option<u8>,
    pub nests: bool,
    pub has_content: USFMMarkerContent,
    pub printed: bool,
    pub closed: USFMMarkerClosed,
    pub occurs_in: &'a str,
    pub deprecated: bool,
    pub description: Option<&'a str>,
}}

pub static USFM_MARKER_ARRAY: [USFMMarkerArrayEntry; {len(fullArrayEntries)}] = [
    {'\n'.join(fullArrayEntries)}
];

static USFM_MARKER_MAP: phf::Map<&'static str, usize> = phf_map! {{ {' '.join([f'{k}{v}' for k,v in markerDictEntries.items()])} }};
'''

    if not RUST_SOURCE.exists():
        print(f"Error: {RUST_SOURCE} not found")
        exit(1)

    with open( RUST_SOURCE, 'rt', encoding='utf-8' ) as source_file:
        rust_text = source_file.read()

    rust_text = ( rust_text
                 .replace( '//WARNINGS_GO_HERE', f'''// WARNING: DO NOT EDIT THIS FILE!!!
//   This file was created by build_static_tables.py {VERSION_STR}
//   To change the functions in this library, edit lib.src.rs''' )
                 .replace( '//STATIC_STRUCTS_GO_HERE', f'''
{static_rust_structs_str}
''' )
                 )

    RUST_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open( RUST_OUTPUT, 'wt', encoding='utf-8' ) as rust_output_file:
        rust_output_file.write( rust_text )

    print( "build_static_tables.py SUCCESSFUL!" )
